import type { Question } from '../types/quiz';

export const DEEP_BANK_QUESTIONS: Record<string, Question[]> = {
  space: [
    {
      id: 'sp_15',
      topic: '우주 & 천문학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '2021년 발사된 제임스 웹 우주망원경(JWST)이 태양과 지구의 중력이 균형을 이루어 안정적인 열 차단과 관측이 가능한 지구-태양 간의 특수 궤도 지점은?',
      options: ['제2 라그랑주 점 (L2)', '제1 라그랑주 점 (L1)', '정지궤도 (GEO)', '지구 저궤도 (LEO)'],
      correctIndex: 0,
      explanation: 'JWST는 지구로부터 약 150만 km 떨어진 L2 점에 위치하여 지구와 태양을 항상 등 뒤에 두고 극저온 적외선 관측을 안정적으로 수행합니다.',
      deepKnowledge: 'L2 지점에서는 태양, 지구, 달의 빛을 5겹의 캡톤(Kapton) 차양막 하나로 동시에 차단할 수 있어 망원경 센서를 영하 233도(40K) 이하로 유지할 수 있습니다.',
      sourceOrTrivia: 'NASA JWST Orbit and Sunshield Architecture',
    },
    {
      id: 'sp_16',
      topic: '우주 & 천문학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '태양계 최외곽을 거대한 구형 껍질 형태로 둘러싸고 있으며, 수만 년의 주기를 가진 장주기 혜성들의 발원지로 추정되는 가상의 얼음 천체 집단은?',
      options: ['오르트 구름 (Oort Cloud)', '카이퍼 벨트', '소행성대', '힐스 구름'],
      correctIndex: 0,
      explanation: '네덜란드의 천문학자 얀 오르트가 제안한 구역으로, 태양으로부터 약 2,000~100,000 AU 거리에 수조 개의 원시 미행성체들이 분포합니다.',
      deepKnowledge: '오르트 구름 외곽은 태양의 중력적 지배 영역의 한계선(약 1~2광년)에 닿아 있어, 지나가는 인근 항성의 섭동에 의해 혜성이 태양계 안쪽으로 튕겨 들어옵니다.',
      sourceOrTrivia: 'Jan Oort (1950) BAN 11',
    },
    {
      id: 'sp_17',
      topic: '우주 & 천문학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '태양과 같은 주계열성 내부에서 수소가 헬륨으로 융합할 때 주도적으로 일어나는 열핵융합 반응 체계는?',
      options: ['양성자-양성자 연쇄 반응 (p-p chain)', 'CNO 순환', '삼중 알파 반응', '탄소 연소 과정'],
      correctIndex: 0,
      explanation: '태양 질량 수준의 항성에서는 중심 온도가 약 1,500만 K 수준이므로 양성자-양성자 연쇄 반응이 전체 융합 에너지의 약 99%를 차지합니다.',
      deepKnowledge: '태양보다 1.3배 이상 무거운 별에서는 중심 온도가 더 높아 탄소, 질소, 산소를 촉매로 사용하는 CNO 순환 반응이 에너지 생산을 지배하게 됩니다.',
      sourceOrTrivia: 'Bethe & Critchfield (1938) Physical Review',
    },
    {
      id: 'sp_18',
      topic: '우주 & 천문학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '아인슈타인이 1916년 일반상대성이론으로 예측하였고 2015년 LIGO 검출기가 두 블랙홀의 병합 과정에서 사상 최초로 직접 검출에 성공한 시공간의 잔물결은?',
      options: ['중력파 (Gravitational Wave)', '우주 마이크로파 배경 복사', '우주선(Cosmic Rays)', '중성미자 진동'],
      correctIndex: 0,
      explanation: '질량을 가진 천체가 가속 운동할 때 시공간 곡률의 변화가 빛의 속도로 전파되는 현상으로, GW150914 관측으로 노벨 물리학상이 수여되었습니다.',
      deepKnowledge: '중력파 검출기 LIGO는 4km 길이의 두 직교 진공 터널에서 레이저 간섭계를 이용해 양성자 지름의 만분의 1 수준의 미세한 시공간 길이 왜곡을 측정했습니다.',
      sourceOrTrivia: 'Abbott et al. (LIGO Scientific Collaboration, 2016) PRL',
    },
    {
      id: 'sp_19',
      topic: '우주 & 천문학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '토성의 얼음 위성으로, 남극의 호랑이 줄무늬 균열에서 수증기 얼음 간헐천이 분출되어 지하에 거대한 액체 바다가 존재함이 입증된 천체는?',
      options: ['엔켈라두스 (Enceladus)', '타이탄', '미마스', '이아페투스'],
      correctIndex: 0,
      explanation: '카시니 탐사선이 발견한 엔켈라두스의 간헐천에는 물, 염분, 단순 유기화합물 및 열수구 활동의 증거인 분자 수소가 포함되어 생명체 탐사의 1순위 후보입니다.',
      deepKnowledge: '토성과의 조석력 마찰로 인해 위성 내부가 지속적으로 가열되어, 두꺼운 얼음 지각 밑에 전 위성적 규모의 따뜻한 지하 바다가 영구 유지되고 있습니다.',
      sourceOrTrivia: 'Cassini-Huygens Mission Findings (NASA/ESA)',
    },
    {
      id: 'sp_20',
      topic: '우주 & 천문학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '우주 전체 에너지 밀도의 약 68%를 차지하며, 중력에 반하여 우주의 팽창 속도를 가속시키는 미지의 척력 에너지를 무엇이라 부르는가?',
      options: ['암흑 에너지 (Dark Energy)', '암흑 물질 (Dark Matter)', '진공 붕괴 에너지', '타키온 장'],
      correctIndex: 0,
      explanation: '1998년 초신성 관측팀에 의해 우주가 가속 팽창하고 있음이 발견되었으며, 아인슈타인 방정식의 우주상수(Lambda) 또는 퀸테센스로 설명됩니다.',
      deepKnowledge: '암흑 물질이 은하를 중력으로 묶어주는 인력 역할을 하는 반면, 암흑 에너지는 우주 공간 전체에 균일한 밀도로 존재하며 척력으로 공간을 밀어냅니다.',
      sourceOrTrivia: 'Perlmutter, Riess, Schmidt (1998) Nobel Prize in Physics 2011',
    },
  ],
  korean_history: [
    {
      id: 'kh_15',
      topic: '한국사 탐구',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '신라 선덕여왕 때 자장율사의 건의로 건립되었으며, 주변 9개국의 침략을 막아내겠다는 호국 불교 염원을 담았던 거대한 목탑은?',
      options: ['황룡사 9층 목탑', '미륵사지 석탑', '다보탑', '분황사 모전석탑'],
      correctIndex: 0,
      explanation: '백제 장인 아비지를 초빙하여 축조한 약 80m 높이의 거대 목탑으로, 고려 시대 몽골의 제3차 침입 당시 불타 소실되었습니다.',
      deepKnowledge: '9층의 각 층은 일본, 중화, 오월, 탁라, 응덕, 말갈, 거란, 여진, 예맥 등 주변 9개 이민족을 복속시키고 평화를 기원하는 상징이었습니다.',
      sourceOrTrivia: '삼국유사 탑상편 황룡사 9층탑 조',
    },
    {
      id: 'kh_16',
      topic: '한국사 탐구',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '조선 정조가 왕권 강화와 인재 육성을 위해 창설한 학술 연구 기관으로, 박제가·이덕무·유득공 등 서얼 출신 실학자들을 검서관으로 등용한 곳은?',
      options: ['규장각 (奎章閣)', '집현전', '홍문관', '성균관'],
      correctIndex: 0,
      explanation: '정조는 규장각을 국왕 직속의 정책 연구 기관이자 초계문신제를 운영하는 개혁 정치의 핵심 싱크탱크로 육성했습니다.',
      deepKnowledge: '신분 차별이 엄격했던 조선 사회에서 서얼 출신 북학파 지식인들을 과감히 등용하여 <대전통편>, <무예도보통지> 등 국가적 편찬 사업을 주도하게 했습니다.',
      sourceOrTrivia: '정조실록 및 규장각지',
    },
    {
      id: 'kh_17',
      topic: '한국사 탐구',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '고려 제4대 왕 광종이 호족들의 경제적·군사적 기반을 해체하고 국가 재정과 왕권을 강화하기 위해 단행한 개혁 조치는?',
      options: ['노비안검법 (奴婢按檢法)', '전민변정도감', '과전법', '사심관 제도'],
      correctIndex: 0,
      explanation: '후삼국 통일 전쟁 과정에서 호족들이 불법으로 강점한 양민 출신 노비들의 본래 신분을 조사하여 양인으로 해방시킨 파격적 개혁이었습니다.',
      deepKnowledge: '양인이 늘어나 국가는 조세와 군역 대상자를 확보하고, 호족들은 사병과 농업 노동력을 잃어 중앙집권적 전제 왕권의 기틀이 마련되었습니다.',
      sourceOrTrivia: '고려사 광종 세가 7년조',
    },
    {
      id: 'kh_18',
      topic: '한국사 탐구',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1919년 3·1 운동의 정신을 계승하여 중국 상하이에서 수립되었으며, 국호로 "대한민국"을 정하고 삼권분립에 기초한 민주공화제 정부는?',
      options: ['대한민국 임시정부', '대한광복군 정부', '신한청년당', '한성정부'],
      correctIndex: 0,
      explanation: '대한민국 임시정부는 일제강점기 독립운동의 구심체 역할을 수행하였으며, 1948년 제헌 헌법 전문에 그 법통 계승이 명시되었습니다.',
      deepKnowledge: '임시헌장 제1조에서 "대한민국은 대한인민으로 조직한 민주공화제로 함"을 선포하여, 군주제 복벽주의를 완전히 극복하고 국민주권 시대를 열었습니다.',
      sourceOrTrivia: '대한민국 임시헌장 (1919. 4. 11 선포)',
    },
    {
      id: 'kh_19',
      topic: '한국사 탐구',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '조선 세종 대 장영실 등이 제작한 세계 최초의 자동 시보 장치 물시계로, 구슬이 떨어지며 지렛대를 작동시켜 종과 북, 징을 울리던 장치는?',
      options: ['자격루 (自擊漏)', '혼천의', '일성정시의', '앙부일구'],
      correctIndex: 0,
      explanation: '1434년 완성된 자격루는 수위의 변화에 따라 쇠구슬이 굴러떨어져 십이지신 인형이 시각에 맞춰 팻말을 들고 종을 치는 최첨단 기계식 자동화 시계였습니다.',
      deepKnowledge: '인간의 주관적 관찰과 오류를 배제하고 자연의 수압 법칙과 기계적 메커니즘을 융합하여 조선 표준시를 궁중과 백성에게 보급한 과학 기술의 정점입니다.',
      sourceOrTrivia: '세종실록 16년 7월 1일 자격루 명',
    },
    {
      id: 'kh_20',
      topic: '한국사 탐구',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '1971년 충남 공주에서 도굴되지 않은 채 온전하게 발굴되어, 무덤의 주인공과 축조 연대를 명확히 밝혀준 지석(誌石)이 출토된 삼국시대 왕릉은?',
      options: ['무령왕릉 (武寧王陵)', '천마총', '황남대총', '무용총'],
      correctIndex: 0,
      explanation: '백제 제25대 무령왕과 왕비의 합장묘로, 토지신으로부터 묘지를 샀다는 매지권(買地券) 지석이 출토되어 삼국시대 고분 중 유일하게 축조 연대가 확정되었습니다.',
      deepKnowledge: '벽돌무덤(전축분) 양식과 중국 남조 양나라제 도자기, 일본산 금송(金松) 목관 등이 함께 발견되어 백제의 탁월한 국제적 해양 교류 네트워크를 입증했습니다.',
      sourceOrTrivia: '국립공주박물관 무령왕릉 발굴 보고서',
    },
  ],
  ai_cs: [
    {
      id: 'ai_15',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '강화학습에서 에이전트가 새로운 보상을 찾기 위해 미지의 행동을 시도하는 것과, 이미 검증된 최적의 행동을 선택하는 것 사이의 근본적인 딜레마는?',
      options: ['탐색과 활용의 딜레마 (Exploration vs Exploitation)', '편향-분산 트레이드오프', '차원의 저주', '과적합과 과소적합'],
      correctIndex: 0,
      explanation: '미지의 기회를 발굴하기 위한 탐색(Exploration)과 현재 알고 있는 최선의 선택을 취하는 활용(Exploitation) 간의 최적 균형은 강화학습의 핵심입니다.',
      deepKnowledge: '이를 수학적으로 해결하기 위해 엡실론-그리디(Epsilon-greedy) 전략이나 Upper Confidence Bound(UCB) 알고리즘이 널리 활용됩니다.',
      sourceOrTrivia: 'Sutton & Barto (2018) "Reinforcement Learning: An Introduction"',
    },
    {
      id: 'ai_16',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '분산 네트워크에서 악의적인 노드가 존재하거나 통신 지연이 발생하더라도 신뢰할 수 있는 합의에 도달해야 한다는 컴퓨터 과학의 고전적 난제는?',
      options: ['비잔틴 장군 문제 (Byzantine Generals Problem)', '식사하는 철학자 문제', '생산자-소비자 문제', '정지 문제 (Halting Problem)'],
      correctIndex: 0,
      explanation: '레슬리 램포트 등이 정립한 분산 시스템 문제로, 사토시 나카모토는 작업증명(Proof of Work)을 통해 블록체인에서 이 문제를 실용적으로 해결했습니다.',
      deepKnowledge: '비잔틴 장애 허용(BFT) 시스템은 전체 노드 중 3분의 1 미만의 배신자 노드가 있더라도 올바른 합의를 보장할 수 있는 수학적 한계를 지닙니다.',
      sourceOrTrivia: 'Lamport, Shostak, Pease (1982) ACM TOPLAS',
    },
    {
      id: 'ai_17',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: 'CPU와 메모리가 물리적으로 분리된 전통적 컴퓨터 구조에서, 데이터 전송 버스의 대역폭 한계로 인해 전체 처리 속도가 제한되는 병목 현상은?',
      options: ['폰 노이만 병목현상 (Von Neumann Bottleneck)', '무어의 법칙 한계', '암달의 법칙', '메모리 누수 현상'],
      correctIndex: 0,
      explanation: '연산 장치(CPU)와 주기억장치 사이의 데이터 전송 통로가 좁아 CPU가 메모리로부터 데이터를 기다리며 공회전하는 현상입니다.',
      deepKnowledge: '현대 AI 가속기(HBM, PIM-Processing In Memory)와 뉴로모픽 칩은 연산과 저장을 한곳에서 통합 처리함으로써 이 병목을 극복하고 있습니다.',
      sourceOrTrivia: 'John Backus (1977) Turing Award Lecture',
    },
    {
      id: 'ai_18',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '출발 노드에서 목표 노드까지의 최단 경로를 탐색할 때, 실제 소요 비용 g(n)과 목표까지의 휴리스틱 추정 비용 h(n)을 결합하여 최적해를 찾는 알고리즘은?',
      options: ['A* 탐색 알고리즘 (A-star Algorithm)', '다익스트라 알고리즘', '벨만-포드 알고리즘', '플로이드-워셜 알고리즘'],
      correctIndex: 0,
      explanation: '피터 하트 등이 개발한 최고우선 탐색 알고리즘으로, 휴리스틱 함수가 실제 최단거리보다 과대평가하지 않는 한(Admissibility) 최적 경로를 보장합니다.',
      deepKnowledge: '게임 AI의 길찾기, 로봇 자율주행 경로 계획, 내비게이션 등 광범위한 분야에서 가장 널리 쓰이는 표준 최적 경로 탐색 엔진입니다.',
      sourceOrTrivia: 'Hart, Nilsson, Raphael (1968) IEEE Trans. Systems Science and Cybernetics',
    },
    {
      id: 'ai_19',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: 'LLM(대형 언어 모델)이 훈련 데이터 외의 최신 정보나 내부 문서를 검색하여 환각(Hallucination)을 줄이고 정확한 답변을 생성하도록 돕는 기술은?',
      options: ['RAG (검색 증강 생성, Retrieval-Augmented Generation)', 'LoRA 미세조정', '프롬프트 인젝션', '양자화 (Quantization)'],
      correctIndex: 0,
      explanation: '사용자의 질문과 관련된 정보를 벡터 데이터베이스 등에서 먼저 검색(Retrieve)한 뒤, 이를 LLM의 컨텍스트에 포함시켜 증강(Augment) 생성하는 기법입니다.',
      deepKnowledge: '모델을 매번 재학습시키지 않고도 기업의 방대한 사내 규정, 최신 뉴스, 전문 기술 문서 등을 실시간으로 정확하게 참조할 수 있게 만듭니다.',
      sourceOrTrivia: 'Lewis et al. (2020) "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks"',
    },
    {
      id: 'ai_20',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '거대한 두 소수의 곱을 구하기는 쉬우나, 그 곱한 결과를 다시 소인수분해하기는 극도로 어렵다는 수학적 일방향성에 기반한 대표적 비대칭 공개키 암호 알고리즘은?',
      options: ['RSA 암호 알고리즘', 'AES 대칭키 암호', 'DES 암호', 'SHA-256 해시'],
      correctIndex: 0,
      explanation: '리베스트(Rivest), 샤미르(Shamir), 에이들먼(Adleman)이 1977년 개발한 공개키 암호 체계로, 현대 인터넷 전자상거래와 보안 통신의 초석입니다.',
      deepKnowledge: '양자컴퓨터가 상용화되면 피터 쇼어가 고안한 쇼어 알고리즘(Shor\'s Algorithm)을 통해 다항 시간 내에 RSA 암호가 해독될 수 있어 양자내성암호(PQC)로의 전환이 진행 중입니다.',
      sourceOrTrivia: 'Rivest, Shamir, Adleman (1978) Communications of the ACM',
    },
  ],
  physics_quantum: [
    {
      id: 'pq_15',
      topic: '물리학 & 양자역학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '물질의 온도가 절대영도(0K)에 극도로 근접할 때, 입자들이 최저 에너지 상태로 일제히 떨어지며 거시적인 단일 양자 파동으로 행동하는 물질 상태는?',
      options: ['보스-아인슈타인 응축 (Bose-Einstein Condensate, BEC)', '플라스마 상태', '초임계 유체', '페르미 액체'],
      correctIndex: 0,
      explanation: '사티엔드라 나트 보스와 알베르트 아인슈타인이 예견하고 1995년 루비듐 원자 기체 냉각 실험을 통해 최초로 구현된 제5의 물질 상태입니다.',
      deepKnowledge: '개별 원자의 파동함수가 서로 겹쳐 거대한 단일 양자 파동을 형성함으로써, 양자역학적 기이한 현상(초유체성, 양자 소용돌이 등)을 눈으로 직접 관측할 수 있습니다.',
      sourceOrTrivia: 'Anderson et al. & Davis et al. (1995) Science',
    },
    {
      id: 'pq_16',
      topic: '물리학 & 양자역학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: 'X선이 정지해 있는 전자와 충돌한 후 산란될 때, 파장이 처음보다 길어지는 현상을 발견하여 빛이 파동뿐 아니라 운동량을 가진 입자임을 입증한 실험은?',
      options: ['콤프턴 산란 (Compton Scattering)', '광전효과', '영의 이중슬릿 실험', '데이비슨-거머 실험'],
      correctIndex: 0,
      explanation: '아서 콤프턴이 1923년 발표한 현상으로, 광자와 전자의 충돌을 고전 당구공의 탄성 충돌처럼 에너지와 운동량 보존 법칙으로 완벽히 설명해 냈습니다.',
      deepKnowledge: '광자가 전자에게 운동량의 일부를 전달하고 튕겨 나가면서 에너지를 잃고(E=hf), 따라서 진동수가 감소하고 파장이 길어지게 됩니다.',
      sourceOrTrivia: 'Arthur H. Compton (1923) Physical Review',
    },
    {
      id: 'pq_17',
      topic: '물리학 & 양자역학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '수학자 에미 뇌터(Emmy Noether)가 증명한 정리로, "물리 법칙의 연속적인 대칭성이 존재할 때마다 그에 대응하는 불변의 물리량이 보존된다"는 물리학의 기본 정리는?',
      options: ['뇌터의 정리 (Noether\'s Theorem)', '벨의 정리', '골드스톤의 정리', '에른페스트의 정리'],
      correctIndex: 0,
      explanation: '시간 평행이동 대칭성에서는 에너지 보존 법칙이, 공간 평행이동 대칭성에서는 운동량 보존 법칙이 도출됨을 입증한 현대 이론물리학의 절대적 기둥입니다.',
      deepKnowledge: '회전 대칭성에서는 각운동량이 보존되고, 게이지 대칭성에서는 전하가 보존되는 등, 자연계의 모든 기본 보존 법칙이 공간과 시간의 대칭적 본성에서 유래합니다.',
      sourceOrTrivia: 'Emmy Noether (1918) "Invariante Variationsprobleme"',
    },
    {
      id: 'pq_18',
      topic: '물리학 & 양자역학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '물질이 임계 온도 이하로 냉각되어 초전도 상태에 도달할 때, 내부의 모든 자기장을 밖으로 밀어내어 완전 반자성을 나타내는 현상은?',
      options: ['마이스너 효과 (Meissner Effect)', '조셉슨 효과', '홀 효과', '제베크 효과'],
      correctIndex: 0,
      explanation: '1933년 발터 마이스너와 로베르트 옥센펠트가 발견한 현상으로, 초전도체 위에 자석을 올려놓으면 공중에 둥둥 뜨는 자기부상 현상의 원리입니다.',
      deepKnowledge: '초전도체는 단순히 전기 저항이 0인 완전 도체에 머무는 것이 아니라, 외부 자기장이 가해지면 표면에 차폐 전류를 형성해 내부 자속 밀도를 완벽히 0으로 만듭니다.',
      sourceOrTrivia: 'Meissner & Ochsenfeld (1933) Naturwissenschaften',
    },
    {
      id: 'pq_19',
      topic: '물리학 & 양자역학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '양자역학에서 한 입자의 위치와 운동량을 동시에 무한한 정밀도로 측정하는 것은 물리적으로 불가능하다는 하이젠베르크의 근본 원리는?',
      options: ['불확정성 원리 (Uncertainty Principle)', '배타 원리', '상보성 원리', '동등 원리'],
      correctIndex: 0,
      explanation: '측정 장비의 기술적 한계가 아니라 입자의 파동-입자 이중성이라는 양자적 본성 자체에서 기인하는 수학적 한계식(Δx·Δp ≥ ℏ/2)입니다.',
      deepKnowledge: '입자의 위치 파동을 좁게 국소화할수록 푸리에 변환에 의해 파장의 범위(운동량)가 무한히 넓어지므로 두 물리량은 상호 교환될 수 없습니다.',
      sourceOrTrivia: 'Werner Heisenberg (1927) Zeitschrift für Physik',
    },
    {
      id: 'pq_20',
      topic: '물리학 & 양자역학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '입자물리학의 표준모형에서 자발적 대칭성 깨짐을 통해 W/Z 보손과 쿼크 등 기본 입자들에게 질량을 부여하는 메커니즘과 연관된 보손 입자는?',
      options: ['힉스 보손 (Higgs Boson)', '글루온', '광자', '중력자'],
      correctIndex: 0,
      explanation: '2012년 유럽입자물리연구소(CERN)의 대형강입자충돌기(LHC) 실험에서 발견되어 표준모형의 마지막 퍼즐을 완성한 입자입니다.',
      deepKnowledge: '우주 초기에 온도가 내려가면서 힉스 장이 진공 기저 상태에서 대칭성을 깨뜨렸고, 이 힉스 장과 강하게 상호작용하는 입자일수록 더 큰 관성 질량을 얻게 되었습니다.',
      sourceOrTrivia: 'Higgs (1964) PRL / ATLAS & CMS Collaborations (2012) Physics Letters B',
    },
  ],
  philosophy: [
    {
      id: 'ph_15',
      topic: '철학 & 사상',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '존 롤스(John Rawls)가 <정의론>에서 사회 구성원들이 자신의 선천적 재능, 부, 사회적 계급을 전혀 모른다고 가정한 상태를 뜻하는 사고실험은?',
      options: ['무지의 베일 (Veil of Ignorance)', '자연 상태', '트롤리 딜레마', '죄수의 딜레마'],
      correctIndex: 0,
      explanation: '자신이 사회에서 가장 불리한 최하층(최소수혜자)으로 태어날 가능성을 염두에 두게 함으로써 공정하고 정의로운 사회 원칙에 합의하도록 유도하는 개념입니다.',
      deepKnowledge: '롤스는 이를 바탕으로 "평등한 기본적 자유의 원칙(제1원칙)"과 "차등의 원칙 및 기회균등의 원칙(제2원칙)"이라는 근대 헌정주의 정의론을 구축했습니다.',
      sourceOrTrivia: 'John Rawls (1971) "A Theory of Justice"',
    },
    {
      id: 'ph_16',
      topic: '철학 & 사상',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '아리스토텔레스가 어떤 사물이 왜 존재하는지 설명하기 위해 제시한 4원인설(Four Causes)에 포함되지 않는 것은?',
      options: ['우연인 (Accidental Cause)', '질료인 (Material Cause)', '형상인 (Formal Cause)', '목적인 (Final Cause)'],
      correctIndex: 0,
      explanation: '아리스토텔레스의 4원인설은 재료가 되는 질료인, 형태와 본질인 형상인, 운동을 유발하는 동력인(작용인), 존재의 목표인 목적인으로 구성됩니다.',
      deepKnowledge: '예컨대 대리석 조각상의 경우 대리석은 질료인, 조각상의 모양은 형상인, 조각가의 정과 망치는 동력인, 감상과 미의 실현은 목적인에 해당합니다.',
      sourceOrTrivia: 'Aristotle, Metaphysics Book V',
    },
    {
      id: 'ph_17',
      topic: '철학 & 사상',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '사르트르가 인간은 사물(칼, 의자)과 달리 미리 정해진 본질 없이 세상에 먼저 내던져진 후 자유로운 선택과 결단을 통해 자신을 창조해 나간다고 천명한 명제는?',
      options: ['실존이 본질에 앞선다', '신은 죽었다', '인간은 생각하는 갈대다', '나는 생각한다 고로 존재한다'],
      correctIndex: 0,
      explanation: '인간은 어떤 목적을 위해 제조된 물건이 아니므로, 자신의 삶의 의미와 책임을 전적으로 스스로 짊어져야 한다는 무신론적 실존주의의 핵심 선언입니다.',
      deepKnowledge: '사르트르는 이 절대적 자유로부터 도망치기 위해 사회적 역할 뒤에 숨거나 남 탓을 하는 자기기만적 태도를 "나쁜 믿음(Mauvaise foi)"이라 비판했습니다.',
      sourceOrTrivia: 'Jean-Paul Sartre (1946) "L\'Existentialisme est un humanisme"',
    },
    {
      id: 'ph_18',
      topic: '철학 & 사상',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '장 자크 루소가 <사회계약론>에서 개별 시민들의 사적 이익의 단순한 총합을 넘어, 공동체 전체의 보편적 공공선과 정의를 지향하는 주권 의지를 무엇이라 불렀는가?',
      options: ['일반의지 (General Will, Volonté générale)', '전체의지', '사적의지', '자유의지'],
      correctIndex: 0,
      explanation: '루소는 개개인의 이기적 요구를 합친 "전체의지(Volonté de tous)"와 달리, 시민 모두가 공공의 이익을 숙고할 때 도출되는 "일반의지"가 법의 원천이라 보았습니다.',
      deepKnowledge: '일반의지에 복종하는 것은 곧 자기가 자신에게 부여한 자율적 법률에 복종하는 것이므로, 개인은 사회 계약을 통해 진정한 도덕적 자유를 얻는다고 역설했습니다.',
      sourceOrTrivia: 'Jean-Jacques Rousseau (1762) "Du contrat social"',
    },
    {
      id: 'ph_19',
      topic: '철학 & 사상',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '토마스 쿤이 <과학혁명의 구조>에서 제안한 개념으로, 과학의 발전은 점진적 누적이 아니라 기존 이론 체계 전체가 붕괴하고 새로운 패러다임으로 교체되는 비약적 과정임을 뜻하는 말은?',
      options: ['패러다임 전환 (Paradigm Shift)', '변증법적 지양', '환원주의', '반증 가능성'],
      correctIndex: 0,
      explanation: '천동설에서 지동설, 뉴턴 역학에서 아인슈타인 상대성이론으로의 이행처럼, 정상과학의 변칙사례가 누적되어 위기에 봉착할 때 혁명적 패러다임 전환이 일어납니다.',
      deepKnowledge: '서로 다른 패러다임 사이에는 언어와 관찰 기준 자체가 달라 객관적 우열을 절대적으로 비교할 수 없다는 "공약불가능성(Incommensurability)" 개념을 제시했습니다.',
      sourceOrTrivia: 'Thomas Kuhn (1962) "The Structure of Scientific Revolutions"',
    },
    {
      id: 'ph_20',
      topic: '철학 & 사상',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '한나 아렌트가 1961년 나치 전범 아돌프 아이히만의 재판을 참관하며, 악은 사악한 괴물에 의해서만 저질러지는 것이 아니라 비판적 사유의 부재에서 비롯된다고 통찰한 개념은?',
      options: ['악의 평범성 (Banality of Evil)', '도덕적 해이', '집단 최면', '인간 소외'],
      correctIndex: 0,
      explanation: '수백만 명의 유대인을 가스실로 수송한 아이히만은 피에 굶주린 광인이 아니라, 상부의 명령을 성실히 집행하고 관료제 규정을 맹종한 평범한 공무원이었습니다.',
      deepKnowledge: '아렌트는 타인의 처지를 헤아리고 비판적으로 성찰하는 능력을 상실한 "생각 없음(Thoughtlessness)"이야말로 인류 최악의 파국적 범죄를 낳는 토양이라고 경고했습니다.',
      sourceOrTrivia: 'Hannah Arendt (1963) "Eichmann in Jerusalem: A Report on the Banality of Evil"',
    },
  ],
  world_history: [
    {
      id: 'wh_15',
      topic: '세계사 & 문명',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '1648년 30년 종교 전쟁을 종결짓고 유럽 국가 간에 종교적 불간섭과 주권 평등을 인정하여 근대 국제 질서의 기틀을 확립한 조약은?',
      options: ['베스트팔렌 조약 (Peace of Westphalia)', '위트레흐트 조약', '베르사유 조약', '빈 의정서'],
      correctIndex: 0,
      explanation: '신성 로마 제국의 제후국들에게 독자적 주권을 부여하고 칼뱅파를 공식 공인함으로써, 교황과 황제의 보편적 지배가 붕괴하고 근대 주권국가 체제가 태동했습니다.',
      deepKnowledge: '국가의 영토 내 최고 권력과 상호 내정 불간섭 원칙을 규정한 "베스트팔렌 체제"는 오늘날 UN을 비롯한 현대 국제법 및 다자외교의 원형으로 작용합니다.',
      sourceOrTrivia: 'Treaty of Westphalia (1648)',
    },
    {
      id: 'wh_16',
      topic: '세계사 & 문명',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '기원전 13세기 이집트의 파라오 람세스 2세와 히타이트 왕 하투실리 3세 사이에 맺어진 인류 역사상 기록으로 확인되는 최초의 공식 국제 평화 조약은?',
      options: ['카데시 조약 (Treaty of Kadesh)', '안탈키다스 조약', '토르데시야스 조약', '칼리아스 화약'],
      correctIndex: 0,
      explanation: '시리아 지역의 패권을 둘러싼 카데시 전투 이후 체결된 조약으로, 상호 불가침과 군사 동맹, 정치 망명자 상호 송환 조항이 점토판 쐐기문자로 보존되어 있습니다.',
      deepKnowledge: '조약의 사본은 현재 뉴욕 UN 본부 입구에 인류 최초의 평화와 외교적 합의를 상징하는 전시물로 복제 전시되어 있습니다.',
      sourceOrTrivia: 'Istanbul Archaeology Museums / UN Headquarters Display',
    },
    {
      id: 'wh_17',
      topic: '세계사 & 문명',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1215년 영국 템스 강변 러니미드에서 실지왕 존이 귀족들의 강요로 서명하여, 국왕의 자의적 과세권을 제한하고 법에 의한 지배를 천명한 문서는?',
      options: ['마그나 카르타 (대헌장, Magna Carta)', '권리청원', '권리장전', '인신보호법'],
      correctIndex: 0,
      explanation: '"자유민은 동료 귀족의 합법적 재판이나 국법에 의하지 않고서는 체포되거나 구금될 수 없다"고 선언하여 근대 입헌주의와 인권 보호의 초석이 되었습니다.',
      deepKnowledge: '국왕 또한 법 아래에 존재해야 한다는 법의 지배(Rule of Law) 원리를 확립하여 훗날 17세기 영국 청교도 혁명과 미국 독립 선언서에 결정적 영향을 미쳤습니다.',
      sourceOrTrivia: 'British Library Magna Carta Collection',
    },
    {
      id: 'wh_18',
      topic: '세계사 & 문명',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1789년 7월 14일 파리 시민들이 전제정치의 상징인 이 요새를 습격하면서 본격적인 프랑스 대혁명의 불길이 타오른 역사적 장소는?',
      options: ['바스티유 감옥 (Bastille)', '베르사유 궁전', '튈르리 궁전', '콩시에르주리'],
      correctIndex: 0,
      explanation: '루이 16세의 군대 집결에 맞서 무기를 확보하기 위해 시민들이 바스티유를 함락시켰으며, 프랑스는 현재 이 날을 국가 국경일(혁명기념일)로 기립니다.',
      deepKnowledge: '바스티유 함락 직후 국민의회는 봉건제 폐지를 선언하고 "자유, 평등, 박애"의 정신을 담은 <인간과 시민의 권리 선언(인권선언)>을 채택했습니다.',
      sourceOrTrivia: 'Soboul (1975) "The French Revolution 1787-1799"',
    },
    {
      id: 'wh_19',
      topic: '세계사 & 문명',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '1453년 오스만 제국의 젊은 술탄 메흐메트 2세가 거대한 우르반 대포와 육로 함선 수송을 통해 함락시키며, 1,000년 비잔티움(동로마) 제국을 멸망시킨 요충 도시는?',
      options: ['콘스탄티노플 (이스탄불)', '알렉산드리아', '안티오키아', '아테네'],
      correctIndex: 0,
      explanation: '철옹성이라 불리던 테오도시우스 삼중 성벽이 함락되며 중세가 공식적으로 종언을 고하고 오스만 제국이 지중해의 최강자로 부상했습니다.',
      deepKnowledge: '콘스탄티노플의 함락으로 그리스 학자들과 고대 문헌들이 대거 이탈리아 반도로 망명하여 피렌체를 중심으로 르네상스가 폭발적으로 개화하는 계기가 되었습니다.',
      sourceOrTrivia: 'Runciman (1965) "The Fall of Constantinople 1453"',
    },
    {
      id: 'wh_20',
      topic: '세계사 & 문명',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '1944년 제2차 세계대전 종전을 앞두고 44개 연합국 대표들이 모여 미국 달러를 금 1온스당 35달러로 고정하고 기축통화로 삼는 전후 국제 금융 질서를 수립한 회담은?',
      options: ['브레턴우즈 협정 (Bretton Woods Agreement)', '얄타 회담', '포츠담 회담', '플라자 합의'],
      correctIndex: 0,
      explanation: '국제통화기금(IMF)과 세계은행(IBRD)을 창설하여 전후 세계 경제 재건과 환율 안정을 도모한 현대 자본주의 세계 통화 체제의 시발점입니다.',
      deepKnowledge: '이 체제는 1971년 닉슨 대통령이 미국의 달러-금 태환 정지를 전격 선언(닉슨 쇼크)할 때까지 전 세계 고정환율 제도의 중심축으로 작동했습니다.',
      sourceOrTrivia: 'United Nations Monetary and Financial Conference (1944)',
    },
  ],
  biology_medicine: [
    {
      id: 'bio_15',
      topic: '생명과학 & 의학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '염색체 양 끝단에 위치하여 DNA 복제 시 유전 정보 손실을 막아주며, 세포가 분열할 때마다 길이가 점차 짧아져 세포의 수명과 노화를 결정하는 생체 시계는?',
      options: ['텔로미어 (Telomere)', '센트로미어', '히스톤', '뉴클레오솜'],
      correctIndex: 0,
      explanation: '엘리자베스 블랙번 등이 발견하여 2009년 노벨 생리의학상을 수상하였으며, 암세포는 텔로머레이스 효소를 과도하게 활성화해 무한 분열합니다.',
      deepKnowledge: 'DNA 중합효소가 단방향(5\'->3\')으로만 합성하는 한계로 인해 지체 가닥의 맨 끝부분이 복제되지 못하는 "말단 복제 문제"를 해결하기 위해 완충 지대로 존재합니다.',
      sourceOrTrivia: 'Blackburn, Greider, Szostak (2009) Nobel Prize in Physiology or Medicine',
    },
    {
      id: 'bio_16',
      topic: '생명과학 & 의학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: 'DNA의 염기서열 자체는 바뀌지 않으면서도, DNA 메틸화나 히스톤 단백질의 변형을 통해 유전자의 켜짐/꺼짐(스위치)이 환경이나 후천적 요인에 의해 조절되는 학문 분야는?',
      options: ['후성유전학 (Epigenetics)', '유전체학 (Genomics)', '단백질체학', '합성생물학'],
      correctIndex: 0,
      explanation: '동일한 DNA 염기서열을 가진 일란성 쌍둥이라 하더라도 성장 환경, 식습관, 스트레스에 따라 발현되는 질병과 형질이 완전히 달라지는 이유를 설명합니다.',
      deepKnowledge: 'DNA의 CpG 아일랜드에 메틸기(-CH3)가 결합하면 전사인자의 접근이 차단되어 유전자 발현이 억제되며, 이러한 후성유전적 각인은 세대를 넘어 유전될 수도 있습니다.',
      sourceOrTrivia: 'Bird (2007) Nature 447 "Perceptions of epigenetics"',
    },
    {
      id: 'bio_17',
      topic: '생명과학 & 의학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '인체에 침입한 병원체를 포식한 후 그 조각을 표면에 제시하여 헬퍼 T세포를 활성화함으로써, 선천성 면역과 후천성 적응면역을 연결하는 가장 강력한 전문 항원제시세포는?',
      options: ['수지상 세포 (Dendritic Cell)', '호중구', '적혈구', '혈소판'],
      correctIndex: 0,
      explanation: '랠프 스타인먼이 1973년 발견한 나뭇가지 모양의 면역세포로, 림프절로 이동하여 순진한 T세포(Naive T cell)에게 침입자의 몽타주를 전달합니다.',
      deepKnowledge: '수지상 세포의 발견은 현대 암 치료의 패러다임을 바꾼 항암 면역 백신과 면역관문억제제 개발의 핵심 이론적 기반이 되었습니다.',
      sourceOrTrivia: 'Steinman & Cohn (1973) J. Exp. Med.',
    },
    {
      id: 'bio_18',
      topic: '생명과학 & 의학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '린 마굴리스(Lynn Margulis)가 주창한 이론으로, 진핵세포 속의 미토콘드리아와 엽록체가 원래 독립 생활을 하던 호기성 세균과 광합성 남세균이 고대 숙주 세포 내부로 유입되어 영구 공생 진화했다고 설명하는 가설은?',
      options: ['세포내공생설 (Endosymbiotic Theory)', '자연발생설', '화생설', '단속평형설'],
      correctIndex: 0,
      explanation: '미토콘드리아와 엽록체가 핵 DNA와 별개의 독자적인 원형 DNA 및 원핵생물형 70S 리보솜을 가지고 있으며, 이중막 구조로 자가 증식한다는 강력한 증거가 뒷받침합니다.',
      deepKnowledge: '산소가 맹독이었던 원시 지구에서 호기성 호흡을 하는 세균과의 세포내 공생은 폭발적인 에너지 생산을 가능하게 하여 복잡한 다세포 진핵생물 진화의 결정적 분기점이 되었습니다.',
      sourceOrTrivia: 'Lynn Margulis (1967) J. Theor. Biol.',
    },
    {
      id: 'bio_19',
      topic: '생명과학 & 의학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '세균이 바이러스(박테리오파지)의 공격을 기억하고 재침입 시 그 DNA를 절단하던 면역 체계를 응용하여, 특정 유전자 부위를 정밀하게 자르고 편집할 수 있게 만든 제3세대 유전자 가위는?',
      options: ['크리스퍼 유전자 가위 (CRISPR-Cas9)', '징크핑거 뉴클레이스', '탈렌(TALEN)', '제한효소'],
      correctIndex: 0,
      explanation: '에마뉘엘 샤르팡티에와 제니퍼 다우드나가 개발하여 2020년 노벨 화학상을 수상하였으며, 난치성 유전 질환 치료와 농작물 개량의 혁명을 이끌고 있습니다.',
      deepKnowledge: '가이드 RNA(gRNA)가 타깃 DNA 염기서열을 찾아가 결합하면 Cas9 단백질이 해당 이중가닥을 정밀하게 절단하여 유전자 교정 효율을 극대화합니다.',
      sourceOrTrivia: 'Jinek, Doudna, Charpentier et al. (2012) Science 337',
    },
    {
      id: 'bio_20',
      topic: '생명과학 & 의학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '뇌의 신경망이 고정되어 있지 않고, 새로운 학습, 경험, 훈련이나 손상 극복 과정에서 시냅스 연결을 끊임없이 재구성하고 강화하는 뇌의 적응적 능력을 무엇이라 하는가?',
      options: ['신경가소성 (Neuroplasticity)', '시냅스 피로', '활동전위', '불응기'],
      correctIndex: 0,
      explanation: '"함께 발화하는 뉴런은 함께 연결된다(Fire together, wire together)"는 헵의 학습 규칙(Hebbian Theory)처럼 뇌는 성인이 된 이후에도 구조적으로 변화합니다.',
      deepKnowledge: '뇌졸중 환자의 기능 회복 훈련, 런던 택시 운전사의 해마 부피 증가 연구, 새로운 외국어 학습 등은 뇌가 평생에 걸쳐 배선을 재조정할 수 있음을 증명합니다.',
      sourceOrTrivia: 'Maguire et al. (2000) PNAS / Doidge (2007) "The Brain That Changes Itself"',
    },
  ],
  economy: [
    {
      id: 'ec_15',
      topic: '경제 & 금융',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '중앙은행의 기준금리가 이미 0%에 도달하여 금리를 더 낮출 수 없는 유동성 함정 상태에서, 중앙은행이 장기 국채 등을 대규모로 직접 매입해 시장에 본원통화를 공급하는 비전통적 통화정책은?',
      options: ['양적완화 (Quantitative Easing, QE)', '지급준비율 인하', '재할인율 인하', '오퍼레이션 트위스트'],
      correctIndex: 0,
      explanation: '2008년 글로벌 금융위기와 2020년 코로나19 팬데믹 당시 벤 버냉키 연준 의장 등이 단행하여 장기 금리를 낮추고 신용 경색을 해소한 대표적 확장 통화정책입니다.',
      deepKnowledge: '통화정책의 파급 경로가 단기 금리 조절에서 중앙은행의 대차대조표(자산 규모) 확대로 전환되며 금융 자산 가격 상승과 부의 불평등 심화 논쟁을 낳기도 했습니다.',
      sourceOrTrivia: 'Ben Bernanke (2009) Federal Reserve Speech',
    },
    {
      id: 'ec_16',
      topic: '경제 & 금융',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '주식 가격의 기하 브라운 운동(확률 미적분)을 기반으로 주식 콜옵션과 풋옵션의 이론적 공정 가치를 산출하는 공식을 정립하여 현대 금융공학의 폭발적 성장을 이끈 수학적 모델은?',
      options: ['블랙-숄즈-머튼 모형 (Black-Scholes-Merton Model)', 'CAPM 자본자산가격결정모형', '마코위츠 포트폴리오 이론', '파마-프렌치 3요인 모형'],
      correctIndex: 0,
      explanation: '피셔 블랙과 마이런 숄즈가 1973년 발표하고 로버트 머튼이 확장한 모형으로, 1997년 노벨 경제학상을 수상하며 글로벌 파생상품 시장을 개척했습니다.',
      deepKnowledge: '무위험 차익거래(No-arbitrage) 원리를 통해 옵션의 리스크를 기초자산 주식으로 완벽히 델타 헤징(Delta Hedging)할 수 있음을 입증했습니다.',
      sourceOrTrivia: 'Black & Scholes (1973) Journal of Political Economy',
    },
    {
      id: 'ec_17',
      topic: '경제 & 금융',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '판매자와 구매자 간의 정보 비대칭성으로 인해 좋은 품질의 재화는 시장에서 빠져나가고 오직 결함 있는 저품질 재화(개살구)만 거래되는 시장 왜곡 현상을 설명한 이론은?',
      options: ['레몬 시장 이론 (Market for Lemons)', '트레지디 오브 더 코먼스', '코즈의 정리', '죄수의 딜레마'],
      correctIndex: 0,
      explanation: '조지 애커로프가 중고차 시장을 사례로 들어 역선택(Adverse Selection)으로 인해 시장 메커니즘 자체가 붕괴할 수 있음을 증명하여 2001년 노벨 경제학상을 수상했습니다.',
      deepKnowledge: '이를 극복하기 위해 품질 보증서 발급, 제3자 공인 인증, 브랜드 평판, 마이클 스펜스의 신호 전달(Signaling) 이론 등이 고안되었습니다.',
      sourceOrTrivia: 'George Akerlof (1970) Quarterly Journal of Economics',
    },
    {
      id: 'ec_18',
      topic: '경제 & 금융',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '조지프 슘페터가 제시한 개념으로, 기업가의 과감한 기술 혁신과 신제품 개발이 낡은 기존 산업과 비효율적 기술을 도태시키며 경제를 장기적 성장으로 이끄는 원동력은?',
      options: ['창조적 파괴 (Creative Destruction)', '보이지 않는 손', '비교우위론', '수확체감의 법칙'],
      correctIndex: 0,
      explanation: '마차 산업이 자동차 산업의 등장으로 사라지고 필름 카메라가 디지털카메라와 스마트폰에 밀려 도태되는 것처럼, 혁신에 수반되는 필연적 진화 과정입니다.',
      deepKnowledge: '슘페터는 경기 순환의 동력이 단순한 가격 균형이 아니라, 기업가 정신(Entrepreneurship)이 촉발하는 불연속적이고 파괴적인 혁신 충격이라고 보았습니다.',
      sourceOrTrivia: 'Joseph Schumpeter (1942) "Capitalism, Socialism and Democracy"',
    },
    {
      id: 'ec_19',
      topic: '경제 & 금융',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '정부가 경기 부양을 위해 국채를 발행하여 재정 지출을 늘릴 때, 채권 금리가 상승하여 민간 기업의 투자와 가계 소비를 위축시키는 거시경제적 역효과는?',
      options: ['구축 효과 (Crowding-out Effect)', '승수 효과', '피구 효과', '기펜재 효과'],
      correctIndex: 0,
      explanation: '정부의 대규모 자금 조달이 금융시장의 자금을 빨아들여 실질 이자율을 밀어 올림으로써, 민간 부문의 경제 활동을 밀어내는(밀어낼 驅, 밀칠 逐) 현상입니다.',
      deepKnowledge: '고전학파는 구축 효과로 인해 확장적 재정정책의 실질적 GDP 증가 효과가 상쇄된다고 주장한 반면, 케인스학파는 유동성 함정 하에서는 효과가 매우 작다고 반박했습니다.',
      sourceOrTrivia: 'Mankiw, Macroeconomics Textbook',
    },
    {
      id: 'ec_20',
      topic: '경제 & 금융',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '대니얼 카너먼과 아모스 트버스키가 창안한 행동경제학 이론으로, 인간은 절대적 부의 수준보다 기준점(Reference point)에 기초하여 이득보다 손실에 훨씬 더 민감하게 반응(손실 회피성)한다는 모형은?',
      options: ['전망 이론 (Prospect Theory)', '기대 효용 이론', '효율적 시장 가설', '합리적 기대 가설'],
      correctIndex: 0,
      explanation: '동일한 100만 원이라도 얻었을 때의 기쁨보다 잃었을 때의 고통을 약 2~2.5배 더 크게 느끼며, 이득 구간에서는 위험 회피적이지만 손실 구간에서는 위험 추구적으로 변합니다.',
      deepKnowledge: '전통 경제학의 합리적 인간(Homo Economicus) 가정을 뒤흔들고, 심리학적 인지 편향을 경제 모델링에 성공적으로 통합하여 2002년 노벨 경제학상을 수상했습니다.',
      sourceOrTrivia: 'Kahneman & Tversky (1979) Econometrica',
    },
  ],
  art_culture: [
    {
      id: 'art_15',
      topic: '미술 & 문화예술',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '피렌체의 건축가 브루넬레스키가 체계화하고 알베르티가 이론화하여, 2차원 평면 위에 3차원 공간의 깊이와 소실점(Vanishing Point)을 수학적으로 구현한 미술 기법은?',
      options: ['선원근법 (Linear Perspective)', '스푸마토 기법', '키아로스쿠로 (명암법)', '콜라주'],
      correctIndex: 0,
      explanation: '관찰자의 시선 위치에 모든 평행선이 수렴하는 소실점을 배치함으로써 르네상스 회화에 과학적 공간감과 사실성을 불어넣은 혁명적 기법입니다.',
      deepKnowledge: '마사초의 <성 삼위일체> 프레스코화는 선원근법을 철저히 적용하여, 성당 벽면 뒤로 실제 깊은 예배당 공간이 뚫려 있는 듯한 놀라운 착시를 창조했습니다.',
      sourceOrTrivia: 'Leon Battista Alberti (1435) "De pictura"',
    },
    {
      id: 'art_16',
      topic: '미술 & 문화예술',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '1917년 마르셀 뒤샹이 기성품 남성용 소변기를 구입하여 "R. Mutt"라는 가명으로 서명한 뒤 전시회에 출품함으로써 현대 개념미술의 서막을 연 레디메이드 작품은?',
      options: ['<샘> (Fountain)', '<자전거 바퀴>', '<병걸이>', '<계단을 내려오는 누드>'],
      correctIndex: 0,
      explanation: '예술이란 작가가 손으로 직접 빚은 물리적 오브제가 아니라, 일상 사물에 새로운 맥락과 아이디어를 부여하는 "개념적 선택"임을 선언한 20세기 미술사 최대의 충격이었습니다.',
      deepKnowledge: '전통적 시각 예술의 망막적(Retinal) 쾌락을 거부하고, 관람자에게 "예술이란 무엇인가?"라는 지적 질문을 던지는 개념주의(Conceptual Art)의 효시가 되었습니다.',
      sourceOrTrivia: 'Marcel Duchamp (1917) Society of Independent Artists Exhibition',
    },
    {
      id: 'art_17',
      topic: '미술 & 문화예술',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '1919년 독일 바이마르에서 발터 그로피우스가 설립하여 순수 예술과 기술적 공예의 통합, "형태는 기능을 따른다"는 현대 산업 디자인과 기능주의 건축의 요람이 된 학교는?',
      options: ['바우하우스 (Bauhaus)', '에콜 데 보자르', '비엔나 분리파', '러시아 구성주의 아카데미'],
      correctIndex: 0,
      explanation: '칸딘스키, 클레, 미스 반 데어 로에 등이 교수진으로 참여하여 현대의 타이포그래피, 가구 디자인, 모더니즘 건축 양식의 표준을 정립했습니다.',
      deepKnowledge: '불필요한 장식을 철저히 배제하고 철골, 유리, 콘크리트 등 대량 생산 가능한 산업 재료의 본질적 아름다움을 추구하여 현대 도시 풍경을 빚어냈습니다.',
      sourceOrTrivia: 'Bauhaus Manifesto (1919) Walter Gropius',
    },
    {
      id: 'art_18',
      topic: '미술 & 문화예술',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1874년 클로드 모네가 르아브르 항구의 일출 풍경을 빠른 붓 터치로 묘사한 작품으로, 당시 비평가의 조롱에서 비롯되어 19세기 대표 미술 사조의 명칭이 된 그림은?',
      options: ['<인상, 해돋이> (Impression, soleil levant)', '<풀밭 위의 점심식사>', '<수련>', '<생라자르 기차역>'],
      correctIndex: 0,
      explanation: '비평가 루이 르루아가 "벽지 무늬보다 덜 완성된 인상(Impression)일 뿐"이라고 비아냥거린 기사에서 "인상주의"라는 명칭이 공식 탄생했습니다.',
      deepKnowledge: '튜브 물감의 발명과 기차의 보급으로 야외(En plein air)로 나간 화가들은 시시각각 변화하는 자연광과 대기의 순간적 반사 색채를 캔버스에 포착했습니다.',
      sourceOrTrivia: 'Musée Marmottan Monet Collection',
    },
    {
      id: 'art_19',
      topic: '미술 & 문화예술',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '베토벤이 프랑스 혁명의 자유 정신에 공감하여 나폴레옹에게 헌정하려 했으나, 그가 스스로 황제에 즉위하자 표지를 찢어버리고 고전주의 교향곡의 틀을 파괴한 걸작 교향곡은?',
      options: ['교향곡 제3번 <영웅> (Eroica)', '교향곡 제5번 <운명>', '교향곡 제6번 <전원>', '교향곡 제9번 <합창>'],
      correctIndex: 0,
      explanation: '전통적 고전주의 교향곡의 규격화된 균형을 깨고 약 50분에 달하는 방대한 규모와 극적인 불협화음, 인간의 투쟁과 승리를 표현하여 낭만주의 음악의 문을 열었습니다.',
      deepKnowledge: '나폴레옹이 황제 관을 쓰자 "그 역시 권력에 눈먼 필부에 불과했다"며 분노하여 악보 표지의 헌정사를 지워버리고 "한 영웅의 회상을 기리며"라는 부제를 남겼습니다.',
      sourceOrTrivia: 'Beethoven (1804) Sinfonia Eroica, Op. 55',
    },
    {
      id: 'art_20',
      topic: '미술 & 문화예술',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '중세 고딕 대성당(노트르담, 샤르트르)에서 높은 천장의 육중한 하중을 건물 바깥쪽 독립된 기둥으로 분산시켜, 외벽을 얇게 만들고 거대한 스테인드글라스를 설치할 수 있게 한 건축 혁신은?',
      options: ['플라잉 버트레스 (Flying Buttress, 공벽)', '포인티드 아치', '리브 볼트', '코린트식 기둥'],
      correctIndex: 0,
      explanation: '공중으로 뻗은 아치 형태의 지지대로, 벽체가 지탱해야 할 지붕의 횡압력을 외벽 바깥의 육중한 버트레스로 전달하는 첨단 고딕 공학의 정수입니다.',
      deepKnowledge: '두꺼운 석조 벽체로 채광이 어두웠던 로마네스크 양식과 달리, 플라잉 버트레스 덕분에 벽면 전체를 신성한 빛이 쏟아져 들어오는 대형 스테인드글라스 창문으로 채울 수 있었습니다.',
      sourceOrTrivia: 'Bony (1983) "French Gothic Architecture of the 12th and 13th Centuries"',
    },
  ],
  psychology_brain: [
    {
      id: 'psy_15',
      topic: '심리학 & 인지과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1961년 예일 대학의 스탠리 밀그램이 실시한 실험으로, 권위 있는 연구자의 지시에 따라 피험자의 65%가 치명적인 450볼트 전기충격 버튼을 누른 충격적인 심리 실험은?',
      options: ['밀그램 복종 실험 (Milgram Obedience Experiment)', '스탠퍼드 감옥 실험', '보보인형 실험', '마시멜로 실험'],
      correctIndex: 0,
      explanation: '나치 전범들이 홀로코스트를 자행한 동기를 분석하기 위한 실험으로, 평범한 인간도 권위의 지시 앞에서는 도덕적 양심을 쉽게 억압할 수 있음을 보여주었습니다.',
      deepKnowledge: '피험자들은 극심한 심리적 갈등과 고통을 호소하면서도, "실험의 모든 책임은 연구자가 진다"는 보증을 받는 순간 자율성을 상실하고 대리적 상태(Agentic state)로 진입했습니다.',
      sourceOrTrivia: 'Stanley Milgram (1963) Journal of Abnormal and Social Psychology',
    },
    {
      id: 'psy_16',
      topic: '심리학 & 인지과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '솔로몬 애시(Solomon Asch)가 선분의 길이를 비교하는 실험을 통해, 명백히 오답인 상황에서도 집단 구성원 다수가 오답을 외칠 때 피험자가 이에 굴복하여 따르는 현상은?',
      options: ['동조 효과 (Conformity Effect)', '방관자 효과', '후광 효과', '피그말리온 효과'],
      correctIndex: 0,
      explanation: '피험자의 약 75%가 최소 한 번 이상 다수의 명백한 오답에 동조했으며, 인간이 집단으로부터 배제되거나 비난받는 것을 회피하려는 강한 사회적 압력을 드러냈습니다.',
      deepKnowledge: '단 한 명이라도 집단의 의견에 반대하는 동료(이견 제시자)가 존재할 경우, 피험자의 오답 동조율이 즉시 4분의 1 이하로 급감한다는 사실도 함께 규명되었습니다.',
      sourceOrTrivia: 'Solomon Asch (1951) "Effects of group pressure upon the modification and distortion of judgments"',
    },
    {
      id: 'psy_17',
      topic: '심리학 & 인지과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '자신의 신념이나 태도와 모순되는 행동을 취했을 때 발생하는 심리적 불편감을 해소하기 위해, 자신의 행동을 번복하기보다 신념을 사후적으로 합리화하여 수정하는 현상은?',
      options: ['인지부조화 (Cognitive Dissonance)', '확증 편향', '초두 효과', '기억 왜곡'],
      correctIndex: 0,
      explanation: '레온 페스팅거의 1달러/20달러 실험에서, 지루한 과제를 하고 겨우 1달러를 받은 집단이 보상이 적은 인지적 모순을 해소하기 위해 "과제가 진짜 재미있었다"고 태도를 바꿨습니다.',
      deepKnowledge: '이솝 우화의 "신 포도" 이야기처럼, 인간은 이미 저지른 행동을 되돌릴 수 없을 때 내면의 신념이나 가치관을 왜곡하여 심리적 균형을 되찾으려 합니다.',
      sourceOrTrivia: 'Festinger & Carlsmith (1959) Journal of Abnormal and Social Psychology',
    },
    {
      id: 'psy_18',
      topic: '심리학 & 인지과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '조지 밀러(George Miller)가 1956년 논문에서 밝혀낸 것으로, 인간의 단기 작업기억(Working Memory)이 한 번에 담아둘 수 있는 정보 묶음의 용량 한계치는?',
      options: ['7 ± 2 청크 (The Magical Number 7)', '3 ± 1 청크', '12 ± 2 청크', '무제한'],
      correctIndex: 0,
      explanation: '전화번호를 010-XXXX-XXXX처럼 몇 개의 의미 있는 덩어리(Chunking)로 나누어 외우면 인간 기억 용량의 한계를 극복하는 데 큰 도움이 됩니다.',
      deepKnowledge: '현대 인지심리학 연구(ネルソン 코완 등)에 따르면 순수한 주의 집중만으로 유지할 수 있는 핵심 정보 덩어리는 실제 약 4개 내외로 더 정밀하게 추정되기도 합니다.',
      sourceOrTrivia: 'George A. Miller (1956) Psychological Review 63',
    },
    {
      id: 'psy_19',
      topic: '심리학 & 인지과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '비행기 추락 사고나 상어 공격처럼 뇌리에 강렬하게 떠오르는 생생한 기억이나 최근 뉴스 사례를 근거로, 실제 통계적 발생 확률을 과대평가하는 인지 편향은?',
      options: ['가용성 휴리스틱 (Availability Heuristic)', '대표성 휴리스틱', '닻내림 효과 (Anchoring)', '사후과잉확신 편향'],
      correctIndex: 0,
      explanation: '머릿속에서 쉽게 인출(Retrieve)할 수 있는 사례일수록 실제로도 자주 일어날 것이라고 착각하는 인간의 직관적 사고 오류입니다.',
      deepKnowledge: '통계적으로 자동차 사고 사망률이 비행기 사고보다 수백 배 높음에도 불구하고, 비행기 사고 뉴스의 시각적 충격으로 인해 비행 공포증을 겪는 이유를 설명합니다.',
      sourceOrTrivia: 'Tversky & Kahneman (1973) Cognitive Psychology',
    },
    {
      id: 'psy_20',
      topic: '심리학 & 인지과학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '중뇌의 복측 피개부(VTA)에서 분비된 신경전달물질이 측좌핵(Nucleus Accumbens)과 전두엽으로 투사되어, 쾌락의 경험보다 미래의 보상을 갈망하고 추구(Wanting)하게 만드는 보상 회로는?',
      options: ['중뇌변연계 도파민 경로 (Mesolimbic Pathway)', '세로토닌 봉선핵 경로', '노르에피네프린 청반 경로', '아세틸콜린 기저핵 경로'],
      correctIndex: 0,
      explanation: '식욕, 성욕, 게임, SNS 알림, 지적 성취감 등 인간의 모든 동기 부여와 탐닉의 엔진 역할을 수행하는 뇌의 핵심 보상 및 강화 학습 회로입니다.',
      deepKnowledge: '도파민은 이미 획득한 보상을 누리는 "좋아함(Liking-오피오이드 담당)"보다는 예측하지 못한 보상을 기대하고 쫓아가는 "원함(Wanting)"을 강렬히 자극합니다.',
      sourceOrTrivia: 'Berridge & Robinson (1998) Brain Res. Rev. "What is the role of dopamine in reward?"',
    },
  ],
  literature_classics: [
    {
      id: 'lit_15',
      topic: '문학 & 세계 고전',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '제임스 조이스의 <율리시스>나 버지니아 울프의 소설에서, 인물의 내면 심리와 무의식적 연상을 논리적 문법이나 여과 없이 끊임없이 흘러가는 대로 서술하는 혁신적 기법은?',
      options: ['의식의 흐름 (Stream of Consciousness)', '낯설게 하기 (Defamiliarization)', '소외 효과', '카타르시스'],
      correctIndex: 0,
      explanation: '심리학자 윌리엄 제임스가 인간 의식의 연속성을 설명하기 위해 만든 용어를 모더니즘 문학가들이 플롯 중심의 전통 서사 구조를 해체하는 데 차용했습니다.',
      deepKnowledge: '<율리시스>의 마지막 장인 몰리 블룸의 독백은 문장부호나 마침표 없이 수만 단어에 걸쳐 인간의 원초적 사유와 관능을 여과 없이 쏟아내는 압도적 실험을 선보입니다.',
      sourceOrTrivia: 'James Joyce (1922) "Ulysses"',
    },
    {
      id: 'lit_16',
      topic: '문학 & 세계 고전',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1605년 미겔 데 세르반테스가 발표한 작품으로, 기사도 소설에 심취하여 스스로 편력 기사가 된 시골 귀족과 그의 충직한 종자 산초 판사의 여정을 풍자한 근대 최초의 장편 소설은?',
      options: ['<돈키호테> (Don Quixote)', '<데카메론>', '<가르강튀아와 팡타그뤼엘>', '<칸터베리 이야기>'],
      correctIndex: 0,
      explanation: '중세의 몰락과 기사도의 허구성을 풍자하는 동시에, 잔인하고 냉혹한 현실에 굴하지 않고 숭고한 이상을 좇는 인간의 희비극적 실존을 개척한 걸작입니다.',
      deepKnowledge: '2권에서는 돈키호테가 이미 1권이 출판되어 세상 사람들이 자신들의 모험담을 읽었다는 사실을 알고 대화하는 등 현대의 메타픽션(Metafiction) 기법을 선구적으로 구사했습니다.',
      sourceOrTrivia: 'Miguel de Cervantes (1605/1615) "El ingenioso hidalgo Don Quijote de la Mancha"',
    },
    {
      id: 'lit_17',
      topic: '문학 & 세계 고전',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '프란츠 카프카의 중편 소설 <변신>에서 어느 날 아침 불안한 꿈에서 깨어났을 때 흉측한 한 마리의 거대한 벌레(해충)로 변해버린 주인공 영업사원의 이름은?',
      options: ['그레고르 잠자 (Gregor Samsa)', '요제프 K', '카를 로스만', '라돌프 체펠'],
      correctIndex: 0,
      explanation: '가족을 부양하던 생활인으로서의 기능을 상실하자마자 가족들에게서조차 철저히 혐오당하고 소외되어 버려지는 현대 자본주의 사회의 비극적 소외를 은유합니다.',
      deepKnowledge: '카프카는 출판 당시 표지에 벌레의 구체적인 모습을 절대로 삽화로 그리지 말라고 요구하며, 관료제와 일상성 속에 갇힌 인간 내면의 모호한 실존적 불안을 강조했습니다.',
      sourceOrTrivia: 'Franz Kafka (1915) "Die Verwandlung"',
    },
    {
      id: 'lit_18',
      topic: '문학 & 세계 고전',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '셰익스피어의 4대 비극 중 하나로, 세 딸의 아첨과 진심을 구별하지 못하고 나라를 물려주었다가 광기에 휩싸여 폭풍우가 몰아치는 황야를 헤매는 노왕의 비극은?',
      options: ['<리어왕> (King Lear)', '<햄릿>', '<오셀로>', '<맥베스>'],
      correctIndex: 0,
      explanation: '거짓 아첨을 한 두 딸(고네릴, 리건)에게 버림받고 막내딸 코델리아의 진실한 사랑을 뒤늦게 깨달으나 파멸에 이르는, 권력과 혈연의 비극적 허상을 그린 작품입니다.',
      deepKnowledge: '궁정의 모든 권력과 옷을 벗어던지고 벌거벗은 인간 본연의 비참한 상태(Poor, bare, forked animal)로 마주하는 리어왕의 광기는 인간 실존의 심연을 응시합니다.',
      sourceOrTrivia: 'William Shakespeare (c. 1606) "King Lear"',
    },
    {
      id: 'lit_19',
      topic: '문학 & 세계 고전',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '도스토옙스키의 마지막 대작 <카라마조프 가의 형제들>에서 둘째 이반이 창작하여 동생 알료샤에게 들려주는 이야기로, 다시 지상에 강림한 예수를 체포하여 심문하는 사상적 에피소드는?',
      options: ['대심문관 (The Grand Inquisitor)', '지하로부터의 수기', '죄와 벌', '백치'],
      correctIndex: 0,
      explanation: '스페인 세비야를 배경으로 늙은 대심문관은 인간에게 자유란 감당할 수 없는 저주일 뿐이라며, 빵과 기적과 권위로 인간을 지배해야 진정한 행복을 줄 수 있다고 예수를 기소합니다.',
      deepKnowledge: '예수는 대심문관의 긴 기소에 논쟁으로 반박하지 않고 조용히 늙은 심문관의 입술에 키스하는 것으로 답하며, 기독교적 사랑과 인간의 자유의지에 관한 최고봉의 사상적 대결을 펼칩니다.',
      sourceOrTrivia: 'Fyodor Dostoevsky (1880) "The Brothers Karamazov" Book V, Chapter 5',
    },
    {
      id: 'lit_20',
      topic: '문학 & 세계 고전',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '단테 알리기에리가 고대 로마 시인 베르길리우스와 영혼의 연인 베아트리체의 인도를 받으며 지옥, 연옥, 천국을 순례하는 14세기 이탈리아 토스카나 방언으로 쓰인 대서사시는?',
      options: ['<신곡> (La Divina Commedia)', '<일리아스>', '<실낙원>', '<데카메론>'],
      correctIndex: 0,
      explanation: '각 권이 33편씩(서곡 포함 총 100편) 완벽한 삼위일체 수비학적 대칭을 이루며, 3운율(Terza Rima)로 인간의 죄와 참회, 영적 구원의 여정을 장엄하게 노래했습니다.',
      deepKnowledge: '당시 지식인의 공용어였던 라틴어가 아닌 토스카나 지방의 속어(이탈리아어)로 집필함으로써 현대 표준 이탈리아어의 언어적 기초를 확립한 인류 문학사의 금자탑입니다.',
      sourceOrTrivia: 'Dante Alighieri (c. 1320) "Divina Commedia"',
    },
  ],
  earth_environment: [
    {
      id: 'geo_15',
      topic: '지구과학 & 환경생태',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '적도의 따뜻한 표층 해수가 북대서양으로 이동해 열을 방출하고 차가워져 침강한 뒤 심해를 통해 남하하는, 지구 전역의 열과 기후를 조절하는 거대한 해양 순환계는?',
      options: ['대서양 자오선 열염순환 (AMOC)', '엘니뇨 남방진동', '코리올리 순환', '쿠로시오 난류 순환'],
      correctIndex: 0,
      explanation: '지구 온난화로 그린란드 빙하가 녹아 막대한 담수가 유입되면 바닷물의 염분과 밀도가 낮아져 침강이 멈추고 순환이 붕괴할 위험(기후 임계점)이 경고되고 있습니다.',
      deepKnowledge: '영화 <투모로우>의 모티브가 된 현상으로, AMOC가 붕괴하면 유럽 대륙에 급격한 한랭화가 닥치고 적도 열대 수렴대(ITCZ)가 남하해 전 지구적 농업 파탄이 우려됩니다.',
      sourceOrTrivia: 'Rahmstorf et al. (2015) Nature Climate Change',
    },
    {
      id: 'geo_16',
      topic: '지구과학 & 환경생태',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1912년 알프레트 베게너의 대륙이동설과 해양저 확장설, 맨틀 대류설이 통합되어 정립된 것으로, 지구 표면이 여러 개의 단단한 판으로 이루어져 움직인다는 현대 지질학의 정설은?',
      options: ['판구조론 (Plate Tectonics)', '지향사 이론', '격변설', '수축설'],
      correctIndex: 0,
      explanation: '지구 암석권이 약 10여 개의 주요 판으로 쪼개져 연약권 위를 떠다니며, 판의 경계(수렴형, 발산형, 보존형)에서 화산 폭발과 지진, 조산 운동이 집중적으로 일어납니다.',
      deepKnowledge: '베게너 생전에는 대륙을 움직이는 거대한 힘의 원동력을 규명하지 못해 배척당했으나, 1960년대 음향측심기를 통한 해저 열곡과 해양 지각의 고지자기 줄무늬 역전 발견으로 완벽히 입증되었습니다.',
      sourceOrTrivia: 'Vine & Matthews (1963) Nature / Wilson (1965)',
    },
    {
      id: 'geo_17',
      topic: '지구과학 & 환경생태',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '지구 중심부 액체 상태의 외핵(철과 니켈)의 대류 운동과 지구 자전의 전향력이 결합하여 유도 전류와 강력한 지구 자기장을 영구적으로 유지하는 전자기 유체역학 이론은?',
      options: ['다이내모 이론 (Geodynamo Theory)', '자기 재연결 이론', '반 알렌 이론', '지열 플룸 이론'],
      correctIndex: 0,
      explanation: '외핵의 도전성 유체 운동이 발전기(다이내모)처럼 스스로 자기장을 재생산하여, 태양풍의 유해한 고에너지 방사선 입자로부터 지구 대기와 생명체를 보호하는 방패를 만듭니다.',
      deepKnowledge: '과거 지질 기록을 보면 지구 자기장의 북극과 남극이 완전히 뒤바뀌는 "지자기 역전(Geomagnetic Reversal)"이 수십만 년 주기로 불규칙하게 반복되어 왔음이 확인됩니다.',
      sourceOrTrivia: 'Glatzmaier & Roberts (1995) Nature "A three-dimensional self-consistent computer simulation of a geomagnetic field reversal"',
    },
    {
      id: 'geo_18',
      topic: '지구과학 & 환경생태',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '제임스 러브록(James Lovelock)이 린 마굴리스와 함께 주창한 가설로, 지구는 단순한 무기물 행성이 아니라 생물과 무생물 환경이 상호작용하며 생존에 적합한 항상성을 스스로 유지하는 하나의 거대한 유기체라는 이론은?',
      options: ['가이아 이론 (Gaia Hypothesis)', '메데아 가설', '인류원리', '단속평형이론'],
      correctIndex: 0,
      explanation: '지구 대기 중 산소 농도(약 21%)와 해양 염분 농도, 지구 평균 기온이 수억 년간 생명 유지에 최적화된 상태로 안정되게 조절되어 온 항상성을 설명합니다.',
      deepKnowledge: '데이지월드(Daisyworld) 시뮬레이션 모델을 통해, 어떠한 목적론적 의지 없이도 검은 데이지와 흰 데이지의 개체군 피드백만으로 행성 기온이 일정하게 자동 제어될 수 있음을 증명했습니다.',
      sourceOrTrivia: 'James Lovelock (1979) "Gaia: A New Look at Life on Earth"',
    },
    {
      id: 'geo_19',
      topic: '지구과학 & 환경생태',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1987년 채택된 국제 환경 협약으로, 성층권 오존층을 파괴하는 주범인 프레온 가스(CFCs, 염화불화탄소)의 생산과 사용을 전 세계적으로 전면 금지시켜 오존홀 복원에 성공한 기념비적 조약은?',
      options: ['몬트리올 의정서 (Montreal Protocol)', '교토 의정서', '파리 기후협정', '바젤 협약'],
      correctIndex: 0,
      explanation: '인류가 과학적 연구 결과(롤런드-몰리나 가설)에 기반하여 전 지구적 차원의 화학물질 퇴출에 성공한 가장 모범적인 글로벌 환경 조약으로 평가받습니다.',
      deepKnowledge: 'CFC 분자 하나에서 떨어져 나온 염소 원자(Cl)는 연쇄 촉매 반응을 일으켜 무려 10만 개 이상의 오존 분자(O3)를 산소 분자(O2)로 파괴하는 가공할 파괴력을 지닙니다.',
      sourceOrTrivia: 'UNEP Montreal Protocol on Substances that Deplete the Ozone Layer (1987)',
    },
    {
      id: 'geo_20',
      topic: '지구과학 & 환경생태',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '약 2억 5천만 년 전 고생대 말 페름기-트라이아스기 경계에서 지구상 해양 생물종의 약 96%, 육상 척추동물의 70%가 절멸한 사상 최대의 대멸종을 촉발한 원인으로 유력한 지질학적 사건은?',
      options: ['시베리아 트랩 (Siberian Traps) 현무암 분출', '칙술루브 소행성 충돌', '데칸 트랩 분출', '오르도비스기 빙하기 도래'],
      correctIndex: 0,
      explanation: '거대한 화성암 지대(LIP)에서 수백만 년간 분출된 막대한 마그마와 석탄층 연소로 대량의 온실가스가 방출되어 급격한 지구 온난화와 해양 무산소화(Anoxia)를 초래했습니다.',
      deepKnowledge: '바다가 따뜻해지며 산소가 고갈되자 혐기성 황산염 환원균이 증식하여 맹독성 황화수소(H2S) 가스가 대기로 분출되었고, 오존층이 파괴되며 전 지구적 생태계가 붕괴했습니다.',
      sourceOrTrivia: 'Burgess et al. (2014) PNAS "High-precision timeline for Earth\'s most severe extinction"',
    },
  ],
};
