import type { Question } from '../types/quiz';

export const EXPANDED_QUESTIONS: Record<string, Question[]> = {
  space: [
    {
      id: 'sp_9',
      topic: '우주 & 천문학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '우주의 방대한 나이와 수천억 개의 은하계를 고려할 때 외계 지적 생명체가 번성했어야 함에도 불구하고, 왜 우리는 아직 그들의 어떠한 흔적도 발견하지 못했는가에 대한 유명한 역설은?',
      options: ['페르미 역설 (Fermi Paradox)', '올베르스의 역설', '트윈 역설', '그랑파라독스'],
      correctIndex: 0,
      explanation: '노벨 물리학상 수상자 엔리코 페르미가 "그들은 도대체 어디에 있는가?(Where is everybody?)"라고 던진 질문에서 유래한 역설입니다.',
      deepKnowledge: '이를 해결하기 위해 지적 문명이 초공간 항행 단계에 이르기 전 자멸하거나 통과하기 힘든 생물학적/기술적 장벽이 존재한다는 "대여과기(Great Filter)" 가설이 제기되었습니다.',
      sourceOrTrivia: 'Robin Hanson (1998) "The Great Filter - Are We Almost Past It?"',
    },
    {
      id: 'sp_10',
      topic: '우주 & 천문학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '백색왜성이 전자 축퇴압으로 스스로의 중력 붕괴를 버텨낼 수 있는 최대 질량 한계치(약 1.44 태양질량)를 일컫는 천체물리학 법칙은?',
      options: ['찬드라세카르 한계 (Chandrasekhar Limit)', '슈바르츠실트 반지름', '에딩턴 한계', '톨먼-오펜하이머-볼코프 한계'],
      correctIndex: 0,
      explanation: '인도의 천체물리학자 수브라마니안 찬드라세카르가 특수상대성이론과 양자역학을 결합해 도출한 한계로, 이 질량을 초과한 별의 잔해는 중성자별이나 블랙홀로 붕괴합니다.',
      deepKnowledge: 'Ia형 초신성은 백색왜성이 동반성 물질을 흡수하다 정확히 찬드라세카르 한계에 도달하는 순간 폭발하므로, 절대 밝기가 일정하여 우주의 거리를 재는 "표준 촉광(Standard Candle)"으로 쓰입니다.',
      sourceOrTrivia: 'S. Chandrasekhar (1931) Astrophysical Journal',
    },
    {
      id: 'sp_11',
      topic: '우주 & 천문학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '1967년 조셀린 벨 버넬이 발견한 천체로, 강력한 자기장을 지닌 채 초당 수십~수백 번 빠르게 자전하며 정밀한 주기 전파 신호를 등대처럼 뿜어내는 고밀도 중성자별은?',
      options: ['펄서 (Pulsar)', '퀘이사 (Quasar)', '마그네타', '블레이저'],
      correctIndex: 0,
      explanation: '펄서는 자전축과 자기축의 불일치로 인해 지구 방향으로 주기적인 전파 펄스가 관측되는 회전하는 중성자별입니다.',
      deepKnowledge: '처음 발견되었을 때 신호 주기가 너무나 규칙적이어서 외계 지적 생명체가 보낸 전파 신호로 오인되어 "LGM-1(Little Green Men-1)"이라는 별칭이 붙기도 했습니다.',
      sourceOrTrivia: 'Hewish, Bell et al. (1968) Nature 217',
    },
    {
      id: 'sp_12',
      topic: '우주 & 천문학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '멀리 떨어진 은하일수록 지구로부터 후퇴하는 속도가 은하와의 거리에 비례하여 빨라진다는 우주 팽창의 기본 법칙은?',
      options: ['허블-르메트르 법칙 (Hubble-Lemaître Law)', '케플러 제3법칙', '슈테판-볼츠만 법칙', '티티우스-보데 법칙'],
      correctIndex: 0,
      explanation: '에드윈 허블과 조르주 르메트르가 관측 데이터와 일반상대성이론을 통해 우주 공간 자체가 균일하게 팽창하고 있음을 밝혀낸 현대 우주론의 기초입니다.',
      deepKnowledge: '2018년 국제천문연맹(IAU)은 르메트르 신부의 이론적 선구성을 공식 인정하여 명칭을 "허블-르메트르 법칙"으로 공식 개정 결의하였습니다.',
      sourceOrTrivia: 'IAU 30th General Assembly Resolution B4 (2018)',
    },
    {
      id: 'sp_13',
      topic: '우주 & 천문학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '일반상대성이론에서 두 시공간 영역을 연결하는 이론적 통로인 "웜홀(Wormhole)"의 목구멍(Throat)이 중력으로 인해 닫히지 않고 열린 상태를 유지하기 위해 필수적인 이론적 물질은?',
      options: ['음의 에너지를 지닌 외래 물질 (Exotic Matter)', '중성미자 군집', '초고밀도 반물질', '타키온 입자'],
      correctIndex: 0,
      explanation: '킵 손과 마이크 모리스의 계산에 따르면, 웜홀을 통과 가능한 상태로 안정화하려면 음의 질량 밀도(Negative Mass-Energy)와 반중력 장력을 갖는 물질이 필연적으로 요구됩니다.',
      deepKnowledge: '양자역학의 카시미르 효과(Casimir Effect) 등 미시 양자장론적 요동에서 국소적인 음의 에너지 밀도가 실제로 측정됨으로써 이론적 탐구가 계속되고 있습니다.',
      sourceOrTrivia: 'Morris & Thorne (1988) American Journal of Physics 56',
    },
    {
      id: 'sp_14',
      topic: '우주 & 천문학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '2015년 9월 14일, 인류 역사상 최초로 레이저 간섭계 중력파 관측소(LIGO)에서 직접 검출하여 아인슈타인의 100년 전 예언을 실증한 중력파 신호(GW150914)의 근원 사건은?',
      options: ['두 개의 블랙홀 쌍성 병합 사건', '중성자별 충돌 킬로노바', '초신성 1987A 폭발', '은하 중심부 초거대블랙홀 탄생'],
      correctIndex: 0,
      explanation: '약 13억 광년 떨어진 곳에서 태양 질량의 36배와 29배인 두 블랙홀이 빛의 속도 절반으로 회전하다 합병하며 3태양질량에 달하는 에너지를 중력파로 뿜어낸 사건입니다.',
      deepKnowledge: '이 역사적 관측을 주도한 라이너 바이스, 배리 배리시, 킵 손 교수는 2017년 노벨 물리학상을 수상하였으며 전자기파를 넘어선 "중력파 천문학"의 새 지평을 열었습니다.',
      sourceOrTrivia: 'Abbott et al. (LIGO Scientific Collaboration) (2016) Physical Review Letters',
    },
  ],

  korean_history: [
    {
      id: 'kh_9',
      topic: '한국사 탐구',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '고려 초기 호족 세력의 경제적·군사적 기반을 약화시키고 왕권을 대폭 강화하기 위해 불법으로 노비가 된 자들을 양인으로 해방시킨 광종의 개혁 정책은?',
      options: ['노비안검법 (956년)', '과전법', '노비종모법', '정혜쌍수'],
      correctIndex: 0,
      explanation: '광종은 노비안검법(956)으로 호족의 사병 기반을 해체하고 국가 조세를 늘렸으며, 이어 후주 귀화인 쌍기의 건의로 과거제(958)를 최초 도입해 관료제를 확립했습니다.',
      deepKnowledge: '이로 인해 양인이 늘어나 국가 재정이 비약적으로 확충되었으나, 공신과 호족들의 거센 반발을 사며 피의 숙청(피의 군주 광종)의 서막이 열리기도 했습니다.',
      sourceOrTrivia: '<고려사> 세가 권제2 광종 7년 조',
    },
    {
      id: 'kh_10',
      topic: '한국사 탐구',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '임진왜란 3대 대첩 중 하나로, 1593년 전라순찰사 권율 장군이 민관군과 부녀자들의 행주치마 돌 나르기 결사 항전으로 3만 왜군을 격퇴한 전투는?',
      options: ['행주 대첩', '한산도 대첩', '진주 대첩', '명량 해전'],
      correctIndex: 0,
      explanation: '행주산성에서 권율 장군이 화차와 신기전을 적극 활용하여 조총으로 무장한 왜군 정예 병력을 상대로 거둔 임진왜란 육상 전투 최고의 대승입니다.',
      deepKnowledge: '이 전투의 승리로 한양 수복의 결정적 전기가 마련되었으며 왜군은 남쪽으로 퇴각할 수밖에 없었습니다.',
      sourceOrTrivia: '<선조실록> 선조 26년 2월 기축 조',
    },
    {
      id: 'kh_11',
      topic: '한국사 탐구',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '조선 후기 정조가 즉위 직후 왕실 도서관이자 학술 연구 기관으로 설립하여, 박제가·이덕무 등 서얼 출신 인재를 등용하고 친위 세력을 양성한 기구는?',
      options: ['규장각', '집현전', '홍문관', '춘추관'],
      correctIndex: 0,
      explanation: '정조는 규장각을 설치하여 신분적 차별을 받던 서얼들을 검서관으로 중용하고, 젊은 문신들을 재교육하는 초계문신제를 운영하며 탕평 개혁을 주도했습니다.',
      deepKnowledge: '규장각은 단순한 왕실 서고를 넘어 국가 정책 입안과 학술 출판의 컨트롤타워이자, 노론 벽파의 권력을 견제하는 국왕의 정치적 싱크탱크였습니다.',
      sourceOrTrivia: '<정조실록> 정조 즉위년 9월 무진 조',
    },
    {
      id: 'kh_12',
      topic: '한국사 탐구',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '1894년 동학농민운동 당시 전주성을 점령한 농민군과 관군 사이에 전주화약이 맺어진 후, 전라도 각지에 설치되어 농민 자치 행정을 집행한 기구는?',
      options: ['집강소 (執綱所)', '도정호', '교정도감', '통리기무아문'],
      correctIndex: 0,
      explanation: '전주화약 체결 후 동학군은 관군과 협력하여 전라도 53개 군현에 민정 자치 기구인 집강소를 설치하고 폐정개혁안 12조를 자율적으로 실천했습니다.',
      deepKnowledge: '한국 역사상 민중이 직접 관청을 운영하며 신분제 폐지, 과부 재가 허용, 부정한 토지 개혁을 추진한 유일무이한 풀뿌리 민주 자치 모델입니다.',
      sourceOrTrivia: '오지영 <동학사(1940)> 폐정개혁조목',
    },
    {
      id: 'kh_13',
      topic: '한국사 탐구',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '1907년 안창호, 양기탁, 신채호 등이 결성한 비밀 결사 애국계몽운동 단체로, 대한제국 최초로 입헌군주제가 아닌 공화정(共和政) 국가 건설을 목표로 한 단체는?',
      options: ['신민회 (新民會)', '독립협회', '대한자강회', '의열단'],
      correctIndex: 0,
      explanation: '신민회는 실력 양성을 위해 대성학교와 오산학교를 세우고 평양 자기회사 등을 운영하는 한편, 만주 삼원보에 신흥무관학교의 모태가 되는 독립군 기지를 개척했습니다.',
      deepKnowledge: '1911년 일제가 조작한 "105인 사건"으로 조직이 강제 해체되었으나, 그 지도층과 군사 기반은 3·1 운동과 대한민국 임시정부 및 무장독립투쟁의 뼈대가 되었습니다.',
      sourceOrTrivia: '국사편찬위원회 한국독립운동사편찬위원회 <신민회의 연구>',
    },
    {
      id: 'kh_14',
      topic: '한국사 탐구',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '1919년 4월 11일 중국 상하이에서 제정·공포된 대한민국 임시헌장 제1조로, 국호 "대한민국"을 최초로 공식화하며 천명한 국가 체제는?',
      options: ['대한민국은 민주공화제로 함', '대한제국의 황권을 계승함', '군민공치주의를 표방함', '대한민국은 자유주의 연방제로 함'],
      correctIndex: 0,
      explanation: '3·1 만세운동의 자주독립 정신을 이어받은 대한민국 임시의정원은 국호를 "대한민국"으로 정하고 제1조에 "대한민국은 민주공화제로 함"을 명시해 군주제를 영구히 폐기했습니다.',
      deepKnowledge: '이는 왕(군주)의 나라였던 "대한제국(Empire)"이 백성(시민)이 주권을 갖는 "대한민국(Republic)"으로 국가 정체성이 혁명적으로 전환된 역사적 분기점입니다.',
      sourceOrTrivia: '<대한민국임시헌장> (1919년 4월 11일 선포)',
    },
  ],

  ai_cs: [
    {
      id: 'ai_9',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '분산 컴퓨팅 시스템에서 일관성(Consistency), 가용성(Availability), 분할 내성(Partition Tolerance)의 세 가지 속성을 동시에 모두 만족하는 것은 불가능하다는 정리는?',
      options: ['CAP 정리 (Brewer\'s Theorem)', '무어의 법칙', '암달의 법칙', '처치-튜링 명제'],
      correctIndex: 0,
      explanation: '에릭 브루어가 제시한 정리로, 네트워크 단절(분할)이 필연적인 분산 환경에서는 일관성을 포기하고 가용성을 택하든가(AP), 가용성을 포기하고 일관성을 택해야(CP) 합니다.',
      deepKnowledge: '이 정리는 RDBMS(전통적 트랜잭션 일관성)에서 Cassandra, MongoDB 등 대규모 수평 확장을 지향하는 NoSQL 분산 데이터베이스 설계의 철학적 기준이 되었습니다.',
      sourceOrTrivia: 'Seth Gilbert & Nancy Lynch (2002) ACM SIGACT News',
    },
    {
      id: 'ai_10',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '원본 이미지에 가우시안 노이즈를 단계적으로 주입(순방향)한 뒤, 인공신경망이 이 노이즈를 점진적으로 역으로 제거(디노이징)하도록 학습시키는 최신 생성 AI 아키텍처는?',
      options: ['확산 모델 (Diffusion Model / DDPM)', '생성적 적대 신경망 (GAN)', '순환 신경망 (RNN)', '자기부호화기 (Autoencoder)'],
      correctIndex: 0,
      explanation: 'Stable Diffusion, Midjourney, Sora 등 현대 최고 품질의 이미지/비디오 생성 모델의 핵심 뼈대로, 물리학의 비평형 열역학 확산 방정식에서 수학적 영감을 받았습니다.',
      deepKnowledge: '기존 GAN이 겪던 모드 붕괴(Mode Collapse)와 학습 불안정성을 극복하고 우수한 생성 다양성과 고해상도 품질을 안정적으로 제공합니다.',
      sourceOrTrivia: 'Sohl-Dickstein et al. (2015) & Ho et al. (2020) NeurIPS',
    },
    {
      id: 'ai_11',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '다익스트라 알고리즘에 목표 노드까지의 추정 잔여 거리인 "휴리스틱 함수 h(n)"을 결합하여 게임 길찾기 및 내비게이션 탐색 속도를 비약적으로 향상시킨 알고리즘은?',
      options: ['A* (에이스타) 알고리즘', '벨만-포드 알고리즘', '플로이드-워셜 알고리즘', '크루스칼 알고리즘'],
      correctIndex: 0,
      explanation: 'A* 알고리즘은 "시작점부터 현재까지 이동한 실제 비용"과 "현재 위치에서 목표 지점까지의 예상 거리(휴리스틱)"를 합산한 총 추정 비용을 기준으로 우선 탐색하여, 무작위 확산을 막고 목표 지점을 향해 지능적으로 최단 경로를 찾아냅니다.',
      deepKnowledge: '목표까지의 예상 거리가 실제 소요 비용보다 결코 크지 않다는 "허용성(Admissibility)" 조건을 만족하면, 언제나 수학적으로 완벽한 최단 경로를 보장하는 우수한 특성을 지닙니다.',
      sourceOrTrivia: 'Hart, Nilsson & Raphael (1968) IEEE Transactions',
    },
    {
      id: 'ai_12',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '신뢰할 수 없는 분산 네트워크 환경에서 배신자(장애 노드)가 존재하더라도 전역적 합의를 이끌어내는 "비잔틴 장군 문제"를 계산 복잡성(작업증명, PoW)으로 실용적으로 해결한 백서는?',
      options: ['사토시 나카모토의 비트코인 백서 (2008)', '튜링의 계산 가능한 수에 대하여', '섀넌의 통신 수학적 이론', '폰 노이만 컴퓨터 보고서'],
      correctIndex: 0,
      explanation: '비트코인은 블록 생성에 막대한 해시 연산(PoW) 비용을 치르게 하고 가장 긴 체인을 정답으로 채택하는 나카모토 합의(Nakamoto Consensus)를 통해 비잔틴 장애 허용을 현실화했습니다.',
      deepKnowledge: '중앙 집중식 신뢰 기관 없이도 수학과 경제적 인센티브(게임이론)를 결합하여 비잔틴 합의를 가능하게 한 인류 분산 컴퓨팅사 최고의 혁신 중 하나입니다.',
      sourceOrTrivia: 'Satoshi Nakamoto (2008) "Bitcoin: A Peer-to-Peer Electronic Cash System"',
    },
    {
      id: 'ai_13',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '2015년 Kaiming He 등이 제안하여 딥러닝 층을 150층 이상 극단적으로 깊게 쌓을 때 발생하는 기울기 소실(Vanishing Gradient) 문제를 잔차 학습(Shortcut/Skip Connection)으로 극복한 획기적 모델은?',
      options: ['ResNet (Residual Neural Network)', 'AlexNet', 'VGGNet', 'InceptionNet'],
      correctIndex: 0,
      explanation: 'ResNet은 신경망 층을 거치며 변환된 결과에 원래의 입력값을 그대로 더해주는 잔차 연결(스킵 커넥션 / 지름길) 구조를 도입하여, 인공신경망이 100층 이상 깊어져도 학습 신호(기울기)가 사라지지 않고 원활하게 전달되도록 혁신했습니다.',
      deepKnowledge: 'ResNet은 2015년 ImageNet 챌린지에서 인간의 오차율(약 5%)보다 낮은 3.57%를 기록하여 시각 인식 분야에서 최초로 인간을 넘어선 기념비적 모델입니다.',
      sourceOrTrivia: 'He et al. (2016) "Deep Residual Learning for Image Recognition", CVPR',
    },
    {
      id: 'ai_14',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '클로드 섀넌이 1948년 정립한 개념으로, 어떤 정보 소스가 가진 불확실성(Uncertainty)이나 예측 불가능성의 정도를 정량화한 수학적 척도는?',
      options: ['정보 엔트로피 (Information Entropy)', '상호 정보량', '쿨백-라이블러 발산', '베이즈 확률'],
      correctIndex: 0,
      explanation: '섀넌의 정보 엔트로피는 발생 가능한 사건들의 확률과 각 정보량의 가중 평균(기댓값)으로 정의되며, 앞면과 뒷면 확률이 50%인 동전 던지기처럼 결과의 불확실성이 극대화될 때 정보량이 최대가 됩니다. 이는 오늘날 모든 디지털 데이터 압축 한계의 이론적 기초입니다.',
      deepKnowledge: '이 개념은 현대 기계학습의 손실 함수로 널리 쓰이는 교차 엔트로피(Cross-Entropy Loss)의 직접적인 수학적 뿌리입니다.',
      sourceOrTrivia: 'Claude Shannon (1948) "A Mathematical Theory of Communication"',
    },
  ],

  physics_quantum: [
    {
      id: 'pq_9',
      topic: '물리학 & 양자역학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '초전도 물질이 임계온도 이하로 냉각될 때, 외부에서 인가된 자기장을 내부에서 완전히 밀어내어 내부 자속밀도를 0으로 만드는 완전 반자성 현상은?',
      options: ['마이스너 효과 (Meissner Effect)', '제벡 효과', '펠티어 효과', '홀 효과'],
      correctIndex: 0,
      explanation: '1933년 발터 마이스너가 발견한 현상으로, 단순한 무저항 도체와 달리 초전도체는 이미 통과하고 있던 자기장까지도 외부로 강제 배출하며 자기부상 현상을 일으킵니다.',
      deepKnowledge: '이 현상은 자기력선이 침투하지 못해 초전도체가 자석 위에 공중 부양된 채 고정되는 퀀텀 락킹(Flux Pinning)의 기초 원리입니다.',
      sourceOrTrivia: 'W. Meissner & R. Ochsenfeld (1933) Naturwissenschaften',
    },
    {
      id: 'pq_10',
      topic: '물리학 & 양자역학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '양자역학에서 미시 입자의 파동성으로 인해, 고전역학적으로는 넘을 수 없는 에너지 장벽(퍼텐셜 벽)을 확률적으로 뚫고 통과해 버리는 현상은?',
      options: ['양자 터널링 (Quantum Tunneling)', '양자 결어긋남', '콤프턴 산란', '제이만 분열'],
      correctIndex: 0,
      explanation: '슈뢰딩거 파동함수가 장벽 내부에서 지수함수적으로 감쇠하지만 0이 되지 않기 때문에 반대편에서 입자가 발견될 유한한 확률이 존재합니다.',
      deepKnowledge: '태양 내부 온도가 고전적으로는 양성자 간 쿨롱 척력을 극복할 수 없음에도 양자 터널링 덕분에 핵융합이 일어나 우리가 빛을 쬘 수 있으며, 스마트폰 플래시 메모리 기록의 핵심 원리입니다.',
      sourceOrTrivia: 'George Gamow (1928) & Friedrich Hund',
    },
    {
      id: 'pq_11',
      topic: '물리학 & 양자역학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '스핀이 반정수(1/2, 3/2 등)인 페르미온 입자들은 동일한 양자역학적 상태(에너지 준위, 궤도, 스핀)를 동시에 공유할 수 없다는 양자역학 법칙은?',
      options: ['파울리 배타 원리 (Pauli Exclusion Principle)', '훈트 규칙', '아우프바우 원리', '하이젠베르크 불확정성'],
      correctIndex: 0,
      explanation: '볼프강 파울리가 1925년 제안한 원리로, 전자들이 하나의 궤도에 무한히 몰리지 않고 껍질을 채우게 만들어 원소의 주기율표와 물질의 단단한 부피를 형성하는 근본 이유입니다.',
      deepKnowledge: '별이 중력으로 붕괴할 때 전자 축퇴압으로 백색왜성을 지탱하고, 중성자 축퇴압으로 중성자별을 지탱하는 버팀목 역시 파울리 배타 원리의 거시적 발현입니다.',
      sourceOrTrivia: 'Wolfgang Pauli (1925) Zeitschrift für Physik',
    },
    {
      id: 'pq_12',
      topic: '물리학 & 양자역학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '불안정하게 붕괴하는 양자계를 매우 극단적으로 짧은 주기로 끊임없이 연속 관측하면 파동함수가 계속 원래 상태로 리셋되어 붕괴 자체가 정지해 버리는 역설적 양자 효과는?',
      options: ['양자 제논 효과 (Quantum Zeno Effect)', '아하로노프-봄 효과', '드하스-반알펜 효과', '에른페스트 정리'],
      correctIndex: 0,
      explanation: '고대 그리스 철학자 제논의 "날아가는 화살은 멈춰 있다"는 역설에 빗대어 이름 붙여진 효과로, 측정 행위 자체가 양자 상태의 시간 발전을 교란하고 억제함을 보여줍니다.',
      deepKnowledge: '반대로 측정 주기를 특정 조건으로 조절하면 붕괴 속도를 오히려 가속하는 "양자 반-제논 효과(Anti-Zeno Effect)"도 양자정보학에서 확인되었습니다.',
      sourceOrTrivia: 'Misra & Sudarshan (1977) Journal of Mathematical Physics',
    },
    {
      id: 'pq_13',
      topic: '물리학 & 양자역학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '독일의 수학자 에미 뇌터(Emmy Noether)가 증명한 정리로, 자연계의 모든 물리적 연속 대칭성(Continuous Symmetry)에는 항상 그에 대응하는 불변의 보존 법칙이 존재한다는 정리는?',
      options: ['뇌터의 정리 (Noether\'s Theorem)', '골드스톤 정리', '양-밀스 질량 간극', '벨의 부등식'],
      correctIndex: 0,
      explanation: '시간 평행이동 대칭성 → 에너지 보존 법칙, 공간 평행이동 대칭성 → 운동량 보존 법칙, 회전 대칭성 → 각운동량 보존 법칙이 성립함을 수학적으로 완전히 통합한 물리학사 최고의 걸작 정리입니다.',
      deepKnowledge: '알베르트 아인슈타인은 에미 뇌터를 "여성의 고등교육이 시작된 이래 탄생한 가장 위대한 수학적 천재"라고 칭송했습니다.',
      sourceOrTrivia: 'Emmy Noether (1918) Nachrichten von der Gesellschaft der Wissenschaften zu Göttingen',
    },
    {
      id: 'pq_14',
      topic: '물리학 & 양자역학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '물질이 전혀 없고 전자기장도 없는 완전한 진공 속에 두 개의 대전되지 않은 금속 평행판을 나노미터 간격으로 접근시키면, 진공 양자 요동에 의해 두 판이 서로 끌어당겨지는 현상은?',
      options: ['카시미르 효과 (Casimir Effect)', '람 이동 (Lamb Shift)', '체렌코프 방사', '슈비츠 방출'],
      correctIndex: 0,
      explanation: '네덜란드 물리학자 헨드릭 카시미르가 예언한 현상으로, 진공은 텅 빈 공간이 아니라 가상 입자들이 생성과 소멸을 반복하는 요동의 바다임을 명쾌하게 증명했습니다.',
      deepKnowledge: '두 판 사이의 좁은 공간에는 긴 파장의 진공 모드가 억제되어 판 바깥쪽의 진공 에너지 밀도가 안쪽보다 높아지며 두 판을 밀어붙이는 순수 양자 압력이 발생합니다.',
      sourceOrTrivia: 'H. B. G. Casimir (1948) Proc. Kon. Ned. Akad. Wet.',
    },
  ],

  philosophy: [
    {
      id: 'ph_9',
      topic: '철학 & 사상',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '모든 감각적 경험과 전제적 믿음을 철저히 의심하는 방법적 회의 끝에, "의심하고 있는 나의 존재만은 결코 부정할 수 없다"며 서양 근대 철학의 제1원리로 선언한 데카르트의 명제는?',
      options: ['코기토 에르고 숨 (나는 생각한다, 고로 존재한다)', '판타 레이 (만물은 흐른다)', '아모르 파티 (네 운명을 사랑하라)', '노세 테 입숨 (너 자신을 알라)'],
      correctIndex: 0,
      explanation: '데카르트의 <방법서설(1637)>에 등장하는 명제로, 감각은 착각일 수 있어도 모든 것을 의심하고 있는 사유 주체의 존재 자체는 필연적 진리라는 근대 합리론의 출발점입니다.',
      deepKnowledge: '이는 주체(Subject)와 객체(Object)를 명확히 분리하는 이원론적 세계관을 정초하여 근대 서구 과학혁명의 철학적 토대를 마련했습니다.',
      sourceOrTrivia: 'René Descartes <Discours de la méthode (1637)>',
    },
    {
      id: 'ph_10',
      topic: '철학 & 사상',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '존 롤스가 <정의론(1971)>에서 제안한 가상적 사고실험으로, 자신의 사회적 지위, 부, 지능, 건강 상태를 전혀 모르는 무지의 상태에서 합의되는 정의의 원칙을 도출하기 위한 장치는?',
      options: ['무지의 베일 (Veil of Ignorance)', '자연 상태 (State of Nature)', '파놉티콘', '원초적 동굴'],
      correctIndex: 0,
      explanation: '자신이 사회의 가장 불우한 약자(최소 수혜자)가 될 가능성을 염두에 둔 합리적 개인들은 최소 수혜자의 이익을 극대화하는 차등의 원칙(Maximin)을 선택하게 된다는 롤스의 핵심 논제입니다.',
      deepKnowledge: '이는 현대 복지국가의 철학적 정당성을 공리주의적 다수결의 횡포로부터 지켜내며 자유주의적 평등주의를 확립했습니다.',
      sourceOrTrivia: 'John Rawls <A Theory of Justice (1971)>',
    },
    {
      id: 'ph_11',
      topic: '철학 & 사상',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '제러미 벤담의 양적 공리주의를 비판하며, "배부른 돼지가 되기보다는 차라리 배고픈 인간이 되는 편이 낫고, 만족스러운 바보보다는 불만족스러운 소크라테스가 되는 편이 낫다"고 주장한 사상가는?',
      options: ['존 스튜어트 밀 (John Stuart Mill)', '아담 스미스', '토머스 홉스', '데이비드 흄'],
      correctIndex: 0,
      explanation: '존 스튜어트 밀은 쾌락에는 단순한 양적 차이뿐 아니라 지적·도덕적·예술적 고차원적 쾌락이라는 질적 차이(Qualitative Utilitarianism)가 엄연히 존재한다고 역설했습니다.',
      deepKnowledge: '밀은 <자유론(1859)>을 통해 타인에게 피해를 주지 않는 한 개인의 개성과 자유는 침해될 수 없다는 "타인 유해 원칙(Harm Principle)"을 확립했습니다.',
      sourceOrTrivia: 'J. S. Mill <Utilitarianism (1861)>',
    },
    {
      id: 'ph_12',
      topic: '철학 & 사상',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '에드문트 후설의 현상학에서, 외부 세계의 존재 여부에 대한 일상적이고 자연적인 독단적 믿음과 판단을 잠시 보류(괄호 치기)하는 행위를 뜻하는 그리스어 철학 용어는?',
      options: ['에포케 (Epoché, 판단중지)', '아파테이아 (Apatheia)', '아타락시아 (Ataraxia)', '카타르시스 (Catharsis)'],
      correctIndex: 0,
      explanation: '후설은 객관 세계의 실재성에 대한 선입견을 괄호 안에 넣어 판단을 보류할 때, 오직 순수한 의식 속에 직접 주어지는 현상 자체의 본질을 직관할 수 있다고 보았습니다.',
      deepKnowledge: '이는 하이데거의 존재론, 사르트르의 실존주의, 메를로-퐁티의 신체 지각론으로 이어지는 20세기 대륙철학의 거대한 분수령이 되었습니다.',
      sourceOrTrivia: 'Edmund Husserl <Ideen zu einer reinen Phänomenologie (1913)>',
    },
    {
      id: 'ph_13',
      topic: '철학 & 사상',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '장 폴 사르트르의 실존주의 핵심 테제로, 사물과 달리 인간은 태어날 때 미리 정해진 본질이나 운명이 없으며 오직 스스로의 선택과 행동을 통해 자신의 정체성을 창조해 나간다는 명제는?',
      options: ['실존은 본질에 앞선다 (L\'existence précède l\'essence)', '신은 죽었다', '이성적인 것이 현실적인 것이다', '영원회귀'],
      correctIndex: 0,
      explanation: '의자는 용도(본질)가 먼저 설계된 후 만들어지지만, 인간은 세상에 무방비하게 내던져진(피투성) 후 스스로 선택하며 살아가는 자유의 저주를 받았다는 실존주의 철학입니다.',
      deepKnowledge: '사르트르는 이 절대적 자유로부터 도망치기 위해 자기기만(Bad Faith, Mauvaise Foi)에 빠지지 말고 자신의 행위에 온전한 책임을 질 것을 역설했습니다.',
      sourceOrTrivia: 'Jean-Paul Sartre <L\'existentialisme est un humanisme (1946)>',
    },
    {
      id: 'ph_14',
      topic: '철학 & 사상',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '토머스 쿤이 <과학혁명의 구조(1962)>에서 밝힌 과학 발전의 메커니즘으로, 새로운 패러다임과 이전 패러다임은 개념과 세계관 자체가 달라 직접적인 공통 척도로 우열을 비교할 수 없다는 개념은?',
      options: ['통약불가능성 (Incommensurability)', '반증가능성 (Falsifiability)', '논리실증주의', '귀납적 확증성'],
      correctIndex: 0,
      explanation: '쿤은 과학이 지식의 점진적 누적이 아니라 "정상과학 → 위기 → 과학혁명(패러다임 전이)"이라는 불연속적 도약으로 발전하며, 두 패러다임 간에는 언어와 관측의 의미가 달라 단순 비교가 불가능하다고 보았습니다.',
      deepKnowledge: '이는 과학이 절대적이고 객관적인 진리의 축적이라는 전통적 신화를 해체하고, 과학 역시 공동체의 사회적 합의와 세계관의 전제 위에서 작동함을 폭로했습니다.',
      sourceOrTrivia: 'Thomas Kuhn <The Structure of Scientific Revolutions (1962)>',
    },
  ],

  world_history: [
    {
      id: 'wh_9',
      topic: '세계사 & 문명',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '1215년 영국 러니미드 평원에서 귀족들이 폭정을 일삼던 존 왕을 굴복시켜 서명하게 한 문서로, 국왕의 과세권 제한과 법에 의한 적법 절차를 규정하여 근대 입헌주의의 씨앗이 된 문서는?',
      options: ['마그나 카르타 (대헌장, Magna Carta)', '권리청원', '권리장전', '인신보호법'],
      correctIndex: 0,
      explanation: '마그나 카르타 제39조는 "어떤 자유민도 법률에 의하지 않고는 체포, 감금, 재산 몰수, 추방을 당하지 않는다"고 규정하여 군주조차 법 위에 군림할 수 없음을 선언했습니다.',
      deepKnowledge: '이 원칙은 이후 영국 명예혁명, 미국 독립선언서, 현대 세계인권선언의 법치주의(Rule of Law)의 직접적인 모태가 되었습니다.',
      sourceOrTrivia: 'Magna Carta (1215)',
    },
    {
      id: 'wh_10',
      topic: '세계사 & 문명',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1789년 7월 14일, 분노한 파리 시민들이 절대왕정의 압제와 무기 탄압의 상징이었던 감옥을 습격하면서 폭발한 유럽 근대 민주주의의 대변혁 사건은?',
      options: ['프랑스 대혁명 (바스티유 감옥 습격)', '영국 청교도 혁명', '러시아 볼셰비키 혁명', '파리 코뮌'],
      correctIndex: 0,
      explanation: '구제도(앙시앵 레짐)의 신분 불평등과 재정 파탄에 저항한 민중 봉기로, 이후 국민의회는 봉건제 폐지와 "인간과 시민의 권리선언(인권선언)"을 선포했습니다.',
      deepKnowledge: '프랑스는 오늘날에도 바스티유 습격일인 7월 14일을 가장 큰 국가 기념일인 "혁명기념일(Fête Nationale)"로 기리고 있습니다.',
      sourceOrTrivia: 'Georges Lefebvre <The Coming of the French Revolution (1939)>',
    },
    {
      id: 'wh_11',
      topic: '세계사 & 문명',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1868년 에도 막부를 무너뜨리고 메이지 덴노를 정점으로 서구의 과학기술과 입헌 제도를 적극 수용하여 아시아 최초의 근대 국민국가로 탈바꿈시킨 일본의 개혁 운동은?',
      options: ['메이지 유신 (明治維新)', '다이카 개신', '무로마치 개혁', '자유민권운동'],
      correctIndex: 0,
      explanation: '폐번치현(봉건 번 폐지), 신분제 철폐, 토지 조세 개혁, 징병제 도입을 단행하고 이와쿠라 사절단을 서구에 파견하여 부국강병을 밀어붙였습니다.',
      deepKnowledge: '이 근대화는 서양 열강의 식민지 전락을 피한 성공 모델이었으나, 동시에 군국주의와 대외 팽창주의(제국주의 침략)로 변질되는 모순을 낳았습니다.',
      sourceOrTrivia: 'W. G. Beasley <The Meiji Restoration (1972)>',
    },
    {
      id: 'wh_12',
      topic: '세계사 & 문명',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '1914년 6월 28일 보스니아의 수도에서 오스트리아-헝가리 제국의 황태자 프란츠 페르디난트가 세르비아계 민족주의 비밀결사 청년 가브릴로 프린치프에게 암살당하여 제1차 세계대전의 도화선이 된 사건은?',
      options: ['사라예보 사건 (Sarajevo Assassination)', '발칸 전쟁', '모로코 위기', '삼국 협상 결렬'],
      correctIndex: 0,
      explanation: '이 암살로 인해 오스트리아가 세르비아에 최후통첩을 보냈고, 동맹 관계에 묶여 있던 러시아, 독일, 프랑스, 영국이 잇따라 참전하며 인류 최초의 세계대전으로 비화했습니다.',
      deepKnowledge: '당시 발칸 반도는 범게르만주의와 범슬라브주의가 정면충돌하던 "유럽의 화약고"였으며, 복잡한 비밀 군사동맹망이 파국적 연쇄 반응을 촉발했습니다.',
      sourceOrTrivia: 'Christopher Clark <The Sleepwalkers: How Europe Went to War in 1914>',
    },
    {
      id: 'wh_13',
      topic: '세계사 & 문명',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1929년 10월 24일 "검은 목요일" 뉴욕 월스트리트 주가 대폭락으로 촉발되어 전 세계 자본주의 시장을 마비시킨 대공황을 타개하기 위해 프랭클린 루스벨트 미국 대통령이 단행한 정책은?',
      options: ['뉴딜 정책 (New Deal)', '마셜 플랜', '먼로 독트린', '트루먼 독트린'],
      correctIndex: 0,
      explanation: '루스벨트는 테네시강 유역 개발공사(TVA) 등 대규모 공공근로 사업, 와그너법(노동자 단결권), 사회보장법을 도입하여 유효수요를 창출하는 수정자본주의를 본격화했습니다.',
      deepKnowledge: '이는 "보이지 않는 손"에만 방치하던 자유방임주의 시장 모델의 한계를 증명하고, 정부의 적극적 시장 개입을 지지하는 케인스 경제학의 실천적 증거가 되었습니다.',
      sourceOrTrivia: 'Arthur Schlesinger Jr. <The Age of Roosevelt (1957)>',
    },
    {
      id: 'wh_14',
      topic: '세계사 & 문명',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '1944년 미국 뉴햄프셔주에서 44개 연합국 대표들이 모여 미국 달러를 35달러=금 1온스로 고정하고 다른 통화는 달러에 연동시키는 금환본위제를 도입하며 IMF와 세계은행을 탄생시킨 협정은?',
      options: ['브레턴우즈 협정 (Bretton Woods Agreement)', '플라자 합의', '루브르 합의', '스미스소니언 협정'],
      correctIndex: 0,
      explanation: '전후 세계 무역 안정을 위해 달러를 세계 기축통화로 확립한 국제 통화 금융 체제로, 1971년 닉슨 대통령의 금태환 정지(닉슨 쇼크) 전까지 세계 경제 호황을 뒷받침했습니다.',
      deepKnowledge: '당시 영국 대표였던 존 메이너드 케인스는 특정 국가의 통화 대신 초국가적 가상 기축통화인 "방코르(Bancor)"를 제안했으나 막강한 패권국 미국의 달러 중심안에 밀렸습니다.',
      sourceOrTrivia: 'Benn Steil <The Battle of Bretton Woods (2013)>',
    },
  ],

  biology_medicine: [
    {
      id: 'bio_9',
      topic: '생명과학 & 의학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '1928년 스코틀랜드의 미생물학자 알렉산더 플레밍이 휴가를 다녀온 뒤 포도상구균 배양 접시에 우연히 피어난 푸른곰팡이 주변에서 세균이 증식하지 못하는 것을 발견하여 탄생시킨 인류 최초의 항생제는?',
      options: ['페니실린 (Penicillin)', '스트렙토마이신', '아스피린', '테트라사이클린'],
      correctIndex: 0,
      explanation: '푸른곰팡이(Penicillium notatum)에서 분비되는 페니실린은 세균의 세포벽 합성을 차단해 세균을 파괴하며, 플로리와 체인의 대량 생산 성공으로 2차대전 수많은 부상병의 목숨을 구했습니다.',
      deepKnowledge: '이 우연한 발견(세렌디피티) 덕분에 과거 폐렴이나 패혈증으로 사망하던 감염병 치료의 일대 혁명이 일어났습니다.',
      sourceOrTrivia: 'Alexander Fleming (1929) British Journal of Experimental Pathology 10',
    },
    {
      id: 'bio_10',
      topic: '생명과학 & 의학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '외부 감염이나 부상으로 손상되어 부풀어 터지는 세포 괴사(Necrosis)와 달리, 생명체의 정상적인 발생과 항상성 유지를 위해 유전적으로 프로그램된 자발적 세포 자살 메커니즘은?',
      options: ['세포자멸사 / 아포토시스 (Apoptosis)', '자가포식 (Autophagy)', '엔도시토시스', '세포분열'],
      correctIndex: 0,
      explanation: '태아의 손가락 형성 과정에서 손가락 사이의 물갈퀴 세포들이 아포토시스로 사라져 손가락이 분리되며, DNA가 치명적으로 손상된 세포가 암세포로 변하지 않도록 스스로 사멸합니다.',
      deepKnowledge: '암세포는 p53 유전자 변이 등을 통해 이 세포자멸사 신호를 무시하고 불멸의 증식을 지속하는 것이 가장 치명적인 질환 기전입니다.',
      sourceOrTrivia: 'Kerr, Wyllie & Currie (1972) British Journal of Cancer 26',
    },
    {
      id: 'bio_11',
      topic: '생명과학 & 의학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: 'DNA의 염기서열(A, T, G, C) 자체는 전혀 변하지 않으면서도, 사이토신 염기에 메틸기(-CH3)가 결합하거나 히스톤 단백질이 변형되어 유전자 발현이 켜지거나 꺼지는 현상을 연구하는 생물학 분야는?',
      options: ['후성유전학 (Epigenetics)', '분자계통학', '단백질체학', '집단유전학'],
      correctIndex: 0,
      explanation: '일란성 쌍둥이가 동일한 유전자를 갖고 태어나도 식습관, 스트레스, 환경에 따라 노년기에 전혀 다른 질병을 앓는 이유가 후성유전학적 표지의 차이 때문임이 밝혀졌습니다.',
      deepKnowledge: '후성유전적 변형은 일부 세대를 거쳐 유전(후성유전적 세대 간 유전)될 수 있음이 확인되어, 라마르크의 획득형질 유전론이 현대 분자생물학에서 재조명받기도 했습니다.',
      sourceOrTrivia: 'Adrian Bird (2007) Nature 447',
    },
    {
      id: 'bio_12',
      topic: '생명과학 & 의학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: 'DNA나 RNA 같은 핵산 유전물질이 전혀 포함되어 있지 않음에도 불구하고, 비정상적으로 잘못 접힌(Misfolded) 단백질 자체가 인접한 정상 단백질의 구조를 변형시켜 전염성을 갖는 병원체는?',
      options: ['프리온 (Prion)', '비로이드 (Viroid)', '박테리오파지', '레트로바이러스'],
      correctIndex: 0,
      explanation: '스탠리 프루시너가 규명하여 1997년 노벨 생리의학상을 수상한 개념으로, 광우병(소해면상뇌증)과 크로이츠펠트-야코프병(CJD)의 원인체입니다.',
      deepKnowledge: '모든 생명체와 감염원은 핵산(유전자)을 통해서만 복제되고 전파된다는 분자생물학의 중심 원리(Central Dogma)를 정면으로 뒤흔든 충격적인 발견이었습니다.',
      sourceOrTrivia: 'Stanley B. Prusiner (1982) Science 216',
    },
    {
      id: 'bio_13',
      topic: '생명과학 & 의학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '진핵생물의 세포 내 소기관인 미토콘드리아와 엽록체가 과거 독립적으로 생활하던 호기성 세균과 광합성 시아노박테리아가 숙주 세포 속으로 유입되어 공생 관계를 형성했다는 이론은?',
      options: ['세포 내 공생설 (Endosymbiotic Theory)', '자연발생설', '화학진화설', '전체유전체 복제설'],
      correctIndex: 0,
      explanation: '린 마굴리스가 체계화한 이론으로, 미토콘드리아가 고유의 원형 DNA와 독자적인 리보솜을 갖고 2중막 구조로 자가 증식한다는 강력한 분자생물학적 증거로 확증되었습니다.',
      deepKnowledge: '이 세포 내 공생 사건 덕분에 진핵세포는 산소를 이용해 18배나 더 많은 ATP 에너지를 폭발적으로 생산할 수 있게 되어 복잡한 다세포 생물로 진화할 수 있었습니다.',
      sourceOrTrivia: 'Lynn Margulis (1967) Journal of Theoretical Biology 14',
    },
    {
      id: 'bio_14',
      topic: '생명과학 & 의학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '2006년 일본 교토대의 야마나카 신야 교수가 성체의 피부 섬유아세포에 단 4개의 특정 전사인자(Oct4, Sox2, Klf4, c-Myc)를 주입해 배아 상태의 만능 분화 능력을 되찾게 한 세포는?',
      options: ['유도만능줄기세포 (iPSCs / 역분화 줄기세포)', '성체줄기세포', '배아줄기세포', '조혈모세포'],
      correctIndex: 0,
      explanation: '이미 분화가 끝난 성체 체세포의 생물학적 시계를 거꾸로 되돌린 생명과학 혁명으로, 야마나카 신야는 2012년 노벨 생리의학상을 수상했습니다.',
      deepKnowledge: '인간 배아를 파괴하지 않고도 환자 자신의 체세포로부터 심장, 신경 등 모든 신체 장기 세포를 만들어낼 수 있어 윤리적 논란 없는 환자 맞춤형 재생의학의 지평을 열었습니다.',
      sourceOrTrivia: 'Takahashi & Yamanaka (2006) Cell 126',
    },
  ],

  economy: [
    {
      id: 'ec_9',
      topic: '경제 & 금융',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '일반적인 수요 법칙과 정반대로, 재화의 가격이 상승할 때 오히려 수요량이 증가하는 극단적인 열등재를 일컫는 경제학 용어는?',
      options: ['기펜재 (Giffen Good)', '베블런재 (Veblen Good)', '보완재', '공공재'],
      correctIndex: 0,
      explanation: '19세기 아일랜드 감자 기근 때처럼, 가난한 사람들의 주식 가격이 오르면 실질 소득이 급감(소득효과)하여 고기 등 고급 음식을 포기하고 감자를 더 사 먹게 되는 현상입니다.',
      deepKnowledge: '베블런재(과시 소비)가 "비쌀수록 폼나서 사는" 심리적 현상인 반면, 기펜재는 "소득효과가 대체효과를 완전히 압도"하여 발생하는 엄밀한 미시경제학적 이상 현상입니다.',
      sourceOrTrivia: 'Alfred Marshall <Principles of Economics (1895)>',
    },
    {
      id: 'ec_10',
      topic: '경제 & 금융',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '정부가 세금을 줄이고 국채를 발행해 재정 지출을 늘리더라도, 합리적인 국민들은 미래에 국채를 갚기 위해 세금이 오를 것을 예상해 소비를 늘리지 않고 저축을 늘리므로 총수요에 아무런 영향이 없다는 정리는?',
      options: ['리카도 대등 정리 (Ricardian Equivalence)', '밀턴 프리드먼의 항상소득가설', '피구 효과', '필립스 곡선'],
      correctIndex: 0,
      explanation: '로버트 바로가 1974년 현대 거시경제학적으로 재정립한 정리로, 조세 감면을 통한 전통적인 케인스주의 경기 부양책이 무력할 수 있음을 이론적으로 비판했습니다.',
      deepKnowledge: '다만 유동성 제약이 있는 가계나 근시안적 소비자가 많은 현실에서는 완벽히 성립하지 않는 경우가 많아 재정정책의 유효성 논쟁의 중심에 있습니다.',
      sourceOrTrivia: 'Robert J. Barro (1974) "Are Government Bonds Net Wealth?" Journal of Political Economy',
    },
    {
      id: 'ec_11',
      topic: '경제 & 금융',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '국제 기축통화국(미국)은 전 세계에 충분한 유동성을 공급하기 위해 지속적으로 무역수지 적자를 내야 하지만, 적자가 누적되면 통화 가치와 신뢰도가 하락하여 기축통화 지위가 흔들리는 구조적 모순은?',
      options: ['트리핀 딜레마 (Triffin Dilemma)', '루카스 비판', '불가능한 삼위일체', '더치 디지즈 (네덜란드병)'],
      correctIndex: 0,
      explanation: '벨기에 경제학자 로버트 트리핀이 1960년에 경고한 딜레마로, 결국 미국은 베트남 전쟁과 무역적자 누적으로 1971년 금태환을 포기하는 닉슨 쇼크를 맞이하게 되었습니다.',
      deepKnowledge: '오늘날 미국 달러 패권의 지속 가능성과 기축통화의 대체재(IMF SDR, 다극 통화 체제, 비트코인 등) 논의의 핵심 경제학적 배경입니다.',
      sourceOrTrivia: 'Robert Triffin <Gold and the Dollar Crisis (1960)>',
    },
    {
      id: 'ec_12',
      topic: '경제 & 금융',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '나심 니콜라스 탈레브가 대중화한 개념으로, 발생 확률이 극히 낮아 예측하기 어렵지만 일단 발생하면 경제와 사회 전반에 엄청난 파괴적 충격을 가져오는 예외적 사건은?',
      options: ['블랙 스완 (Black Swan)', '회색 코뿔소', '나비 효과', '데드캣 바운스'],
      correctIndex: 0,
      explanation: '17세기 호주에서 검은 백조가 발견되기 전까지 서양인들이 모든 백조는 하얗다고 믿었던 데서 유래한 용어로, 2008년 글로벌 금융위기와 코로나19 팬데믹이 대표적입니다.',
      deepKnowledge: '탈레브는 가우스 정규분포(종형 곡선) 모델에만 의존하는 현대 금융공학의 위험관리 모델이 극단값의 위험을 과소평가하고 있다고 맹렬히 비판했습니다.',
      sourceOrTrivia: 'Nassim Nicholas Taleb <The Black Swan (2007)>',
    },
    {
      id: 'ec_13',
      topic: '경제 & 금융',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '공장 매연이나 탄소 배출처럼 환경오염과 같은 부정적 외부효과를 유발하는 행위자에게 오염물질 배출량만큼 세금을 부과하여 시장의 비효율성을 교정하는 조세 제도는?',
      options: ['피구세 (Pigovian Tax)', '토빈세', '라퍼 곡선세', '부가가치세'],
      correctIndex: 0,
      explanation: '영국의 후생경제학자 아서 세실 피구가 제안한 조세로, 오염 주체가 지불하지 않는 사회적 한계비용을 사적 비용으로 내부화(Internalization)하여 최적 생산량을 유도합니다.',
      deepKnowledge: '오늘날 전 세계적으로 도입되고 있는 탄소세(Carbon Tax)와 배출권 거래제가 바로 이 피구세의 대표적인 현대적 정책 구현체입니다.',
      sourceOrTrivia: 'Arthur Cecil Pigou <The Economics of Welfare (1920)>',
    },
    {
      id: 'ec_14',
      topic: '경제 & 금융',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '중앙은행이 경기 부양을 위해 기준금리를 0% 수준까지 극단적으로 낮추었음에도 불구하고, 모든 경제주체들이 화폐를 투자나 소비 대신 그대로 현금으로 보유하려 하여 통화정책이 완전히 무력해지는 상태는?',
      options: ['유동성 함정 (Liquidity Trap)', '스태그플레이션', '하이퍼인플레이션', '디레버리징 쇼크'],
      correctIndex: 0,
      explanation: '존 메이너드 케인스가 제안한 개념으로, 채권 금리가 너무 낮아 향후 금리 상승(채권 가격 폭락)을 예상한 시장 참여자들이 돈을 쥐고만 있어 통화 공급이 실물 경제로 흐르지 않습니다.',
      deepKnowledge: '일본의 잃어버린 30년과 2008년 금융위기 이후 전 세계 중앙은행들이 금리 인하 대신 직접 자산을 매입하는 비전통적 통화정책인 "양적완화(QE)"를 단행한 근본적 이유입니다.',
      sourceOrTrivia: 'J. M. Keynes <The General Theory of Employment, Interest and Money (1936)>',
    },
  ],

  art_culture: [
    {
      id: 'art_9',
      topic: '미술 & 문화예술',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '20세기 초 파블로 피카소와 조르주 브라크가 창시한 미술 사조로, 사물을 한 각도에서만 바라보지 않고 여러 시점에서 해체한 뒤 하나의 캔버스에 평면적으로 재조합한 기법은?',
      options: ['입체주의 (Cubism / 큐비즘)', '야수주의', '초현실주의', '다다이즘'],
      correctIndex: 0,
      explanation: '피카소의 <아비뇽의 처녀들(1907)>로 출발한 큐비즘은 르네상스 이래 500년간 서양 회화를 지배해 온 단일 시점 원근법을 전복시킨 미술사 최대의 혁명입니다.',
      deepKnowledge: '폴 세잔의 "자연의 모든 형태는 원통, 구, 원뿔로 이루어져 있다"는 통찰에서 깊은 영감을 받아 3차원 공간을 2차원 평면성으로 재해석했습니다.',
      sourceOrTrivia: 'John Golding <Cubism: A History and an Analysis (1959)>',
    },
    {
      id: 'art_10',
      topic: '미술 & 문화예술',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '1874년 파리에서 열린 전시회에서 "인상주의(Impressionism)"라는 명칭이 탄생하는 계기가 되었으며, 르아브르 항구의 붉은 아침 해와 바다의 순간적인 빛의 산란을 거친 붓터치로 포착한 클로드 모네의 그림은?',
      options: ['인상, 해돋이 (Impression, Sunrise)', '수련 연작', '해바라기', '생라자르 기차역'],
      correctIndex: 0,
      explanation: '당시 비평가 루이 르루아가 "벽지 밑그림보다 성의가 없다"며 조롱조로 붙인 "인상주의자들의 전시"라는 비평 글에서 미술사상 가장 사랑받는 사조의 이름이 탄생했습니다.',
      deepKnowledge: '모네는 사물의 고유한 색이 존재하는 것이 아니라 태양빛의 각도와 시간에 따라 끊임없이 변화하는 "빛의 순간성"을 야외 사생(En plein air)으로 포착했습니다.',
      sourceOrTrivia: 'Louis Leroy (1874) Le Charivari',
    },
    {
      id: 'art_11',
      topic: '미술 & 문화예술',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '음악이 구체적인 사물을 묘사하지 않고도 인간의 영혼을 감동시키듯, 미술 역시 현실의 대상을 재현하지 않고 순수한 점, 선, 면, 색채의 자율적 조화만으로 내적 필연성을 표현해야 한다며 순수 추상회화를 개척한 러시아 화가는?',
      options: ['바실리 칸딘스키 (Wassily Kandinsky)', '카зи미르 말레비치', '에드바르 뭉크', '마크 로스코'],
      correctIndex: 0,
      explanation: '칸딘스키는 저서 <예술에서의 정신적인 것에 대하여(1911)>에서 회화가 구체적 대상(자연 모방)에서 해방되어 음악처럼 순수한 영적 울림을 창조해야 한다고 역설했습니다.',
      deepKnowledge: '그는 특정 색채를 볼 때 특정 악기의 소리를 느끼는 "공감각(Synesthesia)"의 소유자였으며, 색과 형태의 감정적 상응 관계를 체계화했습니다.',
      sourceOrTrivia: 'Wassily Kandinsky <Über das Geistige in der Kunst (1911)>',
    },
    {
      id: 'art_12',
      topic: '미술 & 문화예술',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1960년대 뉴욕에서 캠벨 수프 캔, 코카콜라 병, 마릴린 먼로 등 대량 생산된 소비 상품과 대중문화 스타의 이미지를 실크스크린 판화 기법으로 복제하여 고급 예술과 상업 미술의 경계를 무너뜨린 팝아트의 교황은?',
      options: ['앤디 워홀 (Andy Warhol)', '로이 리히텐슈타인', '키스 해링', '장 미셸 바스키아'],
      correctIndex: 0,
      explanation: '워홀은 자신의 작업실을 "더 팩토리(The Factory)"라 명명하고 예술 작품을 공장 제품처럼 조수들과 함께 대량 인쇄하여 예술가의 유일무이한 손재주 신화를 해체했습니다.',
      deepKnowledge: '"사업을 잘하는 것이 최고의 예술이다(Being good in business is the most fascinating kind of art)"라는 유명한 선언을 남겼습니다.',
      sourceOrTrivia: 'Andy Warhol <The Philosophy of Andy Warhol (1975)>',
    },
    {
      id: 'art_13',
      topic: '미술 & 문화예술',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '12세기 중엽 프랑스에서 시작된 고딕(Gothic) 성당 건축에서, 무거운 석조 지붕의 하중을 분산시켜 과거 로마네스크 양식과 달리 벽을 얇게 만들고 거대한 스테인드글라스 창문을 통해 "천상의 빛"을 끌어들일 수 있게 만든 3대 핵심 구조 혁신이 아닌 것은?',
      options: ['원형 돔과 펜덴티브 (Pendentive)', '첨두 아치 (Pointed Arch)', '늑골 교차 볼트 (Ribbed Vault)', '플라잉 버트레스 (Flying Buttress / 버팀벽)'],
      correctIndex: 0,
      explanation: '원형 돔과 펜덴티브는 비잔틴(하기아 소피아) 및 르네상스 건축의 특징입니다. 고딕 건축은 첨두 아치, 늑골 볼트, 외부 플라잉 버트레스 3개 기술로 벽체에 가해지는 압력을 외부로 빼내어 경이로운 높이와 채광을 달성했습니다.',
      deepKnowledge: '생드니 수도원장 쉬제르(Suger)는 "물질적 빛을 통해 신의 영적 빛으로 나아간다"는 신플라톤주의 신학을 바탕으로 고딕 양식의 탄생을 이끌었습니다.',
      sourceOrTrivia: 'Erwin Panofsky <Gothic Architecture and Scholasticism (1951)>',
    },
    {
      id: 'art_14',
      topic: '미술 & 문화예술',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '프랑스 철학자 미셸 푸코가 <말과 사물(1966)>의 서두 전체를 바쳐 분석한 디에고 벨라스케스의 1656년 걸작으로, 화가 자신과 공주, 시녀들, 거울에 비친 국왕 부부, 그림을 보는 관람객의 시선이 교차하며 서양 고전주의 "재현(Representation)의 표상 체계"를 해체한 회화는?',
      options: ['시녀들 (Las Meninas / 라스 메니냐스)', '브레다의 항복', '옷을 벗은 마하', '야간 순찰'],
      correctIndex: 0,
      explanation: '벨라스케스는 캔버스 앞에서 그림을 그리는 화가 자신을 화폭 안에 그려 넣고, 정작 그림의 주인공인 국왕 부부는 뒷벽의 작은 거울에만 비추어 관객의 위치와 주체의 자리를 역설적으로 전복시켰습니다.',
      deepKnowledge: '푸코는 이 그림을 통해 "주체가 보이지 않는 곳에서만 객체의 완벽한 재현이 가능하다"는 17~18세기 에피스테메(인식의 틀)의 본질을 철학적으로 규명했습니다.',
      sourceOrTrivia: 'Michel Foucault <Les Mots et les Choses (1966)> Ch. 1',
    },
  ],

  psychology_brain: [
    {
      id: 'psy_9',
      topic: '심리학 & 인지과학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '1971년 필립 짐바르도 교수가 건강한 대학생들을 교도관과 죄수 역할로 무작위 배정한 뒤, 교도관 역할을 맡은 학생들이 점차 가학적으로 변하고 죄수 역할을 맡은 학생들이 극단적 무기력과 패닉에 빠져 6일 만에 조기 중단된 악명 높은 심리학 실험은?',
      options: ['스탠퍼드 감옥 실험 (Stanford Prison Experiment)', '밀그램 복종 실험', '로젠한 가짜 환자 실험', '하로우 원숭이 애착 실험'],
      correctIndex: 0,
      explanation: '개인의 선천적 인성이나 도덕성보다, 제복이나 권력 같은 사회적 환경과 부여된 시스템(역할)이 인간의 행동을 얼마나 잔혹하게 타락시킬 수 있는지를 입증했습니다.',
      deepKnowledge: '짐바르도는 이후 이를 평범한 사람이 악마로 변하는 현상이라 하여 <루시퍼 이펙트(The Lucifer Effect)>라는 저서로 집대성했습니다.',
      sourceOrTrivia: 'Haney, Banks & Zimbardo (1973) International Journal of Criminology and Penology',
    },
    {
      id: 'psy_10',
      topic: '심리학 & 인지과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '솔로몬 애쉬(Solomon Asch)의 1951년 실험으로, 세 개의 선분 중 기준선과 길이가 같은 선분을 찾는 명백히 쉬운 문제임에도 불구하고, 앞선 연기자들이 모두 틀린 답을 말하자 피험자의 약 75%가 최소 한 번 이상 집단의 오답을 따라간 현상은?',
      options: ['동조 현상 (Conformity / 애쉬 동조 실험)', '방관자 효과', '후광 효과', '확증 편향'],
      correctIndex: 0,
      explanation: '인간은 자신의 감각과 판단이 맞다고 확신하면서도, 집단에서 배척당하거나 홀로 튀는 것을 두려워하여 명백한 오답에 굴복하는 사회적 압력을 받음을 보여주었습니다.',
      deepKnowledge: '단 한 명이라도 다른 의견을 내는 "이탈자(Ally)"가 존재할 경우 피험자의 오답 동조율은 4분의 1 이하로 급감하여 다양성과 소수 의견 보장의 중요성을 증명했습니다.',
      sourceOrTrivia: 'Solomon E. Asch (1951) "Effects of group pressure upon the modification and distortion of judgments"',
    },
    {
      id: 'psy_11',
      topic: '심리학 & 인지과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '캐나다의 신경심리학자 도널드 헵(Donald Hebb)이 1949년 제안한 신경생물학 법칙으로, "함께 발화하는 뉴런들은 함께 연결된다(Neurons that fire together, wire together)"는 뇌의 학습 및 기억 형성의 시냅스 가소성 기전은?',
      options: ['헵의 학습 규칙 (Hebbian Theory)', '전부 아니면 전무의 법칙', '골지의 망상설', '베버-페히너 법칙'],
      correctIndex: 0,
      explanation: '시냅스 전 뉴런이 시냅스 후 뉴런을 반복적으로 흥분시키면 두 뉴런 사이의 시냅스 연결 효율이 영구적으로 강화된다는 법칙으로, 현대 인공신경망 가중치 학습의 생물학적 모태입니다.',
      deepKnowledge: '이 이론은 1973년 블리스와 뢰모가 해마에서 장기 강화(LTP: Long-Term Potentiation) 현상을 실제로 전기생리학적으로 측정해 냄으로써 실증되었습니다.',
      sourceOrTrivia: 'Donald O. Hebb <The Organization of Behavior (1949)>',
    },
    {
      id: 'psy_12',
      topic: '심리학 & 인지과학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '신경과학자 안토니오 다마지오(Antonio Damasio)가 <데카르트의 오류(1994)>에서 주창한 이론으로, 복잡한 현실에서 인간의 합리적 의사결정은 순수 이성만으로 이루어지는 것이 아니라 과거 경험에 따른 신체적 정서 신호(내장 반응, 두근거림)의 안내를 받는다는 이론은?',
      options: ['신체표지 가설 (Somatic Marker Hypothesis)', '제임스-랑게 이론', '샤흐터-싱어 2요인론', '안면 피드백 가설'],
      correctIndex: 0,
      explanation: '복내측 전전두엽(vmPFC)이 손상되어 감정을 느끼지 못하는 환자들은 지능과 논리적 사고력은 정상임에도 불구하고, 일상에서 식당 고르기나 약속 잡기 같은 단순한 결정조차 내리지 못하고 마비되는 임상 관찰에서 입증되었습니다.',
      deepKnowledge: '이는 감정이 이성을 방해하는 불순물이 아니라, 오히려 수많은 선택지 중에서 나쁜 선택을 빠르게 걸러내어 이성을 작동하게 하는 필수 파트너임을 밝혔습니다.',
      sourceOrTrivia: 'Antonio Damasio <Descartes\' Error: Emotion, Reason, and the Human Brain (1994)>',
    },
    {
      id: 'psy_13',
      topic: '심리학 & 인지과학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '1964년 뉴욕에서 키티 제노비스가 주택가 한복판에서 괴한에게 살해당할 때 30여 명의 이웃이 비명을 듣고도 아무도 경찰에 신고하지 않은 사건을 계기로 심리학자 달리와 라타네가 규명한 현상은?',
      options: ['방관자 효과 (Bystander Effect / 제노비스 신드롬)', '스톡홀름 증후군', '깨진 유리창 이론', '피그말리온 효과'],
      correctIndex: 0,
      explanation: '위급한 상황을 목격한 사람이 많을수록 "다른 누군가가 신고하겠지"라며 개인이 느끼는 도덕적 책임감이 희석되는 "책임 분산(Diffusion of Responsibility)"이 주요 원인입니다.',
      deepKnowledge: '따라서 위급 상황에서 도움을 요청할 때는 "거기 파란 셔츠 입으신 분, 119에 신고해 주세요!"처럼 특정 개인을 지목해야 방관자 효과를 깰 수 있습니다.',
      sourceOrTrivia: 'Darley & Latané (1968) Journal of Personality and Social Psychology 8',
    },
    {
      id: 'psy_14',
      topic: '심리학 & 인지과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '긍정심리학자 미하이 칙센트미하이(Mihaly Csikszentmihalyi)가 정립한 개념으로, 수행하는 과제의 난이도와 자신의 숙련도가 최적의 높은 균형을 이룰 때 시간의 흐름을 잊고 완전히 자아를 몰실하며 최고의 행복과 생산성을 느끼는 심리적 상태는?',
      options: ['몰입 / 플로우 (Flow)', '마인드풀니스', '자기효능감', '게슈탈트 통합'],
      correctIndex: 0,
      explanation: '과제가 너무 쉬우면 지루함에 빠지고 과제가 너무 어려우면 불안에 빠지지만, 도전 과제와 능력이 완벽히 조화되는 좁은 통로(Flow Channel)에서 인간은 최적의 몰입을 경험합니다.',
      deepKnowledge: '외적 보상(돈, 지위) 때문이 아니라 행위 그 자체가 주는 내재적 기쁨(자가목적적 경험, Autotelic experience)이 핵심 특징입니다.',
      sourceOrTrivia: 'Mihaly Csikszentmihalyi <Flow: The Psychology of Optimal Experience (1990)>',
    },
  ],

  literature_classics: [
    {
      id: 'lit_9',
      topic: '문학 & 세계 고전',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '1605년 스페인의 미겔 데 세르반테스가 발표한 작품으로, 기사도 소설에 너무 심취한 시골 귀족이 자신을 편력 기사로 착각하고 풍차를 거인으로 여겨 돌진하는 이야기를 통해 근대 소설의 효시로 평가받는 작품은?',
      options: ['돈키호테 (Don Quixote)', '가르강튀아와 팡타그뤼엘', '캔디드', '걸리버 여행기'],
      correctIndex: 0,
      explanation: '이상주의자 돈키호테와 지극히 현실주의적인 종자 산초 판사의 대비를 통해 중세적 봉건 환상을 통렬하게 풍자하며 인류 최초의 근대 소설로 꼽힙니다.',
      deepKnowledge: '러시아 작가 투르게네프는 사색만 하고 행동하지 못하는 "햄릿형 인간"과 무모할 정도로 저돌적으로 이상을 향해 돌진하는 "돈키호테형 인간"으로 인간 유형을 양분하기도 했습니다.',
      sourceOrTrivia: 'Miguel de Cervantes <Don Quixote (1605/1615)>',
    },
    {
      id: 'lit_10',
      topic: '문학 & 세계 고전',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '"오늘 엄마가 죽었다. 아니, 어쩌면 어제인지도 모르겠다"라는 충격적인 첫 문장으로 시작하며, 뜨거운 햇빛 때문에 아랍인을 총으로 쏘아 죽였다고 증언하는 주인공 뫼르소의 부조리(Absurd)를 다룬 알베르 카뮈의 소설은?',
      options: ['이방인 (L\'Étranger)', '페스트', '추락', '시시포스 신화'],
      correctIndex: 0,
      explanation: '사회가 요구하는 거짓된 관습(어머니 장례식에서 눈물을 흘리지 않았다는 이유)으로 인해 살인죄보다 "패륜아"로 몰려 사형을 선고받는 개인과 세상의 단절을 그린 실존주의 문학의 걸작입니다.',
      deepKnowledge: '카뮈는 사회적 위선에 편승하여 거짓을 말하기를 거부한 대가로 죽음을 맞이하는 뫼르소를 가리켜 "우리 시대의 유일한 그리스도"라고 평했습니다.',
      sourceOrTrivia: 'Albert Camus <L\'Étranger (1942)>',
    },
    {
      id: 'lit_11',
      topic: '문학 & 세계 고전',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '괴테가 평생에 걸쳐 집필한 대작으로, 세상의 모든 지식을 섭렵했으나 환멸에 빠진 노학자가 악마 메피스토펠레스에게 "순간아 멈추어라, 너는 정말 아름답구나!"라고 외치는 순간 영혼을 넘기기로 계약하는 희곡은?',
      options: ['파우스트 (Faust)', '젊은 베르테르의 슬픔', '빌헬름 마이스터의 수업시대', '이피게니에'],
      correctIndex: 0,
      explanation: '파우스트는 끊임없이 방황하고 갈망하는 인간 영혼의 상징으로, 결국 악마의 유혹 속에서도 타인을 위한 간척 사업이라는 숭고한 행위 속에서 "인간은 노력하는 한 방황한다"는 구원을 얻게 됩니다.',
      deepKnowledge: '괴테는 20대 젊은 시절부터 집필을 시작해 사망하기 1년 전인 82세에 이르러서야 비로소 제2부를 최종 탈고했습니다.',
      sourceOrTrivia: 'J. W. von Goethe <Faust (1808/1832)>',
    },
    {
      id: 'lit_12',
      topic: '문학 & 세계 고전',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '조지 오웰의 디스토피아 소설 <1984>에서 당(Party)이 국민들의 사상과 언어를 통제하기 위해 어휘 수를 대폭 줄여 반역적인 생각 자체를 불가능하게 만든 인공 언어 체계는?',
      options: ['신어 (Newspeak)', '이중사고 (Doublethink)', '텔레스크린', '생각범죄 (Thoughtcrime)'],
      correctIndex: 0,
      explanation: '"전쟁은 평화, 자유는 예속, 무지는 힘"이라는 슬로건처럼, 신어는 "나쁘다(bad)"라는 단어 대신 "언굿(ungood)"을 쓰게 강제함으로써 자유나 인권 같은 체제 전복적 개념을 언어에서 영구 소멸시키려 합니다.',
      deepKnowledge: '이는 언어가 인간의 사고를 규정한다는 "언어적 상대성 가설(사피어-워프 가설)"의 가장 극단적인 디스토피아적 정치 문학 구현입니다.',
      sourceOrTrivia: 'George Orwell <Nineteen Eighty-Four (1949)> Appendix: The Principles of Newspeak',
    },
    {
      id: 'lit_13',
      topic: '문학 & 세계 고전',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '마르셀 프루스트의 대하소설 <잃어버린 시간을 찾아서>에서, 주인공이 홍차에 적신 마들렌 과자 한 조각을 입에 넣는 순간 유년 시절 콩브레 마을의 모든 기억과 감각이 생생하게 되살아나는 현상에서 유래한 인지심리학 용어는?',
      options: ['프루스트 효과 (Proust Effect / 비자의적 기억)', '자이가르닉 효과', '에빙하우스 효과', '괴테 효과'],
      correctIndex: 0,
      explanation: '후각과 미각 정보는 다른 감각과 달리 시상을 거치지 않고 감정과 기억을 담당하는 편도체 및 해마와 직접 연결되어 있어, 특정 냄새를 맡는 순간 과거의 기억이 강력하게 환기됩니다.',
      deepKnowledge: '프루스트는 지적인 노력으로 떠올리는 의지적 기억(Voluntary Memory)보다 감각을 통해 우연히 되살아나는 비자의적 기억(Involuntary Memory)만이 삶의 참된 시간을 되찾아 준다고 보았습니다.',
      sourceOrTrivia: 'Marcel Proust <Du côté de chez Swann (1913)>',
    },
    {
      id: 'lit_14',
      topic: '문학 & 세계 고전',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '콜롬비아 작가 가브리엘 가르시아 마르케스의 <백년 동안의 고독(1967)>으로 대표되는 문학 사조로, 마코도 마을에서 사람이 하늘로 승천하거나 나비 떼가 날아다니는 환상적인 마법적 사건들을 지극히 일상적인 역사적 사실과 평연하게 융합한 서사 기법은?',
      options: ['마술적 사실주의 (Magical Realism)', '신사실주의 (네오리얼리즘)', '자연주의', '초현실주의 자동기술법'],
      correctIndex: 0,
      explanation: '라틴아메리카의 식민지 역사, 토착 신화, 가혹한 독재 현실을 서구 합리주의의 틀을 깨고 환상과 현실의 경계를 허물어 표현한 현대 문학의 금자탑입니다.',
      deepKnowledge: '마르케스는 1982년 노벨 문학상을 수상하며 "환상적인 것은 우리의 상상력이 아니라 라틴아메리카의 참혹하고도 초현실적인 역사 그 자체"라고 연설했습니다.',
      sourceOrTrivia: 'Gabriel García Márquez <Cien años de soledad (1967)>',
    },
  ],

  earth_environment: [
    {
      id: 'geo_9',
      topic: '지구과학 & 환경생태',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '동태평양 페루 연안의 무역풍이 약화되면서 따뜻한 해수가 동쪽으로 이동하여 적도 태평양의 해수면 온도가 평년보다 0.5℃ 이상 비정상적으로 높게 지속되는 기상이변 현상은?',
      options: ['엘니뇨 (El Niño)', '라니냐 (La Niña)', '태풍', '용승 현상'],
      correctIndex: 0,
      explanation: '스페인어로 "아기 예수(남자아이)"를 뜻하는 엘니뇨는 크리스마스 무렵 페루 어민들이 따뜻한 해류 유입을 발견한 데서 유래했으며, 전 지구적 가뭄과 폭우를 유발합니다.',
      deepKnowledge: '반대로 무역풍이 너무 강해져 동태평양 수온이 평년보다 차가워지는 현상은 "라니냐(La Niña / 여자아이)"라고 부르며, 두 현상을 통틀어 ENSO(엘니뇨-남방진동)라 합니다.',
      sourceOrTrivia: 'NOAA Climate Prediction Center ENSO Guide',
    },
    {
      id: 'geo_10',
      topic: '지구과학 & 환경생태',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1909년 크로아티아의 지진학자 안드리야 모호로비치치가 발견한 경계면으로, 지구 내부에서 지각(암석)과 맨틀(감람암질)의 경계를 이루며 지진파의 속도가 급격히 빨라지는 불연속면은?',
      options: ['모호로비치치 불연속면 (모호면 / Moho)', '구텐베르크 불연속면', '레만 불연속면', '콘래드 불연속면'],
      correctIndex: 0,
      explanation: '지진파 관측 시 진원지에서 일정 거리 이상 떨어진 곳에 직접파보다 밀도가 높은 맨틀 상부를 통과해 굴절된 파(모호면 굴절파)가 먼저 도달함을 발견해 지각의 두께를 밝혀냈습니다.',
      deepKnowledge: '대륙 지각 아래에서는 약 30~50km 깊이에 위치하지만, 해양 지각 아래에서는 불과 5~10km 깊이로 얇게 분포합니다.',
      sourceOrTrivia: 'Andrija Mohorovičić (1910) Jahrbuch des meteorologischen Observatoriums in Zagreb',
    },
    {
      id: 'geo_11',
      topic: '지구과학 & 환경생태',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '지구의 자전으로 인해 회전 좌표계에서 운동하는 물체에 작용하는 겉보기 힘(관성력)으로, 북반구에서는 물체의 진행 방향 오른쪽으로, 남반구에서는 왼쪽으로 휘어지게 만드는 힘은?',
      options: ['코리올리 힘 (전향력 / Coriolis Force)', '원심력', '로런츠 힘', '조석력'],
      correctIndex: 0,
      explanation: '프랑스의 수학자 가스파르 귀스타브 드 코리올리가 정립한 힘으로, 대포의 탄도 궤적 왜곡뿐 아니라 북반구에서 태풍이 반시계 방향으로 회전하는 근본적인 이유입니다.',
      deepKnowledge: '적도에서는 코리올리 힘이 0이 되기 때문에 적도 부근(위도 5도 이내)에서는 열대성 저기압(태풍)이 거의 발생하지 않습니다.',
      sourceOrTrivia: 'Gaspard-Gustave de Coriolis (1835) Journal de l\'École Polytechnique',
    },
    {
      id: 'geo_12',
      topic: '지구과학 & 환경생태',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '약 2억 5,200만 년 전 고생대 말에 발생한 사건으로, 러시아 시베리아 트랩의 대규모 화산 폭발로 인한 온실가스 폭증과 해양 산소 고갈로 해양 생물종의 약 96%, 육상 척추동물의 70%가 절멸하여 "대멸종의 어머니(The Great Dying)"라 불리는 사건은?',
      options: ['페름기 말 대멸종 (Permian-Triassic Extinction)', '백악기-팔레오기(K-Pg) 멸종', '오르도비스기 대멸종', '데본기 말 대멸종'],
      correctIndex: 0,
      explanation: '지구 역사상 확인된 5대 대멸종 중 가장 압도적인 규모로, 막대한 용암과 석탄층 연소로 지구 기온이 10℃ 이상 폭등하고 산성비와 해양 무산소증이 지구 전역을 덮쳤습니다.',
      deepKnowledge: '생태계가 회복하는 데만 무려 1,000만 년 이상이 걸렸으며, 이 멸종의 빈자리를 딛고 중생대 파충류와 공룡의 시대가 개막되었습니다.',
      sourceOrTrivia: 'Burgess, Bowring & Shen (2014) PNAS 111',
    },
    {
      id: 'geo_13',
      topic: '지구과학 & 환경생태',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '물체나 행성의 표면이 입사되는 태양 복사 에너지를 반사하는 비율을 뜻하며, 북극의 백색 빙하가 녹아 짙은 색의 해수가 드러날 때 반사율이 떨어져 지구 온난화가 가속화되는 양의 피드백을 일으키는 지표는?',
      options: ['알베도 (Albedo / 반사율)', '방사율 (Emissivity)', '투과율', '일사량 지수'],
      correctIndex: 0,
      explanation: '신선한 눈과 빙하의 알베도는 약 0.8~0.9(태양열의 80~90% 반사)에 달하지만, 개빙 구역의 해수는 알베도가 0.06에 불과해 태양열의 94%를 그대로 흡수합니다.',
      deepKnowledge: '이 얼음-알베도 피드백(Ice-Albedo Feedback)으로 인해 북극 지역은 지구 평균보다 3~4배 더 빠르게 기온이 상승하는 "북극 증폭(Arctic Amplification)" 현상을 겪고 있습니다.',
      sourceOrTrivia: 'IPCC Sixth Assessment Report (AR6) WG1',
    },
    {
      id: 'geo_14',
      topic: '지구과학 & 환경생태',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '지구 대기 중 수증기(H₂O)와 이산화탄소(CO₂), 메탄(CH₄) 등 온실가스들이 흡수하지 못하여, 지표면의 열복사가 우주 공간으로 직접 빠져나갈 수 있는 파장 약 8~12μm 대역의 적외선 통로를 부르는 용어는?',
      options: ['대기의 창 (Atmospheric Window)', '오존 흡수대', '레일리 산란창', '온실 통로'],
      correctIndex: 0,
      explanation: '지구가 과열되지 않고 복사 평형을 유지할 수 있는 자연의 안전 밸브입니다. 그러나 인류가 배출한 프레온가스(CFCs)나 SF6 등 강력한 인공 온실가스들은 바로 이 대기의 창 파장 대역을 정밀하게 가로막아 온난화를 극대화합니다.',
      deepKnowledge: '이 파장대는 적외선 기상위성이 야간에도 지구 표면과 구름 상부의 온도를 정밀하게 촬영할 수 있는 핵심 적외선 관측 채널로도 활용됩니다.',
      sourceOrTrivia: 'Wallace & Hobbs <Atmospheric Science: An Introductory Survey (2nd Ed)>',
    },
  ],
};
