import type { Question, TopicPreset } from '../types/quiz';
import { EXPANDED_QUESTIONS } from './expandedQuestions';
import { DEEP_BANK_QUESTIONS } from './deepBankQuestions';
import { MEGA_QUESTIONS } from '../data/megaQuestions';
import { ULTRA_QUESTIONS } from '../data/ultraQuestions';

export const TOPIC_PRESETS: TopicPreset[] = [
  {
    id: 'space',
    title: '우주 & 천문학',
    category: '과학',
    iconName: 'Orbit',
    description: '태양계의 기초 상식부터 블랙홀 사건의 지평선과 우주론적 시공간까지',
    sampleQuestionsCount: 125,
    tags: ['블랙홀', '태양계', '상대성이론', '빅뱅', '외계행성'],
    color: 'from-blue-600 to-indigo-800',
  },
  {
    id: 'korean_history',
    title: '한국사 탐구',
    category: '역사',
    iconName: 'Landmark',
    description: '단군신화와 훈민정음부터 대동법의 경제사적 의의와 근현대사의 격동까지',
    sampleQuestionsCount: 125,
    tags: ['조선왕조', '삼국시대', '실학', '근현대사', '문화유산'],
    color: 'from-amber-600 to-red-800',
  },
  {
    id: 'ai_cs',
    title: 'AI & 컴퓨터 과학',
    category: 'IT/기술',
    iconName: 'Cpu',
    description: '인공지능의 기본 원리부터 트랜스포머 어텐션 메커니즘과 P-NP 문제까지',
    sampleQuestionsCount: 125,
    tags: ['딥러닝', 'LLM', '자료구조', '양자컴퓨팅', '알고리즘'],
    color: 'from-violet-600 to-purple-800',
  },
  {
    id: 'physics_quantum',
    title: '물리학 & 양자역학',
    category: '과학',
    iconName: 'Atom',
    description: '뉴턴의 운동법칙부터 양자 얽힘, 벨의 부등식, 엔트로피의 본질까지',
    sampleQuestionsCount: 125,
    tags: ['양자역학', '상대성이론', '열역학', '입자물리', '슈뢰딩거'],
    color: 'from-cyan-600 to-blue-800',
  },
  {
    id: 'philosophy',
    title: '철학 & 사상',
    category: '인문학',
    iconName: 'Compass',
    description: '소크라테스의 문답법부터 칸트의 정언명령, 비트겐슈타인의 언어철학까지',
    sampleQuestionsCount: 125,
    tags: ['서양철학', '동양사상', '인식론', '윤리학', '실존주의'],
    color: 'from-emerald-600 to-teal-800',
  },
  {
    id: 'world_history',
    title: '세계사 & 문명',
    category: '역사',
    iconName: 'Globe',
    description: '메소포타미아 문명부터 베스트팔렌 조약, 냉전의 지정학적 역학까지',
    sampleQuestionsCount: 125,
    tags: ['로마제국', '르네상스', '세계대전', '실크로드', '제국주의'],
    color: 'from-orange-600 to-amber-800',
  },
  {
    id: 'biology_medicine',
    title: '생명과학 & 의학',
    category: '과학',
    iconName: 'Dna',
    description: '광합성과 DNA 이중나선부터 크리스퍼 유전자 가위와 후성유전학까지',
    sampleQuestionsCount: 125,
    tags: ['유전공학', '면역학', '뇌과학', '세포생물학', '진화론'],
    color: 'from-rose-600 to-pink-800',
  },
  {
    id: 'economy',
    title: '경제 & 금융',
    category: '경제/사회',
    iconName: 'TrendingUp',
    description: '수요·공급과 인플레이션부터 내쉬 균형, 양적완화, 블랙-숄즈 모형까지',
    sampleQuestionsCount: 125,
    tags: ['거시경제', '화폐금융', '게임이론', '주식/자산', '행동경제학'],
    color: 'from-emerald-700 to-green-900',
  },
  {
    id: 'art_culture',
    title: '미술 & 문화예술',
    category: '예술',
    iconName: 'Palette',
    description: '모나리자의 스푸마토 기법부터 입체주의, 바우하우스 건축과 현대 개념미술까지',
    sampleQuestionsCount: 125,
    tags: ['르네상스', '인상주의', '현대미술', '건축양식', '미학'],
    color: 'from-fuchsia-600 to-rose-700',
  },
  {
    id: 'psychology_brain',
    title: '심리학 & 인지과학',
    category: '심리학',
    iconName: 'Brain',
    description: '조건반사와 인지부조화부터 시스템 1·2 사고 편향과 뇌의 신경가소성까지',
    sampleQuestionsCount: 125,
    tags: ['인지심리', '행동경제학', '뇌과학', '심리실험', '기억메커니즘'],
    color: 'from-teal-600 to-emerald-800',
  },
  {
    id: 'literature_classics',
    title: '문학 & 세계 고전',
    category: '인문학',
    iconName: 'BookOpen',
    description: '오디세이아와 햄릿부터 카프카의 실존적 변신과 도스토옙스키의 심리, 텍스트 다성성까지',
    sampleQuestionsCount: 125,
    tags: ['고전문학', '세계명작', '셰익스피어', '실존주의', '문학비평'],
    color: 'from-amber-700 to-rose-900',
  },
  {
    id: 'earth_environment',
    title: '지구과학 & 환경생태',
    category: '과학',
    iconName: 'Globe',
    description: '판구조론과 대륙이동설부터 밀란코비치 빙하기 주기와 열염순환, 인류세 가이아 생태계까지',
    sampleQuestionsCount: 125,
    tags: ['판구조론', '기후변화', '가이아이론', '인류세', '해양학'],
    color: 'from-emerald-600 to-sky-800',
  },
];

const BASE_CURATED_QUESTIONS: Record<string, Question[]> = {
  space: [
    {
      id: 'sp_1',
      topic: '우주 & 천문학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '태양계에서 가장 거대한 행성으로, 지구 지름의 약 11배에 달하며 거대한 붉은 점(대적점)을 가진 행성은?',
      options: ['토성', '목성', '해왕성', '천왕성'],
      correctIndex: 1,
      explanation: '목성(Jupiter)은 태양계에서 질량과 부피가 가장 큰 가스 행성으로, 다른 모든 행성을 합친 것보다 2.5배 무겁습니다. 표면의 대적점은 수백 년간 지속된 거대한 고기압성 폭풍입니다.',
      deepKnowledge: '목성의 강력한 중력은 소행성대 및 외곽에서 날아오는 수많은 혜성과 운석을 끌어당겨 내행성인 지구가 파멸적인 충돌을 피할 수 있도록 우주의 방패 역할을 해왔습니다.',
      sourceOrTrivia: 'NASA Solar System Exploration Guide',
    },
    {
      id: 'sp_2',
      topic: '우주 & 천문학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '지구에서 볼 때 달의 항상 같은 면만 보이는 현상의 주요 원인은 무엇일까요?',
      options: [
        '달의 자전 주기와 공전 주기가 약 27.3일로 일치하기 때문',
        '달이 전혀 자전하지 않고 가만히 멈춰 있기 때문',
        '태양빛이 항상 달의 앞면만 정면으로 비추기 때문',
        '지구 대기가 달의 뒷면에서 반사되는 빛을 굴절시켜 차단하기 때문',
      ],
      correctIndex: 0,
      explanation: '달은 지구 주위를 공전하는 주기(약 27.3일)와 스스로 자전하는 주기가 완벽히 일치합니다. 이를 천문학에서 "조석 고정(Tidal Locking)" 현상이라고 부릅니다.',
      deepKnowledge: '지구의 중력이 달에 작용한 기조력(조석력)에 의해 오랜 세월 동안 달의 자전 에너지가 소산되어 최종적으로 공전 주기와 자전 주기가 동기화되었습니다.',
      sourceOrTrivia: '천문학 개론 (조석 마찰과 동주기 자전)',
    },
    {
      id: 'sp_3',
      topic: '우주 & 천문학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '별의 일생에서 태양 정도 질량의 별이 수명을 다했을 때 남기는 고밀도의 작고 뜨거운 잔해 천체는?',
      options: ['중성자별', '블랙홀', '백색왜성', '갈색왜성'],
      correctIndex: 2,
      explanation: '태양 질량의 약 8배 이하인 항성은 헬륨 핵융합이 끝난 뒤 외층을 행성상 성운으로 방출하고 중심부에 탄소와 산소로 이루어진 백색왜성(White Dwarf)을 남깁니다.',
      deepKnowledge: '백색왜성은 더 이상 핵융합을 하지 않으며 "전자 축퇴압(Electron Degeneracy Pressure)"으로 중력 붕괴를 버팁니다. 지구 크기이지만 질량은 태양과 맞먹을 정도로 밀도가 높습니다.',
      sourceOrTrivia: '항성 진화론',
    },
    {
      id: 'sp_4',
      topic: '우주 & 천문학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '우주가 팽창하고 있음을 밝혀낸 허블의 법칙에서 은하의 후퇴 속도(v)와 거리(d)의 관계는?',
      options: [
        '거리에 반비례하여 멀수록 천천히 멀어진다',
        '은하까지의 거리에 정비례하여 멀리 있는 은하일수록 더 빠르게 멀어진다',
        '거리와 관계없이 모든 은하가 빛의 속도의 10%로 일정하게 멀어진다',
        '우주 중심을 기준으로 회전하므로 거리가 멀수록 속도가 0에 수렴한다',
      ],
      correctIndex: 1,
      explanation: '에드윈 허블은 먼 은하들의 적색편이 관측을 통해 은하가 멀어지는 속도가 은하까지의 거리에 정비례(v = H0 × d)한다는 사실을 발표하여 대폭발(빅뱅) 우주론의 결정적 토대를 마련했습니다.',
      deepKnowledge: '이 현상은 은하 자체가 공간 속을 날아가는 것이 아니라, 은하 사이의 "공간 자체"가 팽창하기 때문에 발생합니다. 따라서 매우 먼 은하 사이의 겉보기 후퇴 속도는 광속을 초과할 수도 있습니다.',
      sourceOrTrivia: '허블-르메트르 법칙',
    },
    {
      id: 'sp_5',
      topic: '우주 & 천문학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '백색왜성이 전자 축퇴압으로 버틸 수 있는 최대 질량 한계(약 태양 질량의 1.44배)를 일컫는 명칭은?',
      options: ['찬드라세카르 한계', '오펜하이머-볼코프 한계', '슈바르츠실트 반지름', '로슈 한계'],
      correctIndex: 0,
      explanation: '인도의 천체물리학자 수브라마니안 찬드라세카르가 도출한 한계값(약 1.44 M☉)으로, 이를 초과하면 전자 축퇴압이 중력을 감당하지 못해 중성자별이나 블랙홀로 붕괴하거나 Ia형 초신성 폭발을 일으킵니다.',
      deepKnowledge: '오펜하이머-볼코프 한계는 중성자 축퇴압의 한계(약 2~3 M☉)를 말하며, 슈바르츠실트 반지름은 탈출 속도가 광속이 되는 블랙홀의 사건 지평선 반지름을 의미합니다.',
      sourceOrTrivia: '노벨 물리학상 (1983년 수브라마니안 찬드라세카르)',
    },
    {
      id: 'sp_6',
      topic: '우주 & 천문학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '블랙홀의 사건의 지평선(Event Horizon) 근처에서 양자 요동에 의해 입자-반입자 쌍생성이 일어날 때, 에너지를 잃고 서서히 증발하는 현상을 설명한 이론은?',
      options: ['호킹 복사 (Hawking Radiation)', '펜로즈 과정 (Penrose Process)', '카시미르 효과', '운루 효과 (Unruh Effect)'],
      correctIndex: 0,
      explanation: '스티븐 호킹이 1974년 제안한 이론으로, 양자장론과 일반상대성이론을 접목하여 블랙홀이 완벽히 검은 것이 아니라 흑체 복사를 방출하며 질량을 잃고 궁극적으로 소멸할 수 있음을 증명했습니다.',
      deepKnowledge: '호킹 복사의 온도는 블랙홀의 질량에 반비례합니다. 따라서 질량이 작은 미니 블랙홀일수록 훨씬 높은 온도로 격렬하게 폭발하며 증발하게 됩니다.',
      sourceOrTrivia: 'Nature (1974) "Black hole explosions?"',
    },
    {
      id: 'sp_7',
      topic: '우주 & 천문학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '우주 마이크로파 배경 복사(CMB)에서 발견된 약 10만분의 1 수준의 극미한 온도 요동(온도 비등방성)이 지닌 우주론적 가장 심오한 의미는?',
      options: [
        '현재 우주의 은하, 은하단, 우주 거대구조를 형성한 태초의 양자역학적 밀도 요동의 씨앗이다',
        '우주 중심에 거대한 초대질량 블랙홀이 존재한다는 반박할 수 없는 직접적 증거이다',
        '빛의 속도가 시간에 따라 점진적으로 감속하고 있다는 빛 피로 이론의 입증이다',
        '우주가 3차원이 아니라 11차원 칼라비-야우 다양체임을 증명하는 결정적 데이터이다',
      ],
      correctIndex: 0,
      explanation: '우주 급팽창(인플레이션) 시기에 발생한 양자역학적 미시 요동이 우주 크기로 급격히 확대되었고, 이 극미한 밀도 불균일(1/100,000)이 중력에 의해 응집되어 오늘날의 별, 은하, 거대 구조로 성장했습니다.',
      deepKnowledge: '플랑크 위성 관측 결과, 이 CMB 비등방성 파워 스펙트럼의 정밀 분석을 통해 우주의 연령(138억 년), 평탄성(곡률 Ω ≈ 1), 암흑물질(26.8%)과 암흑에너지(68.3%)의 정확한 구성비가 규명되었습니다.',
      sourceOrTrivia: 'Planck Collaboration 2018 Cosmological Parameters',
    },
    {
      id: 'sp_8',
      topic: '우주 & 천문학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '일반상대성이론에서 회전하는 질량체 주위의 시공간 자체가 마치 소용돌이치듯 휘감기는 현상인 "관성계 끌림(Frame-Dragging)"의 학술 명칭은?',
      options: [
        '렌제-티링 효과 (Lense-Thirring Effect)',
        '마이켈슨-몰리 간섭 효과',
        '폰돌프-바인가르텐 효과',
        '아하로노프-봄 위상 변위',
      ],
      correctIndex: 0,
      explanation: '1918년 요제프 렌제와 한스 티링이 도출한 해로, 회전하는 거대 질량체가 주변의 시공간 직물을 회전 방향으로 끌고 가는 현상입니다. NASA의 Gravity Probe B 위성 실험으로 실측 검증되었습니다.',
      deepKnowledge: '커(Kerr) 블랙홀의 경우 회전으로 인해 사건의 지평선 바깥에 "작용구(Ergosphere)"가 형성되며, 이 영역에서는 시공간 끌림 속도가 광속을 초과하여 어떤 물체도 정지 상태를 유지할 수 없습니다.',
      sourceOrTrivia: 'Physikalische Zeitschrift (1918), Gravity Probe B Results',
    },
  ],

  korean_history: [
    {
      id: 'kh_1',
      topic: '한국사 탐구',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '조선 제4대 국왕으로, 백성을 가르치는 바른 소리라는 뜻의 문자 \'훈민정음\'을 창제한 위인은?',
      options: ['태종 이방원', '세종대왕', '정조', '영조'],
      correctIndex: 1,
      explanation: '세종대왕은 1443년(세종 25년) 훈민정음 28자를 친제(직접 창제)하고, 1446년 반포하여 백성들이 문자를 쉽게 깨우쳐 억울함을 풀고 지식을 나누도록 했습니다.',
      deepKnowledge: '훈민정음 해례본(국보 제70호)의 발견으로 자음이 발음기관의 모양을 본뜨고, 모음이 천·지·인(·, ㅡ, ㅣ) 삼재의 철학적 원리를 바탕으로 설계된 과학적 제자 원리가 명확히 입증되었습니다.',
      sourceOrTrivia: '훈민정음 해례본 정인지 서문',
    },
    {
      id: 'kh_2',
      topic: '한국사 탐구',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '임진왜란 당시 한산도 대첩, 명량 대첩, 노량 대첩 등을 승리로 이끈 조선 수군의 명장은?',
      options: ['권율', '이순신', '김시민', '원균'],
      correctIndex: 1,
      explanation: '충무공 이순신 장군은 거북선과 학익진 전술을 활용해 제해권을 장악함으로써 왜군의 보급로를 차단하고 전쟁의 국면을 결정적으로 뒤집었습니다.',
      deepKnowledge: '특히 명량 대첩에서는 13척의 판옥선으로 133척 이상의 왜선을 격퇴하는 세계 해전사상 유례없는 기적적인 승리를 거두었습니다.',
      sourceOrTrivia: '난중일기 및 징비록',
    },
    {
      id: 'kh_3',
      topic: '한국사 탐구',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '조선 후기 각 지방의 특산물(공물) 대신 토지 결수에 따라 쌀, 베, 돈 등으로 통일 납부하게 한 조세 개혁은?',
      options: ['영정법', '대동법', '호포제', '균역법'],
      correctIndex: 1,
      explanation: '광해군 때 경기도에서 처음 실시된 대동법은 기존 가호(집) 단위로 부과되던 과중한 공납을 토지 면적(결) 기준으로 전환하여 양반 지주의 부담을 늘리고 농민의 부담을 경감시켰습니다.',
      deepKnowledge: '대동법 시행으로 국가가 필요한 물품을 시장에서 조달하는 어용 상인인 \'공인(貢人)\'이 등장하여 조선 후기 상품 화폐 경제 발전의 기폭제가 되었습니다.',
      sourceOrTrivia: '조선왕조실록 광해군일기',
    },
    {
      id: 'kh_4',
      topic: '한국사 탐구',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '신라 진흥왕 시기 영토 확장과 통일의 기반이 되었으며, 세속오계를 행동 규범으로 삼았던 청소년 수양 단체는?',
      options: ['화랑도', '조의선인', '경당', '서당'],
      correctIndex: 0,
      explanation: '화랑도는 원광법사의 세속오계(사군이충, 사친이효, 교우이신, 임전무퇴, 살생유택)를 바탕으로 심신을 연마하고 도의를 닦아 삼국통일의 주역(김유신, 관창 등)을 배출했습니다.',
      deepKnowledge: '화랑도는 초기 여성 지도자인 \'원화(源花)\' 제도에서 출발했으나 남모와 준정의 갈등 사건 이후 미소년을 화랑으로 추대하는 조직으로 개편되었습니다.',
      sourceOrTrivia: '삼국사기 신라본기',
    },
    {
      id: 'kh_5',
      topic: '한국사 탐구',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '고려 11대 문종 시기 9재 학당(문헌공도)을 설립하여 사학 12도의 융성을 이끌고 "해동공자"로 불린 학자는?',
      options: ['최충', '김부식', '이규보', '안향'],
      correctIndex: 0,
      explanation: '최충(崔冲)은 과거에 급제한 인재들을 육성하기 위해 시중을 그만둔 후 9재 학당을 열어 사학 교육의 전성기를 열었습니다. 그 명성으로 해동공자로 칭송받았습니다.',
      deepKnowledge: '사학 12도가 지나치게 번성하자 관학(국자감)이 위축되었고, 이에 고려 정부는 예종 때 국학 7재를 설치하고 양현고를 두는 등 관학 진흥책을 대대적으로 펼쳤습니다.',
      sourceOrTrivia: '고려사 열전 최충전',
    },
    {
      id: 'kh_6',
      topic: '한국사 탐구',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '조선 성종 대 완성된 조선의 기본 법전으로, 이전·호전·예전·병전·형전·공전의 육전 체제로 구성된 법전은?',
      options: ['경국대전', '속대전', '대전회통', '경제육전'],
      correctIndex: 0,
      explanation: '세조 때 최항, 서거정 등에 의해 편찬이 시작되어 예종을 거쳐 성종 16년(1485년) 최종 반포된 통일 법전으로, 조선 통치 체제의 유교적 법적 기반을 완비했습니다.',
      deepKnowledge: '경국대전은 "조종성헌(祖宗成憲)"이라 하여 왕이라 하더라도 함부로 개정할 수 없는 최고 규범의 성격을 가졌으며, 이후 영조 대 <속대전>, 고종 대 <대전회통>으로 보완 계승되었습니다.',
      sourceOrTrivia: '경국대전 서문 및 조선왕조실록 성종실록',
    },
    {
      id: 'kh_7',
      topic: '한국사 탐구',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '조선 현종 시기 서인과 남인 간 치열한 정쟁의 중심이 되었던 "예송(禮訟)" 논쟁의 핵심 본질적 쟁점은?',
      options: [
        '효종이 장자가 아닌 차자로서 왕위에 올랐을 때 자의대비의 복상(상복 입는 기간) 기간을 둘러싼 정통성 문제',
        '청나라와의 국경 획정 시 백두산정계비의 토문강 위치 해석을 둘러싼 영토 문제',
        '훈련도감의 지휘권을 국왕 직속으로 할 것인가 비변사 관할로 할 것인가에 대한 군정 쟁점',
        '환곡의 폐단을 막기 위해 사창제를 민간에 이양할 것인지에 대한 재정 통제권 분쟁',
      ],
      correctIndex: 0,
      explanation: '예송논쟁(기해예송, 갑인예송)은 효종과 인선왕후의 승하 시 인조의 계비인 자의대비의 복제(기년복 vs 3년복 등)를 두고 서인(신권 중시, 천하동례)과 남인(왕권 특수성, 왕자체부)이 왕위 계승 정통성을 걸고 대립한 성리학적 정치 논쟁입니다.',
      deepKnowledge: '단순한 상복 시비가 아니라 왕가를 사대부와 동일한 보편적 예법 아래 둘 것인가(서인/송시열), 군왕의 지위는 일반 사대부와 격이 다른 특수성을 지니는가(남인/허목·윤휴)라는 국가 통치 철학의 격돌이었습니다.',
      sourceOrTrivia: '현종실록 및 연려실기술',
    },
    {
      id: 'kh_8',
      topic: '한국사 탐구',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '신라의 골품제에서 6두품 신분 귀족들이 학문적·정치적 역량에도 불구하고 법적으로 오를 수 있었던 최고 관등은?',
      options: ['아찬 (제6관등)', '이벌찬 (제1관등)', '잡찬 (제3관등)', '대아찬 (제5관등)'],
      correctIndex: 0,
      explanation: '신라 골품제에서 제5관등인 대아찬 이상은 오직 \'진골(眞骨)\' 신분만 오를 수 있었으며, 뛰어난 6두품 관인은 아무리 능력이 출중해도 제6관등인 \'아찬\'까지만 승진할 수 있었습니다.',
      deepKnowledge: '이로 인해 최치원 등 뛰어난 6두품 지식인들은 신라 골품제의 폐쇄성에 좌절하고 당나라 빈공과에 응시하거나 후삼국기 호족 세력과 결탁하여 고려 건국의 사상적 기반을 제공하게 되었습니다.',
      sourceOrTrivia: '삼국사기 직관지 (골품제 승진 상한 규정)',
    },
  ],

  ai_cs: [
    {
      id: 'ai_1',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '인간의 신경망(뉴런과 시냅스) 작동 원리에서 영감을 얻어 고안된 머신러닝의 핵심 기술은?',
      options: ['의사결정나무', '인공신경망 (Artificial Neural Network)', '선형회귀', 'K-평균 군집화'],
      correctIndex: 1,
      explanation: '인공신경망(ANN)은 뇌의 뉴런 연결망을 수학적 노드와 가중치(Weight)로 모방한 모델로, 오늘날 딥러닝과 대규모 언어 모델(LLM)의 핵심 근간입니다.',
      deepKnowledge: '1943년 워런 매컬록과 월터 피츠의 인공 뉴런 수학 모델에서 시작되어 1958년 프랑크 로젠블랫의 퍼셉트론으로 이어졌습니다.',
      sourceOrTrivia: 'A Logical Calculus of the Ideas Immanent in Nervous Activity (1943)',
    },
    {
      id: 'ai_2',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '컴퓨터 알고리즘에서 데이터를 먼저 넣은 것이 먼저 나오는 선입선출(FIFO) 방식의 자료구조는?',
      options: ['스택 (Stack)', '큐 (Queue)', '트리 (Tree)', '그래프 (Graph)'],
      correctIndex: 1,
      explanation: '큐(Queue)는 매표소의 대기 줄처럼 먼저 들어간 원소가 먼저 나오는 FIFO(First-In, First-Out) 구조입니다. 반면 스택은 후입선출(LIFO) 방식입니다.',
      deepKnowledge: '너비 우선 탐색(BFS) 알고리즘이나 운영체제의 프로세스 스케줄링, 인쇄 작업 큐 등에 폭넓게 사용됩니다.',
      sourceOrTrivia: 'Introduction to Algorithms (CLRS)',
    },
    {
      id: 'ai_3',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '2017년 구글 연구진이 논문 "Attention Is All You Need"에서 발표하여 현대 생성형 AI(ChatGPT, Gemini 등)의 표준이 된 아키텍처는?',
      options: ['LSTM', '트랜스포머 (Transformer)', 'CNN (합성곱 신경망)', 'ResNet'],
      correctIndex: 1,
      explanation: '트랜스포머는 기존 순환 신경망(RNN)의 순차 처리 한계를 극복하고, "셀프 어텐션(Self-Attention)" 메커니즘을 통해 문장 내 모든 단어 간의 연관도를 병렬로 계산하는 혁신적인 구조입니다.',
      deepKnowledge: '병렬 학습이 가능해져 엄청난 규모의 GPU 클러스터로 초거대 파라미터 사전학습(Pre-training)을 할 수 있게 되었습니다.',
      sourceOrTrivia: 'Vaswani et al. (2017) "Attention Is All You Need"',
    },
    {
      id: 'ai_4',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '웹 브라우저에서 JavaScript 엔진이 단일 스레드(Single Thread)임에도 비동기 I/O를 원활하게 처리할 수 있게 해주는 핵심 메커니즘은?',
      options: ['가비지 컬렉터', '이벤트 루프 (Event Loop)', 'JIT 컴파일러', '웹 워커 풀'],
      correctIndex: 1,
      explanation: 'JavaScript는 싱글 스레드 언어이지만, 호출 스택(Call Stack), 백그라운드 Web API, 태스크 큐(Task Queue/Microtask Queue)와 이를 순환 감시하는 "이벤트 루프"를 통해 논블로킹(Non-blocking) 비동기 처리를 수행합니다.',
      deepKnowledge: '마이크로태스크 큐(Promise.then, MutationObserver)는 일반 매크로태스크 큐(setTimeout, setInterval)보다 우선순위가 높아 호출 스택이 비면 항상 먼저 비워집니다.',
      sourceOrTrivia: 'MDN Web Docs JavaScript 동시성 모델과 이벤트 루프',
    },
    {
      id: 'ai_5',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '신경망의 깊이가 깊어질수록 역전파(Backpropagation) 과정에서 기울기(Gradient)가 0에 수렴하여 앞쪽 층이 학습되지 않는 현상은?',
      options: [
        '기울기 소실 문제 (Vanishing Gradient Problem)',
        '과적합 (Overfitting)',
        '공변량 변화 (Covariate Shift)',
        '차원의 저주 (Curse of Dimensionality)',
      ],
      correctIndex: 0,
      explanation: '시그모이드(Sigmoid) 등의 활성화 함수는 미분값 최댓값이 0.25에 불과하여 연쇄 법칙에 의해 층을 거칠수록 미분값이 기하급수적으로 작아집니다. 이를 극복하기 위해 ReLU 함수와 잔차 연결(Residual Connection) 등이 도입되었습니다.',
      deepKnowledge: '허카이밍(Kaiming He) 등이 제안한 ResNet(2015)은 원래 입력값을 다음 층에 그대로 건네주는 잔차 연결(스킵 커넥션, Skip Connection)을 도입하여 기울기가 손실 없이 직접 이전 층으로 전달되도록 함으로써 수백 층의 깊은 망 학습을 가능케 했습니다.',
      sourceOrTrivia: 'Deep Residual Learning for Image Recognition (2015)',
    },
    {
      id: 'ai_6',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '계산 복잡도 이론에서 "다항 시간 내에 정답인지 검증 가능한 문제들의 집합"을 의미하는 복잡도 클래스는?',
      options: ['P', 'NP', 'NP-Complete', 'EXPTIME'],
      correctIndex: 1,
      explanation: 'NP(Nondeterministic Polynomial time)는 비결정론적 튜링 기계가 다항 시간에 풀 수 있거나, 주어진 해가 정답인지 결정론적 기계로 다항 시간 안에 "검증(Verify)"할 수 있는 문제 집합을 뜻합니다.',
      deepKnowledge: 'P = NP 문제는 밀레니엄 7대 난제 중 하나로, "쉽게 검증할 수 있는 모든 문제는 쉽게 풀 수도 있는가?"라는 이론 컴퓨터 과학 최고의 궁극적 질문입니다.',
      sourceOrTrivia: 'Cook (1971) "The Complexity of Theorem Proving Procedures"',
    },
    {
      id: 'ai_7',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '대규모 언어 모델(LLM)의 트랜스포머 디코더에서 어텐션을 계산할 때, 시간 복잡도가 시퀀스 길이 N에 대해 O(N²)으로 증가하는 근본적인 이유는?',
      options: [
        '모든 토큰 쿼리(Query)가 시퀀스 내의 모든 토큰 키(Key)와 쌍(Pairwise)으로 내적 연산을 수행해야 하기 때문',
        '토큰마다 역전파 가중치를 별도의 독립된 스레드로 물리적 복사하기 때문',
        '피드포워드 신경망 층의 활성화 맵 크기가 토큰 수의 제곱으로 비선형 변환되기 때문',
        '포지셔널 인코딩의 삼각함수 주기가 단어 길이에 비례해 이차원 푸리에 급수를 필요로 하기 때문',
      ],
      correctIndex: 0,
      explanation: 'Softmax(QKᵀ / √d_k)V 연산에서 Q(N×d)와 K(N×d)의 전치 행렬을 곱하면 크기가 N×N인 어텐션 가중치 행렬이 생성되므로, 토큰 길이 N이 늘어날 때 계산량과 메모리가 N²에 비례하여 급증합니다.',
      deepKnowledge: '이를 해결하기 위해 FlashAttention(SRAM 타일링 메모리 최적화), Ring Attention, 또는 선형 복잡도를 갖는 상태 공간 모델(Mamba, RWKV) 등이 활발히 연구되고 있습니다.',
      sourceOrTrivia: 'Dao et al. (2022) "FlashAttention: Fast and Memory-Efficient Exact Attention"',
    },
    {
      id: 'ai_8',
      topic: 'AI & 컴퓨터 과학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '분산 컴퓨팅의 CAP 정리(Brewer\'s Conjecture)에서 네트워크 분할(Partition tolerance)이 발생했을 때 시스템이 동시에 양립할 수 없는 두 가지 속성은?',
      options: [
        '일관성 (Consistency)과 가용성 (Availability)',
        '기밀성 (Confidentiality)과 무결성 (Integrity)',
        '원자성 (Atomicity)과 지속성 (Durability)',
        '선형성 (Linearity)과 확장성 (Scalability)',
      ],
      correctIndex: 0,
      explanation: '분산 네트워크에서 노드 간 통신 장애(P)가 일어날 때, 모든 노드가 항상 동일한 최신 데이터를 반환하는 일관성(C)을 유지하려면 일부 노드의 응답을 거부해야 하고, 모든 요청에 즉각 응답하는 가용성(A)을 보장하려면 과거 데이터를 줄 수밖에 없어 둘을 동시에 만족할 수 없습니다.',
      deepKnowledge: '이에 따라 분산 DB는 CP 계열(HBase, MongoDB, 분산 잠금)과 AP 계열(Cassandra, DynamoDB, 최종 일관성 지원)로 설계 철학이 분기됩니다.',
      sourceOrTrivia: 'Eric Brewer (2000), Seth Gilbert & Nancy Lynch (2002 Formal Proof)',
    },
  ],

  physics_quantum: [
    {
      id: 'phy_1',
      topic: '물리학 & 양자역학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '뉴턴의 운동 제2법칙을 나타내는 가장 유명한 물리 방정식은?',
      options: ['E = mc²', 'F = ma', 'v = d / t', 'PV = nRT'],
      correctIndex: 1,
      explanation: '물체에 가해진 알짜힘(F)은 물체의 질량(m)과 가속도(a)의 곱과 같다는 뉴턴의 제2법칙(힘과 가속도의 법칙)을 나타냅니다.',
      deepKnowledge: '엄밀한 미분 형식으로는 힘이 시간에 따른 운동량의 변화율 F = dp/dt 로 정의되며, 질량이 일정한 경우 F = m(dv/dt) = ma 로 환원됩니다.',
      sourceOrTrivia: '아이작 뉴턴의 <자연철학의 수학적 원리 (프린키피아)> (1687)',
    },
    {
      id: 'phy_2',
      topic: '물리학 & 양자역학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '빛이 파동의 성질뿐만 아니라 불연속적인 에너지 덩어리(알갱이)인 입자의 성질도 지닌다는 빛의 이중성을 증명한 현상은?',
      options: ['광전 효과 (Photoelectric Effect)', '도플러 효과', '빛의 굴절', '전반사'],
      correctIndex: 0,
      explanation: '금속 표면에 특정 진동수 이상의 빛을 비추었을 때 전자가 튀어나오는 현상으로, 아인슈타인은 빛이 광양자(Photon)라는 입자로 충돌한다는 광양자설로 이를 설명하여 1921년 노벨 물리학상을 수상했습니다.',
      deepKnowledge: '빛의 밝기(진폭)를 아무리 높여도 문턱 진동수 이하의 빛은 전자를 단 하나도 튕겨내지 못한다는 점이 파동론으로 설명할 수 없었던 핵심 미스터리였습니다.',
      sourceOrTrivia: 'Einstein (1905) "Concerning an Heuristic Point of View toward the Emission and Transformation of Light"',
    },
    {
      id: 'phy_3',
      topic: '물리학 & 양자역학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '양자역학에서 입자의 위치(x)와 운동량(p)을 동시에 완벽하게 정밀 측정할 수 없다는 원리는?',
      options: ['파울리 배타 원리', '하이젠베르크 불확정성 원리', '에너지 보존 법칙', '앙페르 법칙'],
      correctIndex: 1,
      explanation: '베르너 하이젠베르크가 도출한 원리로, 위치의 불확정성(Δx)과 운동량의 불확정성(Δp)의 곱은 결코 ħ/2(디랙 상수 나누기 2)보다 작아질 수 없습니다.',
      deepKnowledge: '이는 측정 기계의 기술적 한계가 아니라 입자의 파동함수가 지닌 근본적인 수학적 푸리에 변환 상의 물리적 성질입니다.',
      sourceOrTrivia: 'Heisenberg (1927) "Über den anschaulichen Inhalt der quantentheoretischen Kinematik und Mechanik"',
    },
    {
      id: 'phy_4',
      topic: '물리학 & 양자역학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '고립계에서 시간이 흐름에 따라 무질서도(엔트로피)는 결코 감소하지 않고 항상 증가한다는 법칙은?',
      options: ['열역학 제0법칙', '열역학 제1법칙', '열역학 제2법칙', '열역학 제3법칙'],
      correctIndex: 2,
      explanation: '열역학 제2법칙에 따르면 자발적인 변화는 항상 계의 전체 엔트로피가 증가하거나 일정하게 유지되는 방향으로만 진행되며, 이는 비가역적 시간의 화살을 정의합니다.',
      deepKnowledge: '통계역학적으로 엔트로피 S = k ln W (볼츠만 공식)로 정의되며, 이는 계가 가질 수 있는 미시 상태 수 W가 가장 많은 거시 상태로 통계적으로 수렴함을 의미합니다.',
      sourceOrTrivia: '클라우지우스 & 루드비히 볼츠만의 통계역학',
    },
    {
      id: 'phy_5',
      topic: '물리학 & 양자역학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '동일한 페르미온(전자, 양성자 등) 입자 둘은 동일한 양자 상태(모든 양자수가 같은 상태)를 동시에 가질 수 없다는 원리는?',
      options: ['파울리 배타 원리', '훈트의 규칙', '보어의 상보성 원리', '드브로이 물질파 이론'],
      correctIndex: 0,
      explanation: '볼프강 파울리가 1925년 제안한 원리로, 반정수 스핀을 갖는 페르미온들은 원자 내에서 같은 양자수 조합(n, l, m, s)을 공유할 수 없습니다. 이로 인해 전자 껍질 구조와 원소의 주기율표, 화학 결합이 성립합니다.',
      deepKnowledge: '만약 파울리 배타 원리가 없다면 모든 전자가 최저 에너지 준위로 붕괴하여 단단한 물질 구조나 생명체가 존재할 수 없게 됩니다.',
      sourceOrTrivia: 'Pauli (1925) Exclusion Principle',
    },
    {
      id: 'phy_6',
      topic: '물리학 & 양자역학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '아인슈타인이 "유령 같은 원격 작용"이라 비판했던 현상으로, 두 입자가 거리에 무관하게 즉각적으로 얽혀 한쪽의 상태 측정이 다른 쪽의 상태를 즉시 결정짓는 현상은?',
      options: ['양자 얽힘 (Quantum Entanglement)', '양자 터널링', '제이만 효과', '초전도 현상'],
      correctIndex: 0,
      explanation: '양자 얽힘 상태에 있는 두 입자는 아무리 멀리 떨어져 있어도 하나의 결합된 파동함수로 기술되며, 한쪽 입자의 스핀을 관측하는 순간 다른 쪽 입자의 스핀 상태가 확률 파동 붕괴에 의해 즉시 결정됩니다.',
      deepKnowledge: '아인슈타인, 포돌스키, 로젠(EPR)은 이것이 상대성이론의 국소성에 위배된다며 양자론이 불완전하다고 주장했으나, 훗날 벨의 부등식 실험 검증으로 양자역학의 비국소성이 증명되었습니다.',
      sourceOrTrivia: 'EPR Paradox (1935), Alain Aspect et al. (1982 Test of Bell\'s Inequality)',
    },
    {
      id: 'phy_7',
      topic: '물리학 & 양자역학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '국소적 숨은 변수 이론(Local Hidden Variable Theory)이 양자역학의 통계적 예측과 양립할 수 없음을 수학적 부등식으로 증명하여 노벨 물리학상(2022)으로 이어진 정리는?',
      options: ['벨의 부등식 (Bell\'s Theorem / Bell Inequality)', '괴델의 불완전성 정리', '뇌터의 정리', '콜모고로프 공리계'],
      correctIndex: 0,
      explanation: '존 스튜어트 벨이 1964년 도출한 정리로, "어떤 정보도 빛보다 빠르게 전달되지 않으며 물리량이 관측 전에도 실재한다"는 국소 실재론이 참이라면 상관관계가 일정한 한계값을 넘을 수 없음을 보였습니다. 실험 결과 자연은 벨의 부등식을 위배함이 확인되었습니다.',
      deepKnowledge: '2022년 알랭 아스페, 존 클라우저, 안톤 차일링거는 루프홀(Loophole) 없는 벨 부등식 실험으로 노벨 물리학상을 수상하며 양자정보 과학과 양자 컴퓨터의 기초를 확립했습니다.',
      sourceOrTrivia: 'Physics Physique Fizika 1 (1964) "On the Einstein Podolsky Rosen Paradox"',
    },
    {
      id: 'phy_8',
      topic: '물리학 & 양자역학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '연속적인 대칭성이 존재할 때 그에 대응하는 보존 법칙이 반드시 존재함을 증명하여 현대 이론물리학의 기둥이 된 정리는?',
      options: ['뇌터의 정리 (Noether\'s Theorem)', '가우스 발산 정리', '그린의 정리', '위그너-에카르트 정리'],
      correctIndex: 0,
      explanation: '에미 뇌터(Emmy Noether)가 1915년 증명한 정리입니다. 시간 병진 대칭성은 에너지 보존 법칙, 공간 병진 대칭성은 운동량 보존 법칙, 공간 회전 대칭성은 각운동량 보존 법칙을 낳습니다.',
      deepKnowledge: '게이지 대칭성(U(1), SU(2), SU(3))은 전자기력, 약력, 강력의 게이지 보손과 전하 보존을 도출하는 입자물리학 표준모형의 절대적 기초 설계 원리입니다.',
      sourceOrTrivia: 'Noether (1918) "Invariante Variationsprobleme"',
    },
  ],

  philosophy: [
    {
      id: 'phil_1',
      topic: '철학 & 사상',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '자신의 무지를 자각하는 것이 지혜의 시작이라 보며, 끊임없는 문답법(산파술)을 통해 청년들과 대화했던 고대 그리스 철학자는?',
      options: ['소크라테스', '아리스토텔레스', '에피쿠로스', '탈레스'],
      correctIndex: 0,
      explanation: '소크라테스는 "너 자신을 알라"는 델포이 신전의 신탁을 재해석하며, 자신이 아무것도 모른다는 사실을 안다는 무지의 지(知)를 바탕으로 대화를 통해 진리를 도출하는 산파술을 펼쳤습니다.',
      deepKnowledge: '그는 어떤 글도 직접 남기지 않았으며, 그의 사상과 죽음(독배)은 제자인 플라톤의 대화편(변명, 크리톤, 파이돈 등)을 통해 오늘날까지 전해지고 있습니다.',
      sourceOrTrivia: '플라톤의 <변명 (Apology)>',
    },
    {
      id: 'phil_2',
      topic: '철학 & 사상',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '"나는 생각한다, 고로 존재한다(Cogito, ergo sum)"라는 명제로 근대 합리론의 문을 연 철학자는?',
      options: ['르네 데카르트', '존 로크', '데이비드 흄', '바루흐 스피노자'],
      correctIndex: 0,
      explanation: '데카르트는 모든 감각과 인식을 철저히 의심하는 방법적 회의 끝에, "의심하고 있는 나 자신의 사유 행위만큼은 결코 의심할 수 없는 제1의 확실한 진리"임을 발견했습니다.',
      deepKnowledge: '이를 바탕으로 데카르트는 생각하는 실체인 정신(res cogitans)과 공간을 점유하는 물질(res extensa)을 분리하는 심신이원론을 체계화했습니다.',
      sourceOrTrivia: '데카르트의 <방법서설 (1637)>',
    },
    {
      id: 'phil_3',
      topic: '철학 & 사상',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '"최대 다수의 최대 행복"을 도덕과 입법의 기본 원리로 삼은 벤담과 밀의 윤리 사상은?',
      options: ['공리주의 (Utilitarianism)', '의무론', '덕 윤리학', '실존주의'],
      correctIndex: 0,
      explanation: '제레미 벤담이 체계화한 고전적 공리주의는 행위의 도덕적 가치를 그 행위가 산출하는 쾌락과 고통의 결과(유용성)로 측정하는 결과주의 윤리학입니다.',
      deepKnowledge: '존 스튜어트 밀은 벤담의 양적 공리주의를 보완하여 "만족한 돼지보다 불만족한 소크라테스가 낫다"며 질적 공리주의를 제창했습니다.',
      sourceOrTrivia: '밀의 <공리주의 (1861)>',
    },
    {
      id: 'phil_4',
      topic: '철학 & 사상',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '모든 부품을 하나씩 교체하다가 마침내 원래 부품이 하나도 남지 않은 배는 여전히 같은 배인가를 묻는 동일성의 역설은?',
      options: ['테세우스의 배 (Ship of Theseus)', '아킬레우스와 거북이', '제논의 역설', '통 속의 뇌'],
      correctIndex: 0,
      explanation: '플루타르코스가 전한 고대 그리스의 역설로, 사물의 본질과 동일성(Identity)이 그것을 구성하는 물질적 재료에 있는지, 아니면 구조나 연속적인 역사적 형태에 있는지를 질문합니다.',
      deepKnowledge: '인체의 세포 역시 수년 주기로 거의 전부 교체되므로, "10년 전의 나와 지금의 나는 물질적으로 다른데 어떻게 동일인이라 할 수 있는가?"라는 인격 동일성 문제로 직결됩니다.',
      sourceOrTrivia: '플루타르코스 영웅전',
    },
    {
      id: 'phil_5',
      topic: '철학 & 사상',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '임마누엘 칸트의 도덕 철학에서 조건이나 결과에 구애받지 않고 무조건적으로 따라야 하는 절대적 도덕 명령을 가리키는 개념은?',
      options: ['정언명령 (Categorical Imperative)', '가언명령', '공리율', '자연법칙'],
      correctIndex: 0,
      explanation: '"네 의지의 준칙이 언제나 동시에 보편적 입법의 원리가 될 수 있도록 행위하라"는 칸트의 정언명령은 수단으로서가 아닌 목적 그 자체로서 인간을 대할 것을 요구하는 의무론적 윤리학의 핵심입니다.',
      deepKnowledge: '칸트는 <실천이성비판>에서 거짓말이 가져올 유익한 결과가 있더라도, 거짓말이라는 준칙 자체가 보편화되면 신뢰와 언약의 개념 자체가 파괴되므로 무조건적인 도덕적 악이라고 논증했습니다.',
      sourceOrTrivia: '칸트의 <윤리형이상학 정초 (1785)>',
    },
    {
      id: 'phil_6',
      topic: '철학 & 사상',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '장 폴 사르트르의 실존주의 선언에서 인간은 정해진 본질을 갖고 태어나는 사물과 달리 자유로운 선택으로 스스로를 규정한다는 명제는?',
      options: [
        '실존은 본질에 앞선다 (L\'existence précède l\'essence)',
        '신은 죽었다',
        '인간은 생각하는 갈대이다',
        '만물은 유전한다',
      ],
      correctIndex: 0,
      explanation: '페이퍼 나이프 같은 도구는 만들기 전에 용도(본질)가 먼저 정해지지만, 인간은 먼저 세상에 던져져 존재(실존)한 뒤 스스로의 결단과 행동을 통해 자신의 정체성과 가치(본질)를 만들어간다는 실존주의의 핵심 모토입니다.',
      deepKnowledge: '따라서 인간은 자유라는 형벌에 처해졌으며, 자신의 모든 선택에 대해 온전한 책임을 져야 하는 실존적 불안과 직면하게 됩니다.',
      sourceOrTrivia: '사르트르 강연록 <실존주의는 휴머니즘이다 (1945)>',
    },
    {
      id: 'phil_7',
      topic: '철학 & 사상',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '루트비히 비트겐슈타인이 <논리철학 논고>의 마지막 명제 7번에서 남긴 철학사에서 가장 유명한 경구는?',
      options: [
        '말할 수 없는 것에 대해서는 침묵해야 한다 (Wovon man nicht sprechen kann, darüber muss man schweigen)',
        '언어의 한계는 내 세계의 한계를 의미하지 않는다',
        '존재하는 것은 지각되는 것이다',
        '신은 주사위 놀이를 하지 않는다',
      ],
      correctIndex: 0,
      explanation: '비트겐슈타인은 사실을 기술할 수 있는 자연과학적 명제만이 유의미한 언어이며, 윤리학, 미학, 형이상학 등 삶의 궁극적 가치들은 언어로 논리적으로 말해질 수 없고 오직 "보여질(Zeigen)" 뿐이므로 침묵해야 한다고 선언했습니다.',
      deepKnowledge: '후기 비트겐슈타인은 <철학적 탐구>에서 이러한 논리적 언어 그림 이론을 스스로 비판하고, 언어의 의미는 논리적 대응이 아니라 삶의 양식 속에서 쓰이는 "언어 게임(Language-game)"의 사용 방식에 있다고 전환했습니다.',
      sourceOrTrivia: '비트겐슈타인의 <논리철학 논고 (Tractatus Logico-Philosophicus, 1921)>',
    },
    {
      id: 'phil_8',
      topic: '철학 & 사상',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '에드문트 후설의 현상학에서 외부 대상의 실재 여부에 대한 기존의 모든 선입견과 판단을 잠정 중지하고 의식에 나타난 순수 현상만을 직시하는 방법론은?',
      options: ['에포케 (판단중지 / Epoché)', '해체주의 (Deconstruction)', '해석학적 순환', '변증법적 지양 (Aufheben)'],
      correctIndex: 0,
      explanation: '후설은 자연주의적 독단론을 벗어나 인식의 궁극적 확실성에 도달하기 위해, 세상에 대한 기존 판단을 괄호 치기(Einklammerung)하여 멈추는 \'에포케\'를 통해 순수 지향적 의식 세계로 환원해야 한다고 주장했습니다.',
      deepKnowledge: '이는 하이데거의 존재론, 메를로퐁티의 신체 현상학, 사르트르의 실존주의로 이어지며 20세기 유럽 대륙철학의 지형을 근본적으로 바꾸어 놓았습니다.',
      sourceOrTrivia: '후설의 <순수현상학과 현상학적 철학의 이념들 (1913)>',
    },
  ],

  world_history: [
    {
      id: 'wh_1',
      topic: '세계사 & 문명',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '고대 로마 제국에서 검투사 경기와 맹수 사냥, 대중 연극 등이 열렸던 5만 명 규모의 거대한 타원형 원형 경기장은?',
      options: ['콜로세움 (Colosseum)', '판테온', '파르테논 신전', '포룸 로마눔'],
      correctIndex: 0,
      explanation: '서기 80년 티투스 황제 시기 완공된 플라비우스 원형 경기장으로 훗날 "콜로세움"으로 불리게 되었으며, 고대 로마의 건축 공학과 오락 문화를 상징합니다.',
      deepKnowledge: '외벽 아치 기둥은 1층 도리아식, 2층 이오니아식, 3층 코린트식 양식을 층별로 다르게 배치한 정교한 구조미를 보여주며, 지하에는 검투사와 맹수를 올리는 승강기 장치가 갖춰져 있었습니다.',
      sourceOrTrivia: '로마 고고학 및 로마사 연구',
    },
    {
      id: 'wh_2',
      topic: '세계사 & 문명',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '18세기 후반 영국에서 증기기관의 개량과 면직물 공업의 기계화를 시작으로 인류의 생산 방식을 근본적으로 바꾼 역사적 사건은?',
      options: ['산업 혁명 (Industrial Revolution)', '프랑스 대혁명', '종교 개혁', '르네상스'],
      correctIndex: 0,
      explanation: '제임스 와트의 증기기관 개량 등을 필두로 가내 수공업에서 공장제 기계 공업으로 전환되면서 도시화와 자본주의 경제 체제가 급속히 형성되었습니다.',
      deepKnowledge: '영국에서 산업혁명이 가장 먼저 촉발된 요인으로는 풍부한 석탄 자원, 사유재산권을 보호하는 명예혁명 이후의 정치적 안정, 광대한 식민지 시장과 자본 축적이 꼽힙니다.',
      sourceOrTrivia: 'Eric Hobsbawm의 <혁명의 시대>',
    },
    {
      id: 'wh_3',
      topic: '세계사 & 문명',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1215년 영국의 존 왕이 귀족들의 요구에 굴복하여 서명한 문서로, 국왕의 권력을 법 아래 제한하여 근대 입헌주의의 효시가 된 문서는?',
      options: ['마그나 카르타 (대헌장 / Magna Carta)', '권리장전', '인간과 시민의 권리선언', '독립선언서'],
      correctIndex: 0,
      explanation: '영국 국왕이라 할지라도 법 위에 군림할 수 없으며 귀족들의 동의 없이 부당한 과세를 할 수 없고, 적법한 재판 없이는 시민을 체포·구금할 수 없음을 천명했습니다.',
      deepKnowledge: '이후 1689년 영국의 권리장전, 1787년 미국 헌법의 적법절차(Due Process of Law) 원리로 계승 발전되었습니다.',
      sourceOrTrivia: '영국 헌정사 자료 (British Library Magna Carta Collection)',
    },
    {
      id: 'wh_4',
      topic: '세계사 & 문명',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1648년 유럽의 30년 종교 전쟁을 종결짓고, 근대적 주권 국가 체제와 외교의 기본 틀을 확립한 평화 조약은?',
      options: ['베스트팔렌 조약 (Peace of Westphalia)', '베르사유 조약', '위트레흐트 조약', '빈 의정서'],
      correctIndex: 0,
      explanation: '가톨릭과 개신교(루터파, 칼뱅파) 간의 참혹한 종교전쟁을 끝내며, 제후 국가들의 독자적 외교권과 주권을 승인함으로써 "국가 주권" 중심의 근대 국제 질서의 기원이 되었습니다.',
      deepKnowledge: '이 조약으로 교황과 신성로마제국 황제의 초국가적 보편 권력이 와해되고, 개별 국민국가(Nation-state)가 국제정치의 기본 단위가 되는 \'베스트팔렌 체제\'가 탄생했습니다.',
      sourceOrTrivia: 'Henry Kissinger의 <외교 (Diplomacy)>',
    },
    {
      id: 'wh_5',
      topic: '세계사 & 문명',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '고대 그리스 역사가 투키디데스가 스파르타와 아테네의 전쟁을 기록하며 도출한 통찰로, 신흥 강대국이 부상할 때 기존 패권국이 느끼는 두려움이 결국 전쟁으로 이어진다는 개념은?',
      options: [
        '투키디데스의 함정 (Thucydides\'s Trap)',
        '도미노 이론',
        '먼로 독트린',
        '린치핀 이론',
      ],
      correctIndex: 0,
      explanation: '투키디데스는 <펠로폰네소스 전쟁사>에서 "전쟁을 불가피하게 만든 것은 아테네의 성장에 따른 스파르타의 두려움이었다"고 썼으며, 현대 국제정치학에서 패권 전이 시기의 충돌을 분석할 때 인용됩니다.',
      deepKnowledge: '하버드대 그레이엄 앨리슨 교수는 지난 500년간 부상국과 지배국 간의 16차례 권력 교체기 중 12차례가 대규모 전쟁으로 이어졌음을 통계적으로 분석했습니다.',
      sourceOrTrivia: 'Graham Allison의 <예정된 전쟁 (Destined for War)>',
    },
    {
      id: 'wh_6',
      topic: '세계사 & 문명',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '13세기 몽골 제국이 유라시아 대륙 전역을 장악하면서 무역로를 보호하고 20~30마일마다 설치하여 신속한 통신을 가능케 한 역참 제도의 명칭은?',
      options: ['얌 (Jam / Örtöö)', '카라반사라이', '포스탈 코트', '비단길 관문'],
      correctIndex: 0,
      explanation: '몽골 제국의 역참 제도인 \'얌\'은 공무를 수행하는 전령에게 패자(Paiza)를 지급하여 말과 숙식을 제공받게 함으로써, 베이징에서 동유럽까지 수천 킬로미터의 명령 전달을 수주일 내에 완수하게 했습니다.',
      deepKnowledge: '이 역참망을 통해 동서양 간의 화약, 나침반, 인쇄술 등 기술과 문화가 폭발적으로 전파되는 \'팍스 몽골리카(Pax Mongolica)\'의 혈관 역할을 담당했습니다.',
      sourceOrTrivia: '라시드 앗딘의 <집사 (Jami al-Tawarikh)>',
    },
    {
      id: 'wh_7',
      topic: '세계사 & 문명',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '1971년 8월 미국 닉슨 대통령이 일방적으로 선언한 "닉슨 쇼크(Nixon Shock)"의 통화 금융사적 핵심 조치는?',
      options: [
        '미국 달러의 금 태환(금 1온스당 35달러 교환 보장) 전격 정지 및 변동환율제 전환 촉발',
        '국제통화기금(IMF)과 세계은행(World Bank)의 동시 해산 결정',
        '원유 결제 대금을 금화로만 강제하는 페트로골드 결제 시스템 선포',
        '유럽 경제공동체(EEC)와의 모든 금융 거래 및 관세 자유화 협정 파기',
      ],
      correctIndex: 0,
      explanation: '베트남 전쟁 등으로 재정 적자가 심화되고 해외 달러 유출이 늘어나자 미국은 보유 금 부족으로 금 교환을 감당할 수 없게 되었고, 금 태환을 공식 중단하면서 인류 통화사는 법정불환지폐(Fiat Money) 시대로 진입했습니다.',
      deepKnowledge: '이 조치로 제2차 세계대전 이후 세계 금융의 기둥이었던 브레턴우즈 고정환율 체제가 공식 붕괴되었으며, 이후 사우디와의 협정을 통한 \'페트로달러\' 체제로 달러 패권이 재편되었습니다.',
      sourceOrTrivia: 'The Federal Reserve History (Nixon Ends Convertibility of US Dollars to Gold)',
    },
    {
      id: 'wh_8',
      topic: '세계사 & 문명',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '고대 바빌로니아 함무라비 법전의 핵심 원리인 동해보복형(Lex Talionis, "눈에는 눈, 이에는 이")에 내포된 실제 고대 법철학적 목적과 성격은?',
      options: [
        '무제한적이고 자의적인 사적 혈투와 과도한 보복을 제한하되, 피해자의 신분(귀족/평민/노예)에 따라 차등 적용되는 법치주의적 한계 설정',
        '모든 시민의 법 앞의 절대적 평등을 신분제 폐지와 함께 선언한 근대 민주주의의 최초 성문화',
        '국가의 개입 없이 피해 당사자 가족이 직접 가해자를 처형할 수 있도록 인정한 순수 사적 구제 인정',
        '모든 범죄를 화폐적 배상금으로만 해결하도록 강제한 순수 상업법적 규정',
      ],
      correctIndex: 0,
      explanation: '동해보복의 본질은 "눈을 다쳤다고 목숨을 빼앗는 식의 과도한 사적 복수를 금지하고, 입은 피해 이상의 징벌을 금지"하는 일종의 처벌 상한선 규정이었습니다. 다만 피해자와 가해자의 신분 계급에 따라 배상 기준이 엄격히 차등화되었습니다.',
      deepKnowledge: '루브르 박물관에 소장된 2.25미터의 현무암 비석 상단에는 함무라비 왕이 정의의 신 샤마슈(Shamash)로부터 법전을 수여받는 부조가 새겨져 있어 왕권신수설적 정당성을 부여하고 있습니다.',
      sourceOrTrivia: '함무라비 법전 비문 판독문 (Louvre Museum)',
    },
  ],

  biology_medicine: [
    {
      id: 'bio_1',
      topic: '생명과학 & 의학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '식물이 빛 에너지를 이용하여 이산화탄소와 물로부터 포도당을 합성하고 대기 중으로 방출하는 기체는?',
      options: ['산소 (O₂)', '질소', '메탄', '일산화탄소'],
      correctIndex: 0,
      explanation: '식물의 엽록체에서 일어나는 광합성 과정 중 명반응에서 물(H₂O)이 광분해되면서 부산물로 산소 분자가 생성되어 방출됩니다.',
      deepKnowledge: '약 24억 년 전 시아노박테리아(남세균)의 광합성으로 인해 발생한 대산화 사건(Great Oxidation Event)은 지구 대기에 산소를 급증시켜 호흡 생명체의 폭발적 진화를 가능케 했습니다.',
      sourceOrTrivia: '캠벨 생명과학 (Campbell Biology)',
    },
    {
      id: 'bio_2',
      topic: '생명과학 & 의학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '모든 생명체의 유전 정보를 저장하고 있으며, 아데닌(A), 티민(T), 구아닌(G), 시토신(C) 4가지 염기의 이중나선 구조를 가진 분자는?',
      options: ['DNA (디옥시리보핵산)', 'ATP', '글리코겐', '콜레스테롤'],
      correctIndex: 0,
      explanation: '1953년 제임스 왓슨과 프랜시스 크릭이 밝혀낸 DNA 이중나선 구조는 유전 암호를 복제하고 단백질 합성을 지령하는 생명의 설계도입니다.',
      deepKnowledge: '염기 간 상보적 수소결합(A-T는 2개, G-C는 3개의 수소결합)의 특성 덕분에 DNA는 세포 분열 시 정확하고 안정적으로 복제될 수 있습니다.',
      sourceOrTrivia: 'Watson & Crick (1953) "Molecular Structure of Nucleic Acids"',
    },
    {
      id: 'bio_3',
      topic: '생명과학 & 의학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '인간의 적응 면역계에서 특정 항원에 결합하여 무력화하는 "항체(Immunoglobulin)"를 전문적으로 대량 생산·분비하는 면역 세포는?',
      options: ['형질세포 (Plasma cell, 분화된 B세포)', '대식세포', '적혈구', '호중구'],
      correctIndex: 0,
      explanation: '항원을 인식하고 활성화된 B림프구는 형질세포로 분화하여 초당 수천 개의 정밀한 맞춤형 항체 단백질을 혈액 속으로 쏟아냅니다.',
      deepKnowledge: '일부 B세포는 기억 세포(Memory B cell)로 전환되어 체내에 수십 년간 남아 있다가 같은 병원체에 재감염되었을 때 훨씬 빠르고 강력한 2차 면역 반응을 일으킵니다.',
      sourceOrTrivia: 'Janeway 면역생물학',
    },
    {
      id: 'bio_4',
      topic: '생명과학 & 의학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1928년 알렉산더 플레밍이 푸른곰팡이(Penicillium notatum)에서 우연히 발견하여 수많은 세균 감염증을 퇴치한 인류 최초의 천연 항생제는?',
      options: ['페니실린 (Penicillin)', '아스피린', '스트렙토마이신', '인슐린'],
      correctIndex: 0,
      explanation: '플레밍이 발견하고 플로리와 체인이 정제 및 대량 생산에 성공한 페니실린은 세균의 세포벽 합성을 억제하여 세균을 파괴하는 기적의 약물로 노벨 생리의학상을 수상했습니다.',
      deepKnowledge: '인간 세포는 세포벽이 없고 세포막만 존재하기 때문에, 페니실린은 인체 세포에는 독성을 띠지 않고 세균만을 선택적으로 공격할 수 있습니다.',
      sourceOrTrivia: 'British Journal of Experimental Pathology (1929)',
    },
    {
      id: 'bio_5',
      topic: '생명과학 & 의학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '세균이 바이러스 침입에 대항해 진화시킨 면역 방어 시스템에서 착안하여, 가이드 RNA와 Cas9 단백질을 이용해 원하는 특정 유전자 부위를 정밀 교정하는 3세대 유전자 가위 기술은?',
      options: ['CRISPR-Cas9 (크리스퍼 유전자 가위)', '징크핑거 뉴클레아제', '탈렌 (TALEN)', '중합효소 연쇄반응 (PCR)'],
      correctIndex: 0,
      explanation: '에마뉘엘 샤르팡티에와 제니퍼 다우드나가 개발하여 2020년 노벨 화학상을 수상한 기술로, 20개 염기 길이의 sgRNA가 표적 염기서열을 찾아가면 Cas9 효소가 이중 가닥을 정확히 절단합니다.',
      deepKnowledge: '기존 유전자 조작 기술보다 수십 배 정밀하고 비용이 저렴하며 다중 유전자를 동시 교정할 수 있어 희귀 유전 질환 치료와 작물 개량의 새 지평을 열었습니다.',
      sourceOrTrivia: 'Science (2012) "A Programmable Dual-RNA-Guided DNA Endonuclease in Adaptive Bacterial Immunity"',
    },
    {
      id: 'bio_6',
      topic: '생명과학 & 의학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '정상 체세포가 평생 분열할 수 있는 횟수 제한(헤이플릭 한계)의 주원인으로, 염색체 말단에서 유전자를 보호하다가 분열할 때마다 점차 짧아지는 반복 염기서열 부위는?',
      options: ['텔로미어 (Telomere)', '센트로미어 (동원체)', '인트론', '프로모터'],
      correctIndex: 0,
      explanation: 'DNA 복제 효소의 구조적 한계(선도 가닥과 지연 가닥 복제 메커니즘)로 인해 염색체 말단의 텔로미어는 분열 시마다 마모되며, 임계점 이하로 짧아지면 세포는 노화 또는 사멸 주기에 들어갑니다.',
      deepKnowledge: '암세포의 약 85~90%는 텔로미어를 다시 신장시키는 텔로머레이스(Telomerase) 효소를 비정상적으로 활성화하여 무한히 증식하는 불사(Immortal)의 능력을 획득합니다.',
      sourceOrTrivia: '노벨 생리의학상 (2009년 엘리자베스 블랙번, 캐럴 그라이더, 잭 쇼스택)',
    },
    {
      id: 'bio_7',
      topic: '생명과학 & 의학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: 'DNA 염기서열 자체의 변이 없이도 사이토신에 메틸기가 결합하거나 히스톤 단백질의 변형을 통해 유전자 발현이 영구적·가역적으로 조절되는 현상을 연구하는 학문 분야는?',
      options: ['후성유전학 (Epigenetics)', '유전체학 (Genomics)', '단백체학 (Proteomics)', '대사체학 (Metabolomics)'],
      correctIndex: 0,
      explanation: '동일한 DNA 염기서열을 가진 일란성 쌍둥이라도 환경, 스트레스, 식습관 등에 따라 CpG 섬의 DNA 메틸화와 히스톤 아세틸화 양상이 달라져 서로 다른 질병 감수성과 수명을 갖게 되는 근본 원리입니다.',
      deepKnowledge: '정자와 난자를 통해 특정 후성유전학적 마크가 지워지지 않고 다음 세대로 전달될 수 있음(경세대 후성유전)이 밝혀져 유전학의 전통적 도그마를 확장하고 있습니다.',
      sourceOrTrivia: 'Nature Reviews Genetics "Epigenetic mechanisms in mammals"',
    },
    {
      id: 'bio_8',
      topic: '생명과학 & 의학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '광우병(BSE) 및 인간의 크로이츠펠트-야코프병(CJD)을 유발하며, DNA나 RNA 같은 핵산이 전혀 없이 오직 단백질의 3차원 입체 구조 변형만으로 감염성을 전파하는 병원체는?',
      options: ['프리온 (Prion)', '비로이드 (Viroid)', '박테리오파지', '레트로바이러스'],
      correctIndex: 0,
      explanation: '스탠리 프루시너가 규명하여 노벨상을 받은 병원체로, 정상 프리온 단백질(PrP^C, 주로 α-나선 구조)이 변형 프리온(PrP^Sc, 풍부한 β-병풍 구조)과 접촉하면 비정상 구조로 연쇄 변형되어 뇌 신경세포를 사멸시킵니다.',
      deepKnowledge: '핵산이 없기 때문에 자외선, 고온 멸균, 단백질 분해효소 등에 극도의 내성을 가지며, "모든 감염원은 핵산 유전 물질을 지닌다"는 분자생물학의 중심 원리에 큰 충격을 주었습니다.',
      sourceOrTrivia: 'Prusiner (1982) "Novel proteinaceous infectious particles cause scrapie"',
    },
  ],

  economy: [
    {
      id: 'ec_1',
      topic: '경제 & 금융',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '시장에서 물건을 사려는 사람들의 욕구(수요)와 팔려는 사람들의 의사(공급)가 만나는 지점에서 결정되는 가격은?',
      options: ['균형 가격 (Market Clearing Price)', '통제 가격', '원가 가격', '독점 가격'],
      correctIndex: 0,
      explanation: '아담 스미스가 "보이지 않는 손"으로 비유한 시장 메커니즘에서, 수요량과 공급량이 정확히 일치하는 지점에서 균형 가격과 균형 거래량이 형성됩니다.',
      deepKnowledge: '초과 수요가 발생하면 가격이 상승하여 수요가 감소하고 공급이 늘어나며, 반대로 초과 공급이 발생하면 가격이 하락하여 다시 균형으로 회귀하는 자율 조정 기능을 가집니다.',
      sourceOrTrivia: '맨큐의 경제학 (Principles of Economics)',
    },
    {
      id: 'ec_2',
      topic: '경제 & 금융',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '중앙은행(한국은행 등)이 경기 침체를 극복하기 위해 기준금리를 대폭 인하할 때 시중에서 일반적으로 일어나는 현상은?',
      options: [
        '대출 금리가 하락하여 기업 투자와 가계 소비가 촉진되고 시중 유동성이 증가한다',
        '은행 예금 이자가 폭등하여 사람들이 소비를 멈추고 저축만 늘린다',
        '외국인 투자 자금이 무조건 급증하여 자국 통화 가치가 최고치로 치솟는다',
        '시중의 통화량이 전면 회수되어 극심한 디플레이션이 유발된다',
      ],
      correctIndex: 0,
      explanation: '기준금리를 낮추면 시중은행의 차입 비용이 감소하여 대출 이자가 낮아지고, 통화량이 확대되어 자산 가격 상승 및 경기 부양 효과를 유도합니다.',
      deepKnowledge: '하지만 금리가 제로 수준까지 내려가 유동성을 아무리 풀어도 투자나 소비가 늘지 않는 상태를 케인스는 "유동성 함정(Liquidity Trap)"이라고 정의했습니다.',
      sourceOrTrivia: '한국은행 통화신용정책 운영 원리',
    },
    {
      id: 'ec_3',
      topic: '경제 & 금융',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '이미 지출되어 어떤 선택을 하더라도 다시 회수할 수 없는 비용임에도 불구하고, 그동안 들인 노력이 아까워 비합리적인 결정을 고수하는 심리적 오류는?',
      options: ['매몰비용의 오류 (Sunk Cost Fallacy)', '확증 편향', '앵커링 효과', '손실 회피성'],
      correctIndex: 0,
      explanation: '합리적인 의사결정자는 과거의 회수 불가능한 매몰비용을 배제하고 미래의 한계 편익과 한계 비용만을 비교해야 하지만, 인간은 손실에 대한 심리적 거부감으로 인해 손해를 가중시키는 결정을 지속하곤 합니다.',
      deepKnowledge: '초음속 여객기 개발에서 막대한 적자가 예상됨에도 불구하고 사업을 중단하지 못했던 대표적 사례에서 유래하여 \'콩코드 오류\'라고도 불립니다.',
      sourceOrTrivia: 'Daniel Kahneman의 <생각에 관한 생각 (Thinking, Fast and Slow)>',
    },
    {
      id: 'ec_4',
      topic: '경제 & 금융',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '단기적으로 실업률을 낮추려면 물가 상승률(인플레이션)을 감수해야 한다는 두 변수 간의 역(음)의 상관관계를 나타낸 경제학 곡선은?',
      options: ['필립스 곡선 (Phillips Curve)', '로렌츠 곡선', '래퍼 곡선', '쿠즈네츠 곡선'],
      correctIndex: 0,
      explanation: 'A.W. 필립스가 영국 통계를 바탕으로 발견한 곡선으로, 정부가 총수요 관리 정책을 통해 실업률과 인플레이션 사이에서 정책적 절충(Trade-off)을 선택할 수 있다는 근거로 활용되었습니다.',
      deepKnowledge: '1970년대 오일쇼크로 불황 속에 물가가 치솟는 \'스태그플레이션(Stagflation)\'이 발생하면서 프리드먼 등 통화주의자들에 의해 장기 필립스 곡선은 자연실업률 수준에서 수직선이 됨이 밝혀졌습니다.',
      sourceOrTrivia: 'Milton Friedman (1968) "The Role of Monetary Policy"',
    },
    {
      id: 'ec_5',
      topic: '경제 & 금융',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '게임 이론에서 모든 참여자가 상대방의 전략을 전제로 할 때, 어느 누구도 자신의 전략을 일방적으로 변경하여 이득을 얻을 수 없는 정체 상태를 뜻하는 개념은?',
      options: ['내쉬 균형 (Nash Equilibrium)', '파레토 최적', '샤플리 값', '최대최소 전략'],
      correctIndex: 0,
      explanation: '존 내쉬가 수학적으로 증명하여 1994년 노벨 경제학상을 수상한 개념으로, 참가자 각자의 최선의 반응(Best Response)이 서로 일치하는 안정적 균형점을 의미합니다.',
      deepKnowledge: '죄수의 딜레마(Prisoner\'s Dilemma)에서 보듯, 각자가 이기적으로 최선의 선택(배신)을 하여 도달한 내쉬 균형이 집단 전체로서는 상호 협력보다 열등한 결과(비파레토 최적)를 낳는 비극이 발생합니다.',
      sourceOrTrivia: 'John Nash (1950) "Equilibrium points in n-person games"',
    },
    {
      id: 'ec_6',
      topic: '경제 & 금융',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '2008년 글로벌 금융위기 이후 중앙은행이 기준금리가 제로에 도달하자 직접 장기 국채나 모기지 채권을 대규모로 매입하여 시장에 유동성을 주입한 비전통적 통화정책은?',
      options: ['양적완화 (Quantitative Easing / QE)', '오퍼레이션 트위스트', '지급준비율 인상', '외환 스왑 경매'],
      correctIndex: 0,
      explanation: '벤 버냉키 의장의 미국 연준(Fed) 등이 주도한 정책으로, 단기 금리 조절이 불가능한 한계 상황에서 중앙은행 대차대조표를 확대해 장기 금리를 끌어내리고 금융 시스템 붕괴를 막았습니다.',
      deepKnowledge: '이후 시중 유동성을 회수하기 위해 보유 자산을 매각하거나 만기 채권 재투자를 중단하는 정책을 양적긴축(Quantitative Tightening / QT)이라 부릅니다.',
      sourceOrTrivia: 'Ben Bernanke의 연설 및 연준 정책 백서',
    },
    {
      id: 'ec_7',
      topic: '경제 & 금융',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '1973년 발표되어 현대 금융공학의 파생상품 시장을 개척하고 노벨 경제학상(1997)을 이끈 "블랙-숄즈 옵션 가격 결정 모형(Black-Scholes Model)"의 핵심 수학적 가설은?',
      options: [
        '기초 자산의 가격이 기하 브라운 운동(Geometric Brownian Motion)을 따르며 무위험 차익거래(No-arbitrage)가 불가능한 포트폴리오 복제가 성립한다',
        '모든 투자자가 미래 수익률을 정확히 예측하는 완전 예지 능력을 가정한다',
        '이자율이 항상 음수(-)를 유지하는 디플레이션 상태를 기본 전제로 한다',
        '자산의 변동성이 주가의 상승에 따라 선형적으로 무한히 증가한다고 가정한다',
      ],
      correctIndex: 0,
      explanation: '피셔 블랙과 마이런 숄즈, 로버트 머튼은 연속 시간 이토 미적분학(Itô calculus)을 활용하여 주식과 무위험 채권을 결합해 옵션의 수익 구조를 완벽히 복제함으로써 옵션의 이론적 적정 가치를 도출했습니다.',
      deepKnowledge: '실제 시장에서는 정규분포의 꼬리가 이론보다 훨씬 두껍고(팻 테일 / Fat Tail), 내재 변동성이 행사가격에 따라 웃는 모양을 그리는 \'변동성 스마일(Volatility Smile)\' 현상이 관측됩니다.',
      sourceOrTrivia: 'Journal of Political Economy (1973) "The Pricing of Options and Corporate Liabilities"',
    },
    {
      id: 'ec_8',
      topic: '경제 & 금융',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '합리적 기대가설에 기반한 로버트 배로의 "리카도 대등 정리(Ricardian Equivalence)"가 주장하는 재정 정책에 관한 가장 급진적인 명제는?',
      options: [
        '정부가 세금을 깎아주고 국채를 발행해 지출을 늘려도, 합리적 소비자는 미래의 세금 인상을 예상하여 소비 대신 저축을 늘리므로 총수요에 실질적 부양 효과가 없다',
        '국채를 발행하면 반드시 물가가 폭등하여 통화 단위가 붕괴한다',
        '정부 부채의 비율은 국가의 GDP 성장률과 완전히 무관하게 일정하다',
        '세율을 극대화할수록 민간의 지하경제 규모가 완전히 0으로 수렴한다',
      ],
      correctIndex: 0,
      explanation: '합리적인 가계는 현재의 감세가 결국 미래 세대의 세금 부담(또는 자신의 미래 세금 부담)으로 돌아온다는 것을 인지하므로, 소득이 늘었다고 착각하지 않고 미래 세금 납부를 위해 현재 소비를 늘리지 않는다는 재정 무력성 이론입니다.',
      deepKnowledge: '현실에서는 유동성 제약이 있는 가계의 존재, 미래 세대에 대한 이타성의 한계, 근시안적 경제 주체 등으로 인해 리카도 대등 정리가 완벽히 성립하지는 않으나 현대 거시경제학의 중대한 기준 모델입니다.',
      sourceOrTrivia: 'Barro (1974) "Are Government Bonds Net Wealth?"',
    },
  ],

  art_culture: [
    {
      id: 'art_1',
      topic: '미술 & 문화예술',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '레오나르도 다빈치의 걸작 <모나리자>에서 인물의 윤곽선을 뚜렷하게 그리지 않고 연기처럼 부드럽게 번지듯 음영 처리하여 신비로운 미소를 자아낸 명암 기법은?',
      options: ['스푸마토 (Sfumato)', '점묘법 (Pointillism)', '콜라주 (Collage)', '프로타주 (Frottage)'],
      correctIndex: 0,
      explanation: '이탈리아어로 \'연기처럼 사라지다\'라는 뜻의 스푸마토는 색채 사이의 경계선을 미세한 그러데이션으로 뭉개어 입체감과 미묘한 표정을 극대화한 르네상스 회화 기법입니다.',
      deepKnowledge: '다빈치는 눈가와 입술 가장자리에 수십 겹의 반투명 유채 글레이즈를 1~2마이크로미터 두께로 겹겹이 칠해 인간의 시선 각도에 따라 미소가 달라 보이는 착시를 설계했습니다.',
      sourceOrTrivia: '루브르 박물관 모나리자 과학 분석 리포트',
    },
    {
      id: 'art_2',
      topic: '미술 & 문화예술',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '19세기 후반 프랑스에서 시작되어, 화실을 벗어나 야외에서 시시각각 변화하는 자연의 빛과 색채의 순간적 느낌을 포착한 클로드 모네, 오귀스트 르누아르 등의 미술 사조는?',
      options: ['인상주의 (Impressionism)', '신고전주의', '초현실주의', '팝아트'],
      correctIndex: 0,
      explanation: '모네의 작품 <인상, 해돋이(Impression, soleil levant)>에서 유래된 용어로, 사물의 고유색을 부정하고 태양광선 아래에서 변하는 순간의 시각적 인상을 빠른 붓터치로 화폭에 담았습니다.',
      deepKnowledge: '튜브 물감의 발명과 접이식 이젤의 등장은 화가들이 화실을 벗어나 야외(En plein air)에서 직접 빛을 관찰하며 그릴 수 있게 만든 기술적 토대였습니다.',
      sourceOrTrivia: 'E.H. 곰브리치의 <서양미술사>',
    },
    {
      id: 'art_3',
      topic: '미술 & 문화예술',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '사물을 단일 시점에서 바라보는 르네상스 원근법을 전면 부정하고, 여러 각도에서 본 사물의 형태를 기하학적 면으로 해체·재구성한 파블로 피카소와 조르주 브라크의 혁신적 미술 운동은?',
      options: ['입체주의 (Cubism / 큐비즘)', '낭만주의', '다다이즘', '표현주의'],
      correctIndex: 0,
      explanation: '피카소의 <아비뇽의 처녀들(1907)>을 시발점으로 하여, 2차원의 평면 캔버스 위에 3차원 대상의 복수 시점을 동시에 표현함으로써 서양 회화의 500년 공간 개념을 근본적으로 해체했습니다.',
      deepKnowledge: '초기 \'분석적 입체주의\'(형태의 해체와 단색조)에서 출발하여 이후 신문지나 악보를 직접 캔버스에 붙이는 파피에 콜레 등 \'종합적 입체주의\'로 발전했습니다.',
      sourceOrTrivia: '뉴욕 현대미술관(MoMA) 큐비즘 해설집',
    },
    {
      id: 'art_4',
      topic: '미술 & 문화예술',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1919년 발터 그로피우스가 독일 바이마르에 설립하여 "형태는 기능을 따른다"는 현대 디자인과 건축, 예술과 산업 기술의 통합 교육을 선도한 전설적인 조형 예술 학교는?',
      options: ['바우하우스 (Bauhaus)', '에콜 데 보자르', '아르누보 길드', '로열 아카데미'],
      correctIndex: 0,
      explanation: '바우하우스는 순수 예술과 응용 미술의 구분을 없애고, 기계 대량생산 시대에 적합한 기능적이면서도 아름다운 표준 디자인을 창조하여 오늘날 모더니즘 디자인의 모태가 되었습니다.',
      deepKnowledge: '나치의 탄압으로 1933년 강제 폐교되었으나 미스 반 데어 로에, 바실리 칸딘스키 등 교수진이 미국으로 망명하며 전 세계 건축과 시각 디자인 교육의 표준으로 확산되었습니다.',
      sourceOrTrivia: 'Magdalena Droste의 <Bauhaus 1919-1933>',
    },
    {
      id: 'art_5',
      topic: '미술 & 문화예술',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '마르셀 뒤샹이 1917년 기성품 소변기에 <샘(Fountain)>이라는 서명을 붙여 전시하려 했던 것처럼, 물리적 작품 자체보다 작가의 아이디어와 맥락적 선택을 예술의 본질로 정의한 사조는?',
      options: ['개념미술 (Conceptual Art) / 레디메이드', '옵아트', '미니멀리즘 조각', '미래주의'],
      correctIndex: 0,
      explanation: '뒤샹의 레디메이드(Ready-made)는 "화가의 손기술이나 미적 조화가 아니라, 일상 사물을 예술적 맥락으로 전이시키는 작가의 지적 선택이야말로 진정한 예술"이라는 전복적 질문을 던졌습니다.',
      deepKnowledge: '2004년 영국 예술계 전문가 500인이 선정한 \'20세기 가장 영향력 있는 예술작품 1위\'에 피카소의 작품들을 제치고 뒤샹의 <샘>이 선정되었습니다.',
      sourceOrTrivia: 'Turner Prize 2004 Experts Survey on 20th Century Art',
    },
    {
      id: 'art_6',
      topic: '미술 & 문화예술',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '17세기 바로크 회화에서 카라바조가 완성한 기법으로, 칠흑 같은 어둠 속에 한 줄기 강렬한 스포트라이트 조명을 비추듯 극적인 명암 대비를 연출하는 기법은?',
      options: ['테네브리즘 (Tenebrism) / 극단적 키아로스쿠로', '임파스토 (Impasto)', '글레이징', '알라 프리마'],
      correctIndex: 0,
      explanation: '이탈리아어 \'tenebroso(어두운)\'에서 유래한 기법으로, 배경을 깊은 어둠 속에 묻고 주 대상을 강렬한 사광(斜光)으로 부각시켜 연극 무대와 같은 폭발적 긴장감을 부여합니다.',
      deepKnowledge: '카라바조의 이 빛의 혁신은 렘브란트, 벨라스케스, 조르주 드 라 투르 등 바로크 거장들에게 계승되어 서양 회화의 시각적 내러티브를 한 단계 도약시켰습니다.',
      sourceOrTrivia: 'Caravaggio and His Followers in Rome (National Gallery)',
    },
    {
      id: 'art_7',
      topic: '미술 & 문화예술',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '철학자 발터 벤야민이 <기술복제시대의 예술작품>에서 사진과 영화 같은 대량 복제 매체의 등장으로 인해 소멸한다고 분석한 원본 예술품 특유의 시간과 공간의 유일무이한 분위기는?',
      options: ['아우라 (Aura)', '카타르시스', '시뮬라크르', '미메시스 (Mimesis)'],
      correctIndex: 0,
      explanation: '벤야민은 전통 예술이 지녔던 "지금, 여기(Hier und Jetzt)"라는 일회적 현존성과 종교적 제의 가치가 기술적 복제 가능성에 의해 상실되며, 대신 예술의 정치적·전시 가치가 전면에 부각된다고 통찰했습니다.',
      deepKnowledge: '벤야민은 아우라의 붕괴를 비극으로만 보지 않고, 귀족과 부르주아의 전유물이었던 예술이 대중의 비판적 수용과 해방적 정치의 도구로 전환될 수 있는 가능성을 함께 포착했습니다.',
      sourceOrTrivia: '발터 벤야민의 <기술복제시대의 예술작품 (1936)>',
    },
    {
      id: 'art_8',
      topic: '미술 & 문화예술',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '임마누엘 칸트의 <판단력 비판>에서 미적 판정이 개인의 실용적 욕망이나 소유욕, 윤리적 이해관계(Interest)로부터 완전히 자유로워야 성립한다고 본 미적 태도의 핵심 원리는?',
      options: [
        '무관심성 (Disinterestedness / 無關心性)',
        '효용 극대화 원리',
        '감정이입 (Einfühlung)',
        '교화적 목적성',
      ],
      correctIndex: 0,
      explanation: '칸트는 아름다움에 대한 판단(취미판단)은 대상을 소유하거나 먹거나 이용하려는 사적 욕망과 무관하게, 대상의 형식적 합목적성을 순수하게 관조할 때 보편타당성을 획득한다고 보았습니다.',
      deepKnowledge: '이 "무관심한 쾌(Uninteressiertes Wohlgefallen)" 개념은 훗날 19세기 "예술을 위한 예술(L\'art pour l\'art)" 지상주의와 현대 형식주의 미학의 절대적 철학적 근거가 되었습니다.',
      sourceOrTrivia: '칸트의 <판단력 비판 (Kritik der Urteilskraft, 1790)> 제1권 미의 분석론',
    },
  ],

  psychology_brain: [
    {
      id: 'psy_1',
      topic: '심리학 & 인지과학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '러시아의 생리학자 이반 파블로프가 개의 침샘 실험을 통해 입증한 것으로, 무조건 자극(먹이)과 중립 자극(종소리)의 연합을 통해 새로운 반응을 이끌어내는 학습 원리는?',
      options: ['고전적 조건형성 (Classical Conditioning)', '조작적 조건형성', '사회학습 이론', '통찰 학습'],
      correctIndex: 0,
      explanation: '본래 침을 흘리게 하지 못하던 종소리(조건 자극)가 먹이(무조건 자극)와 반복적으로 짝지어짐으로써 종소리만으로도 침 분비(조건 반응)를 유발하는 행동주의 심리학의 기본 원리입니다.',
      deepKnowledge: '훗날 존 왓슨의 \'어린 앨버트 실험\'을 통해 공포증과 같은 감정적 반응 역시 고전적 조건형성을 통해 인간에게 학습될 수 있음이 증명되었습니다.',
      sourceOrTrivia: 'Pavlov (1927) "Conditioned Reflexes"',
    },
    {
      id: 'psy_2',
      topic: '심리학 & 인지과학',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '자신의 신념, 태도와 실제 자신의 행동이 모순되거나 불일치할 때 발생하는 심리적 불쾌감을 해소하기 위해 자신의 태도를 바꾸거나 행동을 합리화하는 현상은?',
      options: ['인지부조화 (Cognitive Dissonance)', '플라시보 효과', '방관자 효과', '후광 효과'],
      correctIndex: 0,
      explanation: '레온 페스팅거(Leon Festinger)가 1957년 제안한 이론으로, 인간은 내면의 일관성을 유지하려는 강력한 동기를 지니고 있어 모순이 생기면 믿음을 바꾸어서라도 심리적 평형을 회복하려 합니다.',
      deepKnowledge: '이솝 우화에서 여우가 포도에 손이 닿지 않자 "저 포도는 분명히 신 포도일 거야"라고 단정하는 신포도 심리가 인지부조화 합리화의 고전적 비유입니다.',
      sourceOrTrivia: 'Festinger (1957) "A Theory of Cognitive Dissonance"',
    },
    {
      id: 'psy_3',
      topic: '심리학 & 인지과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '1961년 예일대학교의 스탠리 밀그램이 실시한 충격적인 심리 실험으로, 흰 가운을 입은 권위자의 명령이 있을 때 평범한 사람들이 타인에게 치명적 전기충격을 가하는 복종 심리를 밝혀낸 연구는?',
      options: ['밀그램 복종 실험 (Milgram Obedience Experiment)', '스탠퍼드 감옥 실험', '로젠한 실험', '애쉬의 동조 실험'],
      correctIndex: 0,
      explanation: '피험자의 무려 65%가 타인이 고통에 비명을 지름에도 불구하고 실험자의 "계속 진행하십시오"라는 명령에 따라 치사량에 가까운 450볼트 최고 전압 버튼을 누르는 충격적 결과를 보였습니다.',
      deepKnowledge: '한나 아렌트가 아이히만 재판을 보며 제시한 "악의 평범성(Banality of Evil)" 개념을 실험실 상황에서 실증적으로 뒷받침한 20세기 사회심리학 최고의 기념비적 연구입니다.',
      sourceOrTrivia: 'Milgram (1963) "Behavioral Study of Obedience"',
    },
    {
      id: 'psy_4',
      topic: '심리학 & 인지과학',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '인간의 뇌 측두엽 안쪽에 위치하며, 새로운 경험과 정보를 단기기억에서 영구적인 장기기억으로 변환(기억 응고화)하는 데 결정적인 중추 역할을 하는 해마(Hippocampus)와 관련된 설명은?',
      options: [
        '해마가 손상되면 과거의 오래된 기억은 유지되지만 새로운 사건을 장기기억으로 저장하지 못하는 전향성 건망증이 발생한다',
        '해마는 오직 심장 박동과 호흡 같은 자율신경계 반사만을 조절한다',
        '해마는 근육 운동의 미세한 균형만을 담당하며 기억과는 무관하다',
        '해마를 제거하면 인간의 시각 인지 능력이 완전히 소멸된다',
      ],
      correctIndex: 0,
      explanation: '간질 치료를 위해 양측 해마를 절제한 유명한 환자 H.M.(헨리 몰레이슨) 연구를 통해, 해마가 새로운 서술기억(사실과 사건)의 형성에 필수불가결하다는 뇌과학의 대발견이 이루어졌습니다.',
      deepKnowledge: '해마의 신경세포는 성인이 된 이후에도 새로운 뉴런이 생성되는 성체 신경발생(Adult Neurogenesis)이 활발히 일어나는 뇌의 매우 특별한 영역 중 하나입니다.',
      sourceOrTrivia: 'Scoville & Milner (1957) "Loss of Recent Memory After Bilateral Hippocampal Lesions"',
    },
    {
      id: 'psy_5',
      topic: '심리학 & 인지과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '노벨 경제학상을 수상한 대니얼 카너먼이 <생각에 관한 생각>에서 정립한 이중과정 이론(Dual Process Theory)의 \'시스템 1\'과 \'시스템 2\'의 특성을 바르게 짝지은 것은?',
      options: [
        '시스템 1은 자동적이고 빠르며 무의식적인 직관 / 시스템 2는 느리고 의식적이며 노력이 필요한 논리적 사고',
        '시스템 1은 복잡한 다변수 수학 계산 / 시스템 2는 위험을 감지하는 순간적 공포 반응',
        '시스템 1은 언어 문법의 엄밀한 교정 / 시스템 2는 동공 크기의 무의식적 변화',
        '시스템 1은 장기 금융 포트폴리오 계획 / 시스템 2는 친숙한 사람의 얼굴 즉각 인식',
      ],
      correctIndex: 0,
      explanation: '인간은 에너지 소모를 줄이기 위해 일상 결정의 대부분을 빠르고 어림짐작에 의존하는 시스템 1(휴리스틱)으로 처리하며, 깊은 주의 집중과 통계적 계산이 요구될 때만 시스템 2를 활성화합니다.',
      deepKnowledge: '인지적 구두쇠(Cognitive Miser) 성향으로 인해 시스템 2가 게으르게 작동할 때 기저율 무시, 닻내림 효과, 가용성 편향 등 체계적인 인지적 오류가 발생합니다.',
      sourceOrTrivia: 'Daniel Kahneman의 <Thinking, Fast and Slow (2011)>',
    },
    {
      id: 'psy_6',
      topic: '심리학 & 인지과학',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '사건을 직접 목격한 이후에 주어지는 사후 오도 정보(Misinformation)나 유도 질문에 의해 목격자의 본래 기억이 오염되거나 거짓 기억(False Memory)이 생성되는 심리학 효과는?',
      options: [
        '오정보 효과 (Misinformation Effect / 엘리자베스 로프터스 연구)',
        '초두 효과 (Primacy Effect)',
        '칵테일파티 효과',
        '피그말리온 효과',
      ],
      correctIndex: 0,
      explanation: '인지심리학자 엘리자베스 로프터스의 실험에서, 자동차 충돌 영상을 본 사람들에게 "차가 부딪혔을 때(Hit)" 대신 "박살 났을 때(Smashed)"라는 단어를 쓰자 실제로 없었던 깨진 유리창 파편을 보았다고 기억하는 현상이 관측되었습니다.',
      deepKnowledge: '인간의 기억은 비디오카메라처럼 기록을 재생하는 것이 아니라 회상할 때마다 뇌에서 재구성되는 취약한 가소성(Reconstructive Nature)을 지님을 입증하여 법정 증언 제도를 혁신했습니다.',
      sourceOrTrivia: 'Loftus & Palmer (1974) "Reconstruction of Automobile Destruction"',
    },
    {
      id: 'psy_7',
      topic: '심리학 & 인지과학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '성인의 뇌 신경세포와 시냅스 연결망이 고정불변한 것이 아니라, 새로운 학습과 환경적 자극, 심지어 뇌 손상 이후의 재활 과정에 따라 물리적으로 구조와 회로를 끊임없이 재구성한다는 뇌과학의 패러다임 전환은?',
      options: ['신경가소성 (Neuroplasticity)', '골지 복합체 설', '대뇌 국재화 고정론', '골상학'],
      correctIndex: 0,
      explanation: '20세기 중반까지 성인의 뇌세포는 재생되지 않고 퇴화만 한다는 것이 통설이었으나, 시냅스 가소성(LTP/LTD)과 기능적 재배치 연구를 통해 뇌는 평생에 걸쳐 경험에 의해 물리적으로 조각됨이 입증되었습니다.',
      deepKnowledge: '런던 택시 기사들의 뇌 MRI 분석에서 복잡한 시내 길을 암기한 베테랑 기사일수록 공간 기억을 담당하는 해마 후부의 회백질 부피가 통계적으로 유의미하게 비대해진 사례가 대표적입니다.',
      sourceOrTrivia: 'Maguire et al. (2000) "Navigation-related structural change in the hippocampi of taxi drivers"',
    },
    {
      id: 'psy_8',
      topic: '심리학 & 인지과학',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '철학자 앤디 클라크와 데이비드 차머스가 1998년 발표한 급진적 인지철학 논제로, 인간의 사고와 인지 과정이 두개골 내부의 뇌에 갇혀 있는 것이 아니라 스마트폰, 수첩, 계산기 등 외부 환경의 도구와 끊김 없이 결합된 결합체계(Coupled System)로 확장되어 존재한다는 이론은?',
      options: [
        '확장된 인지 가설 (The Extended Mind Thesis)',
        '환원주의적 물리주의',
        '데카르트 실체이원론',
        '행동주의 기계론',
      ],
      correctIndex: 0,
      explanation: '기억상실 환자 오토가 항상 가지고 다니는 공책이 보통 사람의 뇌 속 생물학적 기억과 기능적으로 정확히 동등한 인지적 역할을 수행하듯, 외부 도구 역시 인간 인지 시스템의 유기적 일부로 보아야 한다는 이론입니다.',
      deepKnowledge: '이는 현대 생성형 AI와 스마트 디바이스를 단순한 외장 기계가 아닌 인류 지능의 인지적 확장 기관으로 바라보는 인공지능 윤리 및 사이보그 철학의 핵심 이론적 모태입니다.',
      sourceOrTrivia: 'Clark & Chalmers (1998) "The Extended Mind", Analysis 58(1)',
    },
  ],
  literature_classics: [
    {
      id: 'lit_1',
      topic: '문학 & 세계 고전',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '호메로스의 고대 그리스 2대 서사시 중 하나로, 트로이 전쟁 이후 고향 이타카로 돌아가는 영웅의 10년간의 모험과 귀향을 그린 대서사시는?',
      options: ['오디세이아 (Odyssey)', '길가메시 서사시', '아이네이스', '베오울프'],
      correctIndex: 0,
      explanation: '트로이 목마 계책으로 트로이를 함락시킨 오디세우스가 포세이돈의 분노로 표류하며 키클롭스, 사이렌, 칼립소 등을 거쳐 귀향하는 서사시입니다.',
      deepKnowledge: '서양 문학에서 "오디세이(Odyssey)"라는 단어 자체가 파란만장한 긴 여정과 인생의 모험을 뜻하는 보통명사로 정착되었습니다.',
      sourceOrTrivia: 'Homer <Odyssey> (기원전 8세기경)',
    },
    {
      id: 'lit_2',
      topic: '문학 & 세계 고전',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '윌리엄 셰익스피어의 4대 비극에 포함되지 않는 희곡 작품은?',
      options: ['로미오와 줄리엣', '햄릿', '오셀로', '리어 왕'],
      correctIndex: 0,
      explanation: '셰익스피어의 공식적인 4대 비극은 <햄릿>, <오셀로>, <리어 왕>, <맥베스>입니다. <로미오와 줄리엣>은 초기 대표 비극이지만 4대 비극에는 포함되지 않습니다.',
      deepKnowledge: '<맥베스>는 권력욕, <오셀로>는 질투, <리어 왕>은 배은망덕과 통찰, <햄릿>은 우유부단과 사유라는 인간 영혼의 보편적 비극 결함을 깊이 파고듭니다.',
      sourceOrTrivia: 'A.C. Bradley <Shakespearean Tragedy (1904)>',
    },
    {
      id: 'lit_3',
      topic: '문학 & 세계 고전',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '단테 알리기에리가 피렌체 방언(이탈리아어)으로 저술한 대서사시로, 로마 시인 베르길리우스와 연인 베아트리체의 인도를 받아 저승을 순례하는 3부작 구성의 걸작은?',
      options: ['신곡 (La Divina Commedia)', '데카메론', '실낙원', '파우스트'],
      correctIndex: 0,
      explanation: '단테의 <신곡>은 지옥편(Inferno), 연옥편(Purgatorio), 천국편(Paradiso) 3개 권역(각 33가, 총 100가)으로 이루어진 중세 기독교 세계관의 집대성입니다.',
      deepKnowledge: '당시 학술 공용어였던 라틴어 대신 속어(토스카나 방언)로 쓰여 이탈리아 표준어 성립에 지대한 공헌을 하였습니다.',
      sourceOrTrivia: 'Dante Alighieri <Divina Commedia (1320)>',
    },
    {
      id: 'lit_4',
      topic: '문학 & 세계 고전',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '어느 날 아침 불안한 꿈에서 깨어났을 때, 자신이 흉측한 한 마리의 거대한 벌레(해충)로 변해버린 주인공 "그레고르 잠자"의 소외와 실존적 비극을 다룬 프란츠 카프카의 소설은?',
      options: ['변신 (Die Verwandlung)', '소송 (심판)', '성 (Das Schloss)', '시골의사'],
      correctIndex: 0,
      explanation: '카프카의 <변신>은 가족의 생계를 짊어진 평범한 외판원이 벌레로 변하자 도구적 효용을 잃고 결국 가족들에게조차 짐승으로 버림받는 현대인의 도구화와 고립을 통렬히 고발합니다.',
      deepKnowledge: '실존주의 철학자 사르트르와 카뮈에게 심대한 영향을 주었으며, "카프카적(Kafkaesque)"이라는 부조리 문학의 대명사가 되었습니다.',
      sourceOrTrivia: 'Franz Kafka <Die Verwandlung (1915)>',
    },
    {
      id: 'lit_5',
      topic: '문학 & 세계 고전',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '도스토옙스키의 소설 <카라마조프 가의 형제들> 제5권에 등장하는 유명한 극중 극으로, 지상에 재림한 예수를 체포하여 "인간에게 자유는 너무 무거운 짐이며, 빵과 기적으로 지배해야 한다"고 반박하는 에피소드는?',
      options: ['대심문관 (The Grand Inquisitor)', '지하로부터의 수기', '죄와 벌', '백치'],
      correctIndex: 0,
      explanation: '둘째 이반 카라마조프가 지은 서사시에서, 스페인 세비야에 재림한 예수에게 90세의 대심문관은 "인간은 자유를 감당하지 못하므로 기적, 신비, 권위로 통치해야 한다"고 예수를 비난합니다.',
      deepKnowledge: '인간의 자유의지와 신정론(Theodicy), 전체주의 권력의 본질을 다룬 서양 문학사상 가장 심오한 철학적 담론 중 하나로 꼽힙니다.',
      sourceOrTrivia: 'Dostoevsky <The Brothers Karamazov (1880)> Book V, Ch. 5',
    },
    {
      id: 'lit_6',
      topic: '문학 & 세계 고전',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '제임스 조이스의 <율리시스>나 버지니아 울프의 소설에서 두드러진 기법으로, 인물의 논리적인 생각뿐 아니라 순간적인 감각, 연상, 무의식적 기억의 단편들을 여과 없이 서술하는 모더니즘 문학 기법은?',
      options: ['의식의 흐름 (Stream of Consciousness)', '낯설게 하기 (Defamiliarization)', '소외 효과', '간텍스트성'],
      correctIndex: 0,
      explanation: '심리학자 윌리엄 제임스의 개념에서 유래한 기법으로, 시간적 순서나 인과적 문장 구조를 깨고 등장인물의 내면에서 찰나마다 흘러가는 의식의 물결을 생생하게 포착합니다.',
      deepKnowledge: '<율리시스>의 마지막 장인 "몰리 블룸의 독백"은 쉼표나 마침표 등 구두점 없이 수십 페이지에 걸쳐 여성의 내면 의식을 펼쳐냅니다.',
      sourceOrTrivia: 'William James <The Principles of Psychology (1890)> & James Joyce',
    },
    {
      id: 'lit_7',
      topic: '문학 & 세계 고전',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '프랑스의 구조주의 문학비평가 롤랑 바르트가 1967년 발표한 기념비적 에세이로, 텍스트의 의미는 원작자의 의도나 전기에 구속되는 것이 아니라 독자의 능동적 읽기 행위 속에서 비로소 탄생한다고 선언한 논제는?',
      options: ['저자의 죽음 (The Death of the Author)', '신화론 (Mythologies)', '기호학의 모험', '텍스트의 즐거움'],
      correctIndex: 0,
      explanation: '바르트는 텍스트를 고정된 진리를 가진 작가의 사유물이 아닌, 수많은 문화적 인용의 직물(Tissue of Quotations)로 보았으며 "독자의 탄생은 필연적으로 저자의 죽음의 대가를 치러야 한다"고 천명했습니다.',
      deepKnowledge: '이는 포스트모더니즘과 후기구조주의 비평 이론의 분수령이 되어, 해석의 권위를 작가 중심주의에서 수용자 및 독자 반응 이론으로 전환시켰습니다.',
      sourceOrTrivia: 'Roland Barthes (1967) "La mort de l\'auteur"',
    },
    {
      id: 'lit_8',
      topic: '문학 & 세계 고전',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '러시아 문학이론가 미하일 바흐틴이 도스토옙스키의 소설을 분석하며 정립한 개념으로, 단일한 작가의 목소리가 전체를 지배하는 것이 아니라 동등한 가치를 지닌 복수의 독립된 의식과 목소리들이 대등하게 충돌하고 상호작용하는 서사 구조는?',
      options: ['다성성 / 폴리포니 (Polyphony)', '단성적 독백주의 (Monologism)', '환원주의적 메타서사', '미메시스 (Mimesis)']
,
      correctIndex: 0,
      explanation: '바흐틴은 전통 소설의 일방적 독백(Monologue)과 달리, 도스토옙스키의 인물들은 작가의 꼭두각시가 아니라 자신만의 사상과 목소리로 작가조차 예측하기 힘든 자율적 대화(Dialogism)를 수행한다고 보았습니다.',
      deepKnowledge: '바흐틴의 대화주의(Dialogism)와 카니발 이론은 현대 문화 연구, 탈식민주의, 언어학에 걸쳐 다문화적 다양성과 비판적 담론 분석의 주춧돌이 되었습니다.',
      sourceOrTrivia: 'Mikhail Bakhtin <Problems of Dostoevsky\'s Poetics (1929)>',
    },
  ],
  earth_environment: [
    {
      id: 'geo_1',
      topic: '지구과학 & 환경생태',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '20세기 초 알프레트 베게너가 주창한 대륙이동설을 바탕으로 발전하여, 지구 표면이 약 10여 개의 거대한 암석 조각(판)으로 나뉘어 맨틀의 대류에 의해 서서히 움직인다는 현대 지구과학 이론은?',
      options: ['판구조론 (Plate Tectonics)', '지구수축설', '지향사 이론', '해저정지설'],
      correctIndex: 0,
      explanation: '1960년대 해양저 확장설과 고지자기 역전 줄무늬 발견을 통해 맨틀 대류에 의해 판이 생성·이동·소멸하며 지진과 화산이 판의 경계에서 발생한다는 판구조론이 확립되었습니다.',
      deepKnowledge: '베게너 생전에는 대륙을 움직이는 원동력을 명쾌히 규명하지 못해 배척받았으나, 홈스의 맨틀 대류 가설과 해양학 데이터에 힘입어 과학사상 가장 위대한 패러다임 혁명 중 하나로 부활했습니다.',
      sourceOrTrivia: 'Alfred Wegener (1912) & Tuzo Wilson (1965)',
    },
    {
      id: 'geo_2',
      topic: '지구과학 & 환경생태',
      difficulty: 'easy',
      difficultyLabel: '기초 상식',
      question: '지구 대기권 중 지표면에서 고도 약 10~50km 사이에 위치하며, 태양으로부터 방출되는 해로운 자외선(UV-C 및 대부분의 UV-B)을 흡수해 지상 생명체를 보호하는 층은?',
      options: ['오존층 (성층권 내)', '전리층', '중간권 계면', '열권'],
      correctIndex: 0,
      explanation: '성층권의 오존(O3)층은 자외선을 흡수하여 광화학 반응을 일으키며, 이 덕분에 지상에 복잡한 육상 생명체가 번성할 수 있는 생존 장벽이 마련되었습니다.',
      deepKnowledge: '프레온가스(CFCs)로 인한 오존 구멍을 막기 위해 1987년 체결된 몬트리올 의정서는 인류 역사상 가장 성공적인 국제 환경 협약으로 평가받습니다.',
      sourceOrTrivia: 'WMO/UNEP Scientific Assessment of Ozone Depletion',
    },
    {
      id: 'geo_3',
      topic: '지구과학 & 환경생태',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '해수의 수온(열)과 염분 농도 차이에 따른 밀도 변화에 의해 구동되며, 그린란드 해역에서 심해로 침강하여 전 지구 해양을 약 1,000~2,000년에 걸쳐 순환시키는 거대한 심층 해류 시스템은?',
      options: [
        '열염순환 (Thermohaline Circulation / 대양 컨베이어 벨트)',
        '엘니뇨 남방진동',
        '코리올리 에크만 수송',
        '아열대 환류 및 해양 와류 (Subtropical Gyre & Mesoscale Eddies)',
      ],
      correctIndex: 0,
      explanation: '열염순환(AMOC)은 적도의 따뜻한 열에너지를 북대서양으로 실어 나르고 차가워진 고염분 해수가 가라앉아 전 지구 기후를 안정화하는 지구의 거대한 기후 에어컨 역할을 합니다.',
      deepKnowledge: '지구온난화로 그린란드 빙하가 녹아 막대한 담수가 유입되면 표층수의 염분이 낮아져 침강이 멈추거나 둔화될 수 있어 기후 급변의 임계점(Tipping Point)으로 경고받습니다.',
      sourceOrTrivia: 'Wallace Broecker (1991) "The Great Ocean Conveyor"',
    },
    {
      id: 'geo_4',
      topic: '지구과학 & 환경생태',
      difficulty: 'medium',
      difficultyLabel: '일반 지식',
      question: '지구 생태학자 제임스 러브록과 린 마굴리스가 제안한 이론으로, 지구 생물권과 대기, 해양, 지각이 서로 상호작용하여 지구 전체를 생명 유지에 최적화된 하나의 자기조절 유기체(Self-regulating System)로 본 가설은?',
      options: ['가이아 이론 (Gaia Hypothesis)', '생물중심주의', '신다윈주의', '적자생존론'],
      correctIndex: 0,
      explanation: '러브록은 지구 대기의 산소 농도(약 21%)와 해양의 염분 농도가 수억 년간 일정하게 유지되는 것은 생명체들이 지구 환경을 능동적으로 항상성 있게 유지하기 때문이라고 설명했습니다.',
      deepKnowledge: '초기에는 의인화된 목적론이라는 비판을 받았으나, 단순한 모델인 "데이지월드(Daisyworld)" 시뮬레이션을 통해 피드백 루프만으로 자율 조절이 가능함을 수학적으로 증명했습니다.',
      sourceOrTrivia: 'James Lovelock <Gaia: A New Look at Life on Earth (1979)>',
    },
    {
      id: 'geo_5',
      topic: '지구과학 & 환경생태',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '지구 공전 궤도의 이심률 변화(약 10만 년), 자전축 경사의 변화(약 4.1만 년), 자전축의 세차운동(약 2.6만 년)이 복합적으로 작용하여 지구의 일사량 분포를 바꾸고 빙하기와 간빙기 주기를 유발한다는 이론은?',
      options: ['밀란코비치 주기 (Milankovitch Cycles)', '도플러 효과 기후론', '챈들러 요동설', '모호로비치치 주기'],
      correctIndex: 0,
      explanation: '세르비아의 지구물리학자 밀루틴 밀란코비치가 계산한 천문학적 궤도 역학으로, 북반구 고위도 지역의 여름철 일사량이 줄어들 때 빙하가 녹지 않고 누적되어 빙하기가 시작됨을 입증했습니다.',
      deepKnowledge: '1976년 해양 퇴적물 코어의 산소 동위원소 비율 분석(Hays et al.)을 통해 지질학적 빙하기 주기와 밀란코비치 계산이 완벽하게 일치함이 실증되었습니다.',
      sourceOrTrivia: 'Milankovitch (1941) & Hays, Imbrie, Shackleton (1976) Science',
    },
    {
      id: 'geo_6',
      topic: '지구과학 & 환경생태',
      difficulty: 'hard',
      difficultyLabel: '심화 지식',
      question: '노벨 화학상 수상자 파울 크뤼천(Paul Crutzen)이 제안한 지질시대 명칭으로, 산업혁명 이후 인간의 기술 문명과 경제 활동이 지구 시스템의 지형, 대기 성분, 생물다양성에 지질학적 지층 수준의 돌이킬 수 없는 흔적을 남기고 있는 새로운 지질시대를 뜻하는 용어는?',
      options: ['인류세 (Anthropocene)', '홀로세 (Holocene)', '신생대 플라이스토세', '캄브리아세'],
      correctIndex: 0,
      explanation: '인류세는 화석연료 연소로 인한 탄소 동위원소 변화, 플라스틱 테크노포실(Technofossils), 핵실험 방사성 낙진, 닭 뼈 화석 등이 지구 퇴적층에 영구적인 지질학적 신호로 남는 시대를 상징합니다.',
      deepKnowledge: '인간이 자연에 적응하는 존재에서 지구 환경 시스템 자체를 교란하는 가장 강력한 지질학적 동력원으로 변모했음을 상징하는 개념입니다.',
      sourceOrTrivia: 'Crutzen & Stoermer (2000) IGBP Global Change Newsletter',
    },
    {
      id: 'geo_7',
      topic: '지구과학 & 환경생태',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '스톡홀름 회복력 센터의 요한 록스트룀(Johan Rockström) 등이 2009년 제시한 글로벌 지구시스템 프레임워크로, 기후변화·생물다양성 손실·질소/인 순환 등 인류가 안전하게 생존할 수 있는 9개 환경 영역의 한계치를 정량화한 모델은?',
      options: ['행성 한계선 (Planetary Boundaries)', '탄소 중립 넷제로 지수', '생태 발자국', 'IPCC 온실가스 배출경로'],
      correctIndex: 0,
      explanation: '행성 한계선은 9대 핵심 영역(기후변화, 생물다양성 보전, 담수 이용, 토지 이용, 화학물질 오염 등) 중 하나라도 임계값(Threshold)을 넘어서면 지구 시스템 전체가 불가역적인 파국에 이를 수 있다고 경고합니다.',
      deepKnowledge: '최근 2023년 연구 평가에 따르면 9개 한계선 중 생물권 보전, 토지 변화, 담수 변화, 신규 물질 유입 등 이미 6개 이상의 경계선이 위험 수위를 초과한 것으로 분석되었습니다.',
      sourceOrTrivia: 'Rockström et al. (2009) Nature / Richardson et al. (2023) Science Advances',
    },
    {
      id: 'geo_8',
      topic: '지구과학 & 환경생태',
      difficulty: 'profound',
      difficultyLabel: '심오한 지식',
      question: '지구 역사상 약 24억 년 전 시아노박테리아(남세균)의 산소 발생 광합성으로 인해 대기 중 산소 농도가 급격히 상승하며, 당시 혐기성 생명체 대부분이 절멸하고 온실가스 메탄이 산화되어 지구 전체가 얼어붙었던 사건은?',
      options: ['대산화 사건 (Great Oxidation Event, GOE)', '캄브리아기 대폭발', '페름기 말 대멸종', 'K-Pg 멸종 사건'],
      correctIndex: 0,
      explanation: '시아노박테리아가 엽록소를 통해 태양빛과 물을 분해하여 방출한 산소는 초기에는 해양의 철 이온과 반응해 호상철광층(BIF)을 형성한 뒤 대기로 분출되어 지구 환경을 완전히 뒤바꾸었습니다.',
      deepKnowledge: '이로 인해 강력한 온실효과를 유지하던 메탄(CH4)이 CO2와 H2O로 산화되며 온실효과가 급감하여 휴로니안 빙하기(Huronian Glaciation)라는 사상 최악의 전 지구 동결 사건이 발생했습니다.',
      sourceOrTrivia: 'Holland (2006) "The oxygenation of the atmosphere and oceans"',
    },
  ],
};

// Merge base curated questions with expanded questions, deep bank questions, mega questions, and ultra questions (Total: 1,500 curated questions)
export const CURATED_QUESTIONS: Record<string, Question[]> = Object.keys(BASE_CURATED_QUESTIONS).reduce(
  (acc, key) => {
    acc[key] = [
      ...(BASE_CURATED_QUESTIONS[key] || []),
      ...(EXPANDED_QUESTIONS[key] || []),
      ...(DEEP_BANK_QUESTIONS[key] || []),
      ...(MEGA_QUESTIONS[key] || []),
      ...(ULTRA_QUESTIONS[key] || []),
    ];
    return acc;
  },
  {} as Record<string, Question[]>
);


