import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Question } from '../src/types/quiz.ts';
import { buildDomainQuestions, type RawQDef } from './generators/types.ts';

import { SPACE_RAW_ITEMS } from './data/spaceData.ts';
import { PHYSICS_RAW_ITEMS } from './data/physicsData.ts';
import { BIO_RAW_ITEMS } from './data/bioData.ts';
import { GEO_RAW_ITEMS } from './data/geoData.ts';
import { KOREAN_HISTORY_RAW_ITEMS } from './data/koreanHistoryData.ts';
import { WORLD_HISTORY_RAW_ITEMS } from './data/worldHistoryData.ts';
import { PHILOSOPHY_RAW_ITEMS } from './data/philosophyData.ts';
import { LITERATURE_RAW_ITEMS } from './data/literatureData.ts';
import { AICS_RAW_ITEMS } from './data/aicsData.ts';
import { ECONOMY_RAW_ITEMS } from './data/economyData.ts';
import { PSYCHOLOGY_RAW_ITEMS } from './data/psychologyData.ts';
import { ART_RAW_ITEMS } from './data/artData.ts';

import { EXAM_DATA_1 } from './data/examData1.ts';
import { EXAM_DATA_2 } from './data/examData2.ts';

interface DomainDef {
  key: string;
  prefix: string;
  topic: string;
  items: RawQDef[];
}

const DOMAINS: DomainDef[] = [
  { key: 'space', prefix: 'sp', topic: '우주 & 천문학', items: SPACE_RAW_ITEMS },
  { key: 'physics_quantum', prefix: 'pq', topic: '물리학 & 양자역학', items: PHYSICS_RAW_ITEMS },
  { key: 'biology_medicine', prefix: 'bm', topic: '생명과학 & 의학', items: BIO_RAW_ITEMS },
  { key: 'earth_environment', prefix: 'geo', topic: '지구과학 & 환경생태', items: GEO_RAW_ITEMS },
  { key: 'korean_history', prefix: 'kh', topic: '한국사 탐구', items: KOREAN_HISTORY_RAW_ITEMS },
  { key: 'world_history', prefix: 'wh', topic: '세계사 & 문명', items: WORLD_HISTORY_RAW_ITEMS },
  { key: 'philosophy', prefix: 'ph', topic: '철학 & 사상', items: PHILOSOPHY_RAW_ITEMS },
  { key: 'literature_classics', prefix: 'lit', topic: '문학 & 세계 고전', items: LITERATURE_RAW_ITEMS },
  { key: 'ai_cs', prefix: 'ai', topic: 'AI & 컴퓨터 과학', items: AICS_RAW_ITEMS },
  { key: 'economy', prefix: 'ec', topic: '경제 & 금융', items: ECONOMY_RAW_ITEMS },
  { key: 'psychology_brain', prefix: 'psy', topic: '심리학 & 인지과학', items: PSYCHOLOGY_RAW_ITEMS },
  { key: 'art_culture', prefix: 'art', topic: '미술 & 문화예술', items: ART_RAW_ITEMS },
];

console.log('🚀 Building Mega Question Bank (960 items across 12 domains: 80 items each)...');

const megaMap: Record<string, Question[]> = {};
let totalNewQuestions = 0;
const errors: string[] = [];

for (const d of DOMAINS) {
  const examItems = (EXAM_DATA_1[d.key] || []).concat(EXAM_DATA_2[d.key] || []);
  const combinedItems = [...d.items, ...examItems];

  if (combinedItems.length !== 80) {
    errors.push(`Domain "${d.key}" has ${combinedItems.length} items (expected 80)`);
  }

  // Pre-validate every item
  combinedItems.forEach((item, idx) => {
    const label = `${d.key}[${idx}]`;
    if (!item.q || item.q.trim().length < 5) errors.push(`${label} question too short`);
    if (!Array.isArray(item.opts) || item.opts.length !== 4) errors.push(`${label} options != 4`);
    if (new Set(item.opts).size !== 4) errors.push(`${label} options duplicate: ${JSON.stringify(item.opts)}`);
    if (typeof item.cIdx !== 'number' || item.cIdx < 0 || item.cIdx > 3) errors.push(`${label} invalid cIdx: ${item.cIdx}`);
    if (!item.exp || item.exp.trim().length < 10) errors.push(`${label} exp too short`);
    if (!item.deep || item.deep.trim().length < 10) errors.push(`${label} deep too short`);
    if (!['easy', 'medium', 'hard', 'profound'].includes(item.diff)) errors.push(`${label} invalid diff: ${item.diff}`);
  });

  const questions = buildDomainQuestions(d.prefix, d.topic, combinedItems);
  megaMap[d.key] = questions;
  totalNewQuestions += questions.length;
  console.log(`  ✓ ${d.topic} (${d.key}): ${questions.length} questions built (IDs: ${questions[0].id} ~ ${questions[questions.length - 1].id})`);
}

if (errors.length > 0) {
  console.error('❌ Validation Errors encountered during build:');
  errors.forEach((err) => console.error(`  - ${err}`));
  process.exit(1);
}

console.log(`\n🎉 Total new questions built and validated: ${totalNewQuestions}`);

// Output file path
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const outPath = path.resolve(__dirname, '../src/data/megaQuestions.ts');

const fileContent = `// Auto-generated by scripts/buildMegaBank.ts
// Total: ${totalNewQuestions} high-quality curated questions across 12 domains
import type { Question } from '../types/quiz.ts';

export const MEGA_QUESTIONS: Record<string, Question[]> = ${JSON.stringify(megaMap, null, 2)};
`;

fs.writeFileSync(outPath, fileContent, 'utf-8');
console.log(`💾 Successfully written to ${outPath} (${(Buffer.byteLength(fileContent) / 1024).toFixed(1)} KB)`);
